### ISSUE TITLE
ImportError: cannot import name 'joblib'

### ISSUE THREAD

**Issue by Kmoorthi1989** [joblib/joblib#1059]
I'm getting **ImportError: cannot import name 'joblib'** error while run python app. App file contain **from sklearn.externals import joblib**,, sklearn and joblib library already installed.

Please help me.

**Comment by ogrisel** [comment]
This code was written for an older version of scikit-learn.

Just use:

```python
import joblib
```

instead in the code.

If this is a library you cannot modify your self or cannot update to a version compatible with the latest version of scikit-learn, please downgrade the version of scikit-learn to use a compatible version.

**Comment by Elyas-Demeke** [comment]
> This code was written for an older version of scikit-learn.
> 
> Just use:
> 
> ```python
> import joblib
> ```
> 
> instead in the code.
> 
> If this is a library you cannot modify your self or cannot update to a version compatible with the latest version of scikit-learn, please downgrade the version of scikit-learn to use a compatible version.

This worked for me, Thanks

**Comment by dinokv** [comment]
Change` from 

sklearn.externals import joblib `

to `

import joblib as jb`

**Comment by NirmalManickam** [comment]
> > This code was written for an older version of scikit-learn.
> > Just use:
> > ```python
> > import joblib
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead in the code.
> > If this is a library you cannot modify your self or cannot update to a version compatible with the latest version of scikit-learn, please downgrade the version of scikit-learn to use a compatible version.
> 
> This worked for me, Thanks

> This one worked for me, Thanks

**Comment by raja7dr** [comment]
instead of using
`from sklearn.externals import joblib` 
Try this
`import joblib`
