### ISSUE TITLE
about using locky mode joblib. 

### ISSUE THREAD

**Issue by sassan72** [joblib/joblib#1075]
I could successfully run my code with multiprocessing mode joblib. here is the command line that I used to run the code in parallel mode:

rr = Parallel(n_jobs=-1, backend="locky")(delayed(bh_diag)(N, M, Mx, My, U, m[i], J, Vx, Vy) for i in range(0, len(m)) )

how can I run it with locky mode? which one is more powerful? multiprocessing or locky. I know that locky take advantage of both multiprocessing and multithreading.

**Comment by tomMoral** [comment]
The name of the backend is `loky` and not `locky`. Does that fix your problem?

**Comment by tomMoral** [comment]
As for the more powerful, it does not really change the computation power simply the way the workers are started:
- `multiprocessing`: workers are started for each call to `Parallel` with `fork` (which is quick). It is easier to share object between the two processes are they are clone of each other. But this *cloning* can lead to bad behavior with C-level lib such as BLAS so it is not recommended as it can lead to program freeze.
- `loky`: use a reusable pool of worker started with `spawn` (which is slow). But hopefully you should pay the spawning cost only once. Sharing object is also a bit more ocmplicated. But it should be safer as it respect the POSIX convention so there should be no hang.

The recommended backend is thus `loky`, except if you have a specific pattern that cannot be handled with `loky`.

**Comment by ogrisel** [comment]
Closing this issue. I think @tomMoral is complete. Feel free to reopen if it's not the case.

**Comment by sassan72** [comment]
thanks. sorry for misspelling. loky.

**Comment by tomMoral** [comment]
No problem! cool if this solved you issue.
