### ISSUE TITLE
two output value from joblib function

### ISSUE THREAD

**Issue by sassan72** [joblib/joblib#1081]
```python
with parallel_backend("multiprocessing"):
        g, g_bias = Parallel(n_jobs=-2)(delayed(gradients)(var_corrected, feats_train_batch[j], Y_train_batch[j], bias) for j in range(batch_size) )
        grads += g / batch_size
        grad_bias +=g_bias / batch_size
```

I got this error:

```python-traceback
TypeError                                 Traceback (most recent call last)
<ipython-input-9-147a7cd01c32> in <module>
     29     with parallel_backend("multiprocessing"):
     30         g, g_bias = Parallel(n_jobs=-2)(delayed(gradients)(var_corrected, feats_train_batch[j], Y_train_batch[j], bias) for j in range(batch_size) )
---> 31         grads += g / batch_size
     32         grad_bias +=g_bias / batch_size
     33 

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'
```

**Comment by ogrisel** [comment]
What does your gradients function return? Do you have batch_size of 2?

```python
Parallel(n_jobs=-2)(delayed(gradients)(var_corrected, feats_train_batch[j], Y_train_batch[j], bias) for j in range(batch_size) )
        grads += g / batch_size
```

is fundamentally equivalent to:

```python
[gradients(var_corrected, feats_train_batch[j], Y_train_batch[j], bias) for j in range(batch_size)]
```

so the code above makes little sense to me.

**Comment by sassan72** [comment]
def gradients(params, feature, label, bias=0):
    grads = np.zeros_like(params)
    imag = imaginary(params, params, feature)
    for i in range(params.shape[0]):
        for j in range(params.shape[1]):
            params_bis = np.copy(params)
            
            params_bis[i][j][0]+=np.pi
            grads[i][j][0] = -0.5 * real(params, params_bis, feature)
            params_bis[i][j][0]-=np.pi
            
            params_bis[i][j][1]+=np.pi
            grads[i][j][1] = 0.5 * (imaginary(params, params_bis, feature) - imag)
            params_bis[i][j][1]-=np.pi
            
            params_bis[i][j][2]+=np.pi
            grads[i][j][2] = 0.5 * (imaginary(params, params_bis, feature) - imag)
            params_bis[i][j][2]-=np.pi
    p = execute_circuit(params, feature, bias=bias) 
    grad_bias = (p - label) / (p * (1 - p)) 
    grads *= grad_bias
    return grads, grad_bias

exactly, the gradient function returns grads, grad_bias. 

as you mentioned the function is this : gradients(var_corrected, feats_train_batch[j], Y_train_batch[j], bias) and batch_size is 2.

**Comment by sassan72** [comment]
I considered batch size equal to 2, Just for easy run.
But for my problem I have to consider it 50.

**Comment by sassan72** [comment]
the code runs well without using parallelization. Actually, I used multiprocessing and loky methods for parallelization before. Both of them are great. but I haven't done for multi return values case so far. like this
with parallel_backend("loky", inner_max_num_threads=4):
    rr = Parallel(n_jobs=-1)(delayed(bh_diag)(N, M, Mx, My, U, m[i], J, Vx, Vy) for i in range(0, len(m)) )
this has only one return value.

**Comment by sassan72** [comment]
thanks Olivier. Problem solved.
