### ISSUE TITLE
Recent versions are missing from the changelog in readthedocs

### ISSUE THREAD

**Issue by alegonz** [joblib/joblib#1087]
Hi there :)

When perusing the documentation I just noticed that the [changelog](https://joblib.readthedocs.io/en/latest/developing.html#latest-changes) as shown in readthedocs is missing the changes for versions 0.15.0 onward.

**Comment by ogrisel** [comment]
Thanks for the report. I fixed it in: 43a077ebb44bb4ead64175510bec13b4c3998607

The changelog at https://joblib.readthedocs.io/en/latest/developing.html#latest-changes has now been updated to show 0.16.0 and 0.15.0 as expected.
