### ISSUE TITLE
Loky process worker respawn in a Flask app

### ISSUE THREAD

**Issue by zacqed** [joblib/joblib#1100]
1. While converting a function to execute in parallel using JobLib within a flask application deployed with gunicorn, Loky back-end respawns the entire application when the function is executed. i.e. (njobs=-1) workers spawn the entire flask app all over again. Is there any way around it?

2. Is there a way to start the loky workers while starting the application itself, this would save a lot of time starting these workers when the function is executed?

Thanks

**Comment by ogrisel** [comment]
This might be related to https://github.com/joblib/loky/issues/207 .

Could you please provide us with a minimal reproducer?

**Comment by zacqed** [comment]
Shifted to multiprocessing as the backend and it works fine. Th related looks to be the problem here. 

I am closing it as a duplicate at this time.
