### ISSUE TITLE
How to remove None values when using Parallel?

### ISSUE THREAD

**Issue by ajinra020307** [joblib/joblib#1101]
I try to use joblib.Parallel for running a loop in parallel
`
output = joblib.Parallel(n_jobs=self.concurrency)(joblib.delayed(my_function)(way) for way in self.ways)`

my_function returns values based on a condition. So if it fails the condition it returns None.
But i dont need None values in output list

how can i do this?

**Comment by tomMoral** [comment]
There is no direct mechanism to filter the results in `joblib`.

You have to filter the items afterwards, for instance with `output = [v for v in output if v is not None]`.
