### ISSUE TITLE
ordinary for loop is faster than joblib parallel , delayed combination

### ISSUE THREAD

**Issue by Mohamed209** [joblib/joblib#1105]
I was testing the performance 
`from math import sqrt`
 `import time`
 `from joblib import Parallel, delayed`
 `s = time.time()`
 `[sqrt(i ** 2) for i in range(1000000)]`
 `print(time.time()-s)`
 `s1 = time.time()`
 `Parallel(n_jobs=-1)(delayed(sqrt)(i ** 2) for i in range(1000000))`
 `print(time.time()-s1)`
results 
0.4646732807159424 s
39.72209048271179 s
 it is even 100x slower than ordinary foor loop

**Comment by JaKasb** [comment]
In your code, the serialization-time is higher than the compute-time.
All distributed computing methods cause some form of overhead.
Your observation is not a specific joblib-problem, nor is an issue for the intended use case of joblib.

**Comment by GaelVaroquaux** [comment]
Thanks for the answer @JaKasb

**Comment by Rob192** [comment]
Thanks @JaKasb, I run into the same issue myself. If I may : @Mohamed209 was using the exemple given in the documentation at the page "Embarrassingly parallel for loops". I find it confusing to give as an example, a function for which it is not usefull to use joblib to speed up the execution. At least, I would expect explanation or a warning as a new user of joblib :) 
I tried to use Pool from multiprocessing, and it is indeed speeding the execution. 

``` python
from math import sqrt
import time
from multiprocessing import Pool
def f(x):
    return sqrt(x ** 2) 
for i in [1, 2, 5, 20]:
    start_time = time.time()
    with Pool(i) as p:
        a = p.map(f, range(10000000))
    print(f'{i} CPU {time.time()- start_time}')
```

**Comment by JaKasb** [comment]
The compute time of f() is 300ns.
For comparison : 1 RAM access is 100ns
Unless all data-structures are inside the CPU caches, such short functions are useless as a benchmark.
You are effectively benchmarking CPython, the OS Scheduler and the CPU Architecture.
If you watch htop during execution, you will see only 1 loaded core.

Furthermore Pool.map() is much faster than Pool.apply_async()
```python
from math import sqrt
import time
from multiprocessing import Pool
from joblib import Parallel, delayed

def f(x): return sqrt(x ** 2)
tasks = list(range(int(1E5)))

for n in [1, 2, 5, 20]:
    start_time = time.time()
    with Pool(n) as p:
        a = p.map(f, tasks)
    print(f'{n:02d} CPU {time.time() - start_time:.2f}')
    
for n in [1, 2, 5, 20]:
    start_time = time.time()
    with Pool(n) as p:
        a = [p.apply_async(f, i) for i in tasks]
    print(f'{n:02d} CPU {time.time() - start_time:.2f}')
    
for n in [1, 2, 5, 20]:
    start_time = time.time()
    Parallel(n_jobs=n, backend='multiprocessing', verbose=0)\
        (delayed(f)(i) for i in tasks)
    print(f'{n:02d} CPU {time.time() - start_time:.2f}')
```

I agree that the example under https://joblib.readthedocs.io/en/latest/parallel.html
does not achieve a speedup. 
However the example intends to show the syntax und use-case.
