### ISSUE TITLE
FEATURE: Allow pathlib.Path type as location parameter for Memory class and so on

### ISSUE THREAD

**Issue by Mandroide** [joblib/joblib#1116]
I thought it could be good to allow [pathlib.Path](https://docs.python.org/3/library/pathlib.html) as [location parameter](https://github.com/joblib/joblib/blob/master/joblib/memory.py#L851), among those the Memory class is one.

**Comment by majidaldo** [comment]
Ran into this when implementing backend #1124 .

On that note, I think Path should also have attributes: module_name, func_name, ...etc.

**Comment by Mandroide** [comment]
@tomMoral What do you think of this?

**Comment by Mandroide** [comment]
@tomMoral What do you think of this? This issue needs at least a label.

**Comment by tomMoral** [comment]
I though this feature has been implemented in #817. See [here](https://github.com/joblib/joblib/blob/master/joblib/memory.py#L108).
Did you ran into issues with this feature?

If not, the doc could certainly be improved to mention this. PR welcome :)

**Comment by Mandroide** [comment]
> I though this feature has been implemented in #817. See [here](https://github.com/joblib/joblib/blob/master/joblib/memory.py#L108).
> Did you ran into issues with this feature?
> 
> If not, the doc could certainly be improved to mention this. PR welcome :)

You are right, it was implemented. I thought it wasn't since the docstring didn't specify it as such. Thanks for!

I didn't run into issues. I
