### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by PriyatamNayak** [joblib/joblib#1118]
Am trying to dump the model output to a pickle file getting  TypeError: can't pickle _thread.RLock objects error

```python
tmp=tempfile.TemporaryFile() 
with open(tmp.name, 'wb') as fp:
        joblib.dump(data_to_dump, fp)

data_to_dump={'2y_grt_yield': {'ts_model': <ct_ml.tcss.timeseries_analysis_development.TimeSeriesAnalysis at 0x7f83f189bef0>,
  'model_type': 'autoprophet',
  'metrics': {'mae': 0.902170708413049,
   'std_mae': 0.013925235278416458,
   'mape': 658.2934702887475,
   'std_mape': 51.7895989325371,
   'rmse': 0.9022781717940771,
   'r2_score': -16734.725038556324}}}
```

**Comment by tomMoral** [comment]
This is not a issue specific with `joblib` but with `pickle`.

I don't know what is your model `ct_ml.tcss.timeseries_analysis_development.TimeSeriesAnalysis` but it seems it has a reference to a `RLock` which is an object that cannot be pickled. This makes the object not picklable with the default method.

The solution would be to implement a `__reduce__` method (see doc [here](https://docs.python.org/3/library/pickle.html#object.__reduce__)) in the `TimeSeriesAnalysis` object to make it picklable. Basically, this methods needs to return a function  `func` and some arguments `args` that permits to reconstruct the object `obj` as `obj = func(*args)`.

Closing this issue as it is not specific to `joblib`.
