### ISSUE TITLE
Is that possible to open multiple consoles for multiple job task?

### ISSUE THREAD

**Issue by boshueryi** [joblib/joblib#1134]
Hello, 
I am using joblib for multiprocessing task management. I have a function that would be called in every processing task. In this function I would print some necessary information to the console. The problem is, for example, when I run 2 tasks at the same time, the printing information would be mixed together in one console. It would be very hard to read.
So I would like to ask if it is possible to open a new console for every processing task, when the jobs started by joblib?
THANKS A LOT!

**Comment by GaelVaroquaux** [comment]
> So I would like to ask if it is possible to open a new console for every processing task, when the jobs started by joblib?

No. For very fundamental reasons, this is not possible. A Python program in general has no notion of console (this notion is actually Windows-specific), and cannot manipulate these objects. They may not exist (think for instance a Python script powering a web server).

I think that the tool that you are looking for is the logging functionality: https://docs.python.org/3/library/logging.html

**Comment by tomMoral** [comment]
Note that while you cannot open different consoles, you can separate the logging stream by using [the `logging` library from std lib](https://docs.python.org/3/library/logging.html).
By streaming the logs to different files, you can easily open different terminals to tail those logs.
