### ISSUE TITLE
Joblib error when editting files

### ISSUE THREAD

**Issue by fishfishson** [joblib/joblib#1135]
I edit my dataloder file after running it. However, joblib report error like following
``` python
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/deepsdf/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/root/miniconda3/envs/deepsdf/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/root/workspace/voxel2sdf/data/chaos.py", line 290
    class ChaosShapeDataset(Dataset):
                                    ^
SyntaxError: unexpected EOF while parsing
"""
```
So during running, joblib will reload the file dynamicly?

**Comment by tomMoral** [comment]
There is no dynamic reloading in `joblib`.

However, it is very possible that a new worker has been respawned after you changed your file.
So in this case the new file is loaded.

**Comment by ogrisel** [comment]
Indeed. If the worker timeout after idling for a while and then a new parallel job is dispatched, we start new python workers. So joblib assumes that the code stays the same on disk for the whole duration of the main process.

Closing as you don't see any simple fix for this.
