### ISSUE TITLE
Can joblib.parallel return data asynchronously?

### ISSUE THREAD

**Issue by Rgcsh** [joblib/joblib#1148]
```
from concurrent.futures import as_completed
```
just like  above, When I use mulitprocess,I want return data asynchronously!
Can  joblib.parallel  achieve?

**Comment by jjerphan** [comment]
Unfortunately no, `joblib.Parallel` is purely synchronous. 

Here are some pasts discussions regarding this subject: https://github.com/joblib/joblib/issues/79.

**Comment by tomMoral** [comment]
There is an ongoing PR (#588 ) that implement something not so far from this.
It is not totally `as_completed` as it still returns the result in order.

It would be nice to take the time to merge this feature but we still have some debate on the API/scope.

**Comment by Rgcsh** [comment]
@jjerphan @tomMoral   Thanks for reply! I have implemented this function in  [this link](https://github.com/Rgcsh/joblib/commit/970a430699919664fa7be5af456c7a5957ef8469) . Thanks a lot!!!
