### ISSUE TITLE
Add ability for joblib.Memory to delete entries not recently used

### ISSUE THREAD

**Issue by jwodder** [joblib/joblib#1170]
It would be useful if `joblib.Memory` supported more fine-grained cache clearing operations than just deleting everything; specifically, we would like the option to delete all but the X most-recently used entries or all but the most recent entries adding up to no more than a given size.

**Comment by GaelVaroquaux** [comment]
I think that you are look for the "bytes_limit" argument of joblib.Memory
https://joblib.readthedocs.io/en/latest/generated/joblib.Memory.html

Tell us if it does the job.

**Comment by jwodder** [comment]
I missed that somehow.  How does `reduce_size()` decide what entries to delete?  It is based on access timestamps or something else?

**Comment by tomMoral** [comment]
Yes, `reduce_size` delete the elements based on the `last_access` property.
See here: https://github.com/joblib/joblib/blob/457d2c8a926105fd156b1dfccfaae3e500d22451/joblib/_store_backends.py#L309

We should update the doc to explain this part.
