### ISSUE TITLE
Using dict like operation with Joblib

### ISSUE THREAD

**Issue by ShivKJ** [joblib/joblib#1209]
Hi,

As I explored docs on cache, I found it is more towards decorating a function. 

Can we use it to store key-value pairs with joblib? For example,

```python
memory = Memory('cache')

memory['key'] = value # value for this key is stored in `cache` in similarly manner 

# later on

print(memory['key']) # prints the data. If data does not exists then raises `KeyError` error

print(memory.get('key-not-exists')) # returns None if this key does not exists.
```

Similarly, we can have few more use dict operations.

Does there exist some functions in `joblib` for the similar requirement?

**Comment by GaelVaroquaux** [comment]
No, this is not a functionality covered by joblib. joblib is for function.

For disk-based storage, you can have a look at the Python module https://docs.python.org/3/library/shelve.html
