### ISSUE TITLE
Default returned value for timeout tasks

### ISSUE THREAD

**Issue by nlhkh** [joblib/joblib#1221]
Currently I have a job that runs 140000 tasks using Joblib. My problem is that sometimes, under some conditions, a task is stuck, i.e. it does not give error, but never finishes, due to third party library's bug. `timeout` is a good option in this case, but it throw an exception as a whole job, thus the other 139999 tasks did not get to finish, although they are perfectly fine.

What I propose is to optionally set a default value, e.g. `Parallel(..., timeout=10, timeout_default="some value to return",...)`. If `timeout_default is None`, then it will behave just as before. If `timeout_default not None`, then it will return the default value, with a warning, instead of throwing an exception.

**Comment by GaelVaroquaux** [comment]
Isn't this something that you can code in the function that you are
submitting to joblib?

**Comment by nlhkh** [comment]
No, I cannot really timeout a Python function without using threading or multiprocessing. You are thinking of the case when my function raise an exception, which I can catch. This is the case when **no exception is raise**, and the function *never finishes*.

**Comment by nlhkh** [comment]
@GaelVaroquaux could you help me find out why the test `test_nested_loop_error_in_grandchild_resource_tracker_silent` failed in python38 and python37?

I have run the test on my local machine (Apple M1), with both python38 and python37, and it was successful. I don't think my change affect any existing behavior.

**Comment by nlhkh** [comment]
@GaelVaroquaux do you approve of this direction? I haven't seen any any response.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux do you approve of this direction? I haven't seen any any response.

I am overwhelmed by things to attend to, and will not have time to look
at the PR. Sorry

**Comment by nlhkh** [comment]
> @GaelVaroquaux do you approve of this direction? I haven't seen any any response.
> I am overwhelmed by things to attend to, and will not have time to look at the PR. Sorry

Ah I understand. Whenever you have time.

For now I temporarily fixed my problem by using loky to spawn another process with timeout, although this is not ideal, because I spawn more processes, which incurs more overhead.

**Comment by bkmi** [comment]
I would be interested in this feature.

**Comment by lesteve** [comment]
I guess this is a duplicate of #367? To be frank, this is unlikely to be at the top of our priority list in the near future ...
