### ISSUE TITLE
Loading models weights from .h5 file

### ISSUE THREAD

**Issue by jithincheriyan** [joblib/joblib#1241]
Hi,

My project pipeline has multiple deep learning models and all those need to be loaded at different times of execution. All model weights  are saved as .h5 files. I was wondering is there anyways to load those h5 files using joblib to speed up the pipeline? Or would you please be able to recommend some other packages if its not possible with joblib?

Cheers

**Comment by GaelVaroquaux** [comment]
No, this is not possible with joblib.

I don't know out of the top of my head which package could help.

**Comment by jithincheriyan** [comment]
All good, thank you for the support.
