### ISSUE TITLE
How to yield result instead of getting the result list?

### ISSUE THREAD

**Issue by BrightXiaoHan** [joblib/joblib#1242]
This is my code
```python
import time
from joblib import Parallel, delayed
def producer():
    with open("some_large_file") as f:
        for line in f:
            yield line

def func(i):
    time.sleep(1)  # or other time comsumption operations
    return i
out = Parallel(n_jobs=10, verbose=100)(delayed(func)(i) for i in producer())
print(out)
```
My purpose is to read a large file (about 10G)，and do some operations on each line.
The final result will be saved in the `out` variable, which is a list object stored in memory. Can joblib yield immediate results during run jobs? Then I can write the result content to a file rather than store them in the memory?

**Comment by npyoung** [comment]
Second this feature request. Often my parallel jobs have large outputs that I want to process and write to disk as they become available rather than keep them around in memory until all jobs have completed. I would use something like `multiprocessing.Pool.imap` for this but I need the advanced pickling and memmap conversion of joblib.

**Comment by BrightXiaoHan** [comment]
Hi @npyoung, Could you please share your code snippet with me, which you use `multiprocessing.Pool.imap` to address this issue?

**Comment by GaelVaroquaux** [comment]
This feature is quite challenging to code (danger of race conditions, in particular when dealing with exceptions).

There is a pull request in progress on this feature:
https://github.com/joblib/joblib/pull/588
We hope to merge in soonish, but these things are tricky.

**Comment by npyoung** [comment]
Thanks @GaelVaroquaux, I will see if I can get the @fcharras fork working for me. I have a nice field test scenario for it... see below.

@BrightXiaoHan this is a pattern I tend to use when rendering videos frame-by-frame
```python
from multiprocessing import Pool
with Pool() as pool:
    rendered_video_frames = pool.imap(make_video_frame, frame_times)
    for frame in rendered_video_frames:
        movie.write_frame(frame)
```
`imap` returns the video frames in order and allows already-written frames to be garbage-collected from memory.

Note that `make_video_frame` needs to importable and multiprocessing will either copy or miss globals (depending on platform and python version), which are two key constraints/problems joblib helps with.

**Comment by BrightXiaoHan** [comment]
@npyoung Thanks for your sharing.
