### ISSUE TITLE
Restarting failed workers

### ISSUE THREAD

**Issue by Midnighter** [joblib/joblib#1249]
I'm currently running some Python code in parallel using `multiprocessing.get_context("spawn").Pool()`. The code in those processes calls a Java library that I have no control over and sometimes segfaults. Thus I was wondering if joblib/loky has the ability to restart failed workers. I don't mind that some tasks fail but I don't want the program to be interrupted by the error and I'd like to maintain a stable number of processes, of course.

Thank you for your help.

**Comment by ogrisel** [comment]
There is no built-in feature to do this in joblib in general as it would be very backend dependent (for instance it would not be possible at all with the threading backend and complex to do with the dask backend).

That being said it should be possible to do write your own subprocess execution wrapper using cloudpickle and implement your own handling of worker crash. You can take inspiration of:

https://github.com/cloudpipe/cloudpickle/blob/master/tests/testutils.py#L143

**Comment by Midnighter** [comment]
Thank you for the info. I'll see what I can come up with.
