### ISSUE TITLE
Code Change of a nested function in Memory.cache

### ISSUE THREAD

**Issue by bharathc346** [joblib/joblib#1287]
Hi I have a pretty simple setup using joblib's memory caching. Although the function I want to cache is a nested one i.e it calls another helper function which does some of the core work. Currently if I change code in the helper function joblib memory does not recompute results and will still retrieve from the old cache reflecting the older version of the helper function . 

For example:

```
import joblib
import time
from typing import List

memory = joblib.Memory("cache", verbose=3)

# main func
def fake_costly_computation(data: List[str], cost: int) -> List[List[str]]:
    return [x.split() for x in data]

# helper func
def _costly_computation(cost: int) -> None:
    time.sleep(cost)


if __name__ == "__main__":
    data = ["Hi how are u", "good how bout u"]
    res = memory.cache(fake_costly_computation)(data, 10)
```

Say I modify my code to: 
```
def _costly_computation(cost: int) -> None:
    time.sleep(2 * cost)
```

then joblib.Memory still loads the cached result instead of computing `fake_costly_computation` again. I believe it is because of this [line](https://github.com/joblib/joblib/blob/ea8562fdeda5c20ed059fdeeff83b1b4792dfa7a/joblib/memory.py#L700-L702)

`old_func_code` and `func_code` only get the code of the top level function and compare those and since those are equal we retrieve from the cache. 

I am wondering if there is a good way of dealing with this, maybe increasing `stacklevel` (will try this a bit later, currently I think it is at 4), or another way?

**Comment by GaelVaroquaux** [comment]
Joblib doesn't do a deep analysis of the code: it would induce too much computational cost. 

The right way is to clear the function cache manually.  The memoized function (which is returned by the decorator) has a method to do this.

**Comment by pascalwhoop** [comment]
just found this and very disappointed by this, an AST analysis of the tree of functions being called is very cheap and could be done during boot time. Why would this be "expensive"?

**Comment by GaelVaroquaux** [comment]
> just found this and very disappointed by this, an AST analysis of the tree of functions being called is very cheap and could be done during boot time.

> Why would this be "expensive"?

Functions can be modified dynamically. It would have to be done on a regular basis. I also fear false positives.
