### ISSUE TITLE
Can `joblib.Parallel` be used with `n_jobs=1`, while still using parallel code?

### ISSUE THREAD

**Issue by maxfrei750** [joblib/joblib#1294]
First of all: Thanks for your awesome work on this project! I'm not using `joblib.Parallel` with the goal to parallelize code execution, but just to isolate the repeated serial code execution of memory-leaky external code.

While this arguably is a little hacky, it actually works quite well. However, for this to work, I need to use `n_jobs=2`, which makes sense, given the [documentation](https://joblib.readthedocs.io/en/latest/parallel.html#parallel-reference-documentation) saying:

> If 1 is given, no parallel computing code is used at all, ...

For completeness’s sake, here is the full set of parameters that I currently use:
`Joblib.Parallel(n_jobs=2, backend=loky, prefer=processes, require=None, verbose=0, timeout=None, pre_dispatch=2*n_jobs, batch_size=1, temp_folder=None, max_nbytes=None, mmap_mode=r)`

As a result, the leaked memory is reset after each two runs. I.e. each pair of runs is isolated from all other pairs of runs, which makes sense to me, given the use of `n_jobs=2`. 

Now the question: Is there a way to isolate every single run, i.e. use `n_jobs=1`, but still use the parallel code, to create separate processes?

Thanks in advance!

**Comment by tomMoral** [comment]
Hello,

No it is not currently possible with `joblib` with only the `Parallel` parameters. The idea is that when `n_jobs=1`, most of the time, you don't want the overhead of needing to create a new process to execute your code, so we special case this and just run the computation sequentially.

That being said, there is a good change that you can do it with a custom backend deriving from the `LokyBackend`, that create an executor with one worker but returns an `effective_n_jobs = 2`. This is a guess but I think this can work.

- You need to return `effective_n_jobs != 1` as this is special case for sequential execution in the code of `Parallel` so this would break some stuff.
- You can still create an executor with 1 worker in the `config`.

That being said, why don't you directly use `loky`? You can simply call

```python
from loky import get_reusable_executor

executore = get_reusable_executor(max_workers=1)
for args in list_args:
    f = executor.submit(f, *args, **kwargs)
    res = f.result()
```

this gives you a flexible API, probably more adapted to your need?

**Comment by maxfrei750** [comment]
Hi! Thanks for your detailed answer! The reason I am tied to `Parallel` is that I use it as part of [`hydra`](https://hydra.cc/docs/plugins/joblib_launcher/). So unfortunately, I cannot utilize the solution that you provided. Also, my fairly simple use-case might better be solved using `multiprocessing`.

Thank you very much for the insights that you shared! If you don't mind, I'll close this issue for now, since the initial question was answered. :+1:
