### ISSUE TITLE
Why is LZ4 compression faster than without compression in dump?

### ISSUE THREAD

**Issue by rickyrick2002** [joblib/joblib#1300]
From https://joblib.readthedocs.io/en/latest/auto_examples/compressors_comparison.html :

> Raw dump duration: 0.177s

> LZ4 dump duration: 0.114s

I downloaded the test code `compressors_comparison.py` and confirm the result.

But I don't get it, shouldn't raw dump be the fastest? How could lz4 dump faster than raw dump?

**Comment by GaelVaroquaux** [comment]
Because disk write is slower than compute.
