### ISSUE TITLE
Possible permissions issue: "semaphore or lock released too many times" fail in process_executor submit

### ISSUE THREAD

**Issue by bldrvnlw** [joblib/joblib#1322]
Versions:
joblib: 0.14.1 (sorry I'm supporting an old site that is in the process of upgrading)
python: 2.7.16

Context:

a) An apache server supporting two websites that execute logic using joblib Parallel (via php exec)
b) One website runs that logic under user xyz-apache using the system installed php (5.6)
c) A newer version of the same website that runs under a different user xyz-php using php-fpm (7.3)

Error:
In the old website a Parallel execution using the loky (default) backend works, on the new website the same code fails due to this exception in SemLock

```python-traceback
Traceback (most recent call last):
  File "/var/www/newsite/scripts/GeneSet.py", line 224, in <module>
    gs = Parallel(n_jobs=n_cores, backend="loky")(delayed(GeneSetTest)(f, filedir) for f in files)
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python2.7/dist-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python2.7/dist-packages/joblib/_parallel_backends.py", line 551, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/reusable_executor.py", line 160, in submit
    fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/process_executor.py", line 1047, in submit
    self._ensure_executor_running()
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/process_executor.py", line 1022, in _ensure_executor_running
    self._start_queue_management_thread()
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/backend/synchronize.py", line 107, in __exit__
    return self._semlock.release()
  File "/usr/local/lib/python2.7/dist-packages/joblib/externals/loky/backend/semlock.py", line 222, in release
    "semaphore or lock released too many times")
ValueError: semaphore or lock released too many times
```

Executing the code in the new website using  the old user (`sudo -u xyz-apache sh -c python`) also works. So I guess that this is triggered by a permissions difference between users xyz-php and xyz-apache. All other code on the new web site runs without errors using the new xyz-php user only the loky backend fails.

Does anyone have an idea where the permission difference might lie? What is the loky backend creating that could trigger this?

BTW using backend="multiprocessing" works (though I couldn't swear to it being stable), as does prefer="threads" though the latter takes twice as long.

**Comment by ogrisel** [comment]
Please let us know if you can reproduce this problem on the latest versions of joblib (ideally even the joblib development branch).

**Comment by ogrisel** [comment]
This could be a bug in loky but it's likely that this part of loky has evolved quite significantly if I recall correctly. So maybe this has already been fixed and I would rather not waste time chasing and old bug that does not exist anymore in the dev version.

**Comment by bldrvnlw** [comment]
Using an older cloudpickle (1.3.0) and the package [futures](https://pypi.org/project/futures/ I created a backport of joblib 1.0.1 and installed it in a virtualenv. 

The virtualenv was a complete but separate copy of the system packages installed with pip install -r requirements.txt and then the new joblib 1.0.1 backport. Activating that environment caused the joblib with loky backend to work. However uninstalling the 1.0.1 and restalling the old joblib 0.14.1 also worked in the virtualenv. So it looks like the virtualenv switch was more important than the backport

To further test a second virtualenv was created using the _--system-site-packages_ option to ensure that it was otherwise identical. Again the joblib 0.14.1 worked if executed by first switching to this virtualenv. So the puzzle is why does the main python environment fail but a switch to a virtualenv (that is nothing more than a proxy for the system environment) work?

At this point I'm no close to knowing why the error occurs, but I do have a workaround that could keep the project turning over until we complete migration from py2 to py3.

**Comment by ogrisel** [comment]
Alright. Let's close this issue for now and feel free to open a new one if you reproduce something related with a more recent version of joblib.

**Comment by bldrvnlw** [comment]
The error appears to be related to differences in the PATH environment which I was able to spot by contrasting the working and failing examples. Having modified the settings in the new php-fpm environment the joblib scheduling works. It remains puzzling though that this didn't show in other python code.
