### ISSUE TITLE
Joblib freezes when called from another module

### ISSUE THREAD

**Issue by tomrig** [joblib/joblib#1326]
I tried calling a function this i implemented in a different file/module that uses joblib Parallel and when called it just freezet completely
I have been able to replicate this with a very minimal example as seen below

calc module:
```python
from joblib import Parallel, delayed

def square_int(i):
    return i*i

def do_sth(int_list):
    result=Parallel(n_jobs=6)(delayed((square_int))(i) for i in int_list)
    return result
```

Test module:
```python
import calc
print(calc.do_sth([1,2,3,4,5,6,7,9,10]))
```

**Comment by ogrisel** [comment]
Thanks for the minimal report, unfortunately I cannot reproduce on my own machine. Can you please give the version number of joblib, Python and the type and version of your Operating System?

Which command do you use to execute the test module?

**Comment by tomrig** [comment]
Python 3.10.7
joblilb 1.1.0
Win 10 enterprise

python Test.py

**Comment by tomrig** [comment]
identified the issue 
in both of the cases i ran into the issue there was stuff outside function defs in the imported module
