### ISSUE TITLE
Breaking change in Memory constructor 

### ISSUE THREAD

**Issue by inon-peled** [joblib/joblib#1341]
In version 1.1.0, `Memory.__init__` had argument `cachedir=None`.

This argument does not appear in version 1.2.0, thus breaking compatibility with `scikit-learn` and other packages that require `joblib>=1.0.0`.

**Comment by tomMoral** [comment]
`cachedir` has been deprecated for `location` since `joblib 0.12` so it was removed in this release. (see #1236).
