### ISSUE TITLE
ENH: Provide a way to tell if Memory had a cache hit

### ISSUE THREAD

**Issue by larsoner** [joblib/joblib#1342]
It would be nice if there were a way to tell if there was a cache hit for `memory.cache(func)(*args, **kwargs)`.

Is this possible already? If so, I can add a PR to add whatever method works to the docs. If it's in the docs already and I missed it, my apologies!

If it's not possible, I'm not sure of a great way to do it. One option would be `Memory(..., return_hit=False)` where, if `True`, each call returns `out, hit = memory.cache(func)(*args, **kwargs)` rather than just returning the `out` from the `func`.

**Comment by tomMoral** [comment]
There is a way to check if a call is in cache with [`check_call_in_cache`](https://joblib.readthedocs.io/en/latest/memory.html#joblib.memory.MemorizedFunc.check_call_in_cache). The workflow is more like:

```python
func_cache = memory.cache(func)
hit = func_cache.check_call_in_cache(*args, **kwargs) 
```

It is true that it could be better documented, feel free to open a PR :)

**Comment by larsoner** [comment]
But there is no way to do it as part of the call directly, so in the case of a miss, you end up computing the hashes twice, right? I guess this is typically negligible at least, but just want to check my understanding.

I should be able to make a quick doc PR

**Comment by tomMoral** [comment]
Yes, that's true it requires computing the hash twice. 

If there is use-cases where avoiding this is necessary, I would rather add a function `call_with_is_cached` that returns the both the result and `is_in_cache` as I am not in favor of having an API where changing a parameter of `Memory` would change the signature of the function.
