### ISSUE TITLE
ValueError: unsupported pickle protocol: 5 on python 3.7.13 and joblib 1.2.0

### ISSUE THREAD

**Issue by parap1uie-s** [joblib/joblib#1346]
I'm trying to apply joblib on aarch64 platform with python 3.7.13, joblib 1.2.0, but received errors:

```
--------------------------------------------------------------------------------
LokyProcess-5 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/paddle_npu/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
    prep_data = pickle.load(from_parent)
ValueError: unsupported pickle protocol: 5


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-10 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/paddle_npu/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
    prep_data = pickle.load(from_parent)
ValueError: unsupported pickle protocol: 5
```

The relative code:
```python3
from joblib import Parallel, delayed
def inter_resize_func(slice_id):
    return skimage.transform.resize(data[tuple(I)], new_shape_2d, order, **kwargs)

reshaped_data = Parallel(n_jobs=16)(
                    delayed(inter_resize_func)(slice_id) for slice_id in range(shape[axis]))
```

**Comment by parap1uie-s** [comment]
Any suggestions? Thanks in advance.

**Comment by Sonyoyo** [comment]
I have the same issue.

**Comment by Sonyoyo** [comment]
Using python 3.8 and joblib 1.2.0 with the same python code works fine.

**Comment by parap1uie-s** [comment]
> Using python 3.8 and joblib 1.2.0 with the same python code works fine.

yep, python 3.8 works fine.

**Comment by jjerphan** [comment]
From [the documentation of pickle](https://docs.python.org/3/library/pickle.html#data-stream-format):

> Protocol version 5 was added in Python 3.8. It adds support for out-of-band data and speedup for in-band data. Refer to [PEP 574](https://peps.python.org/pep-0574/) for information about improvements brought by protocol 5.

If you still plan to use Python 3.7 (which is no longer supported), you might want to try using [`pickle5`](https://pypi.org/project/pickle5/), which provide the fifth version of the pickle protocol.
