### ISSUE TITLE
When using the Catboost model to call sklearn's permanence importance to calculate the contribution rate, the joblib library prompts ValueError: assignment destination is read-only

### ISSUE THREAD

**Issue by qq492947833** [joblib/joblib#1355]
As an example, when I use the Catboost model to call sklearn's permanence importance to calculate the contribution rate, the joblib library prompts ValueError: assignment destination is read-only. This cannot be solved by modifying max nbytes, even if I increase it to 99999M.
This problem only occurs when I use catboost, not when I use other GBDT models.I want to know why.
If you can answer, I would be very grateful!

**Comment by arturohu** [comment]
We had some problems with the new version of scipy dependency. Maybe it could help you. 

We forced to install the previous version scipy==1.9.1 instead of last scipy==1.9.2 installed by default as scikit-learn dependecy.

**Comment by qq492947833** [comment]
> We had some problems with the new version of scipy dependency. Maybe it could help you.
> 
> We forced to install the previous version scipy==1.9.1 instead of last scipy==1.9.2 installed by default as scikit-learn dependecy.

Thank you very much,it is worked.
