### ISSUE TITLE
pickling error

### ISSUE THREAD

**Issue by rolfverberg** [joblib/joblib#1360]
I am fitting with lmfit in parallel using joblib. All runs fine from command line unix python script, but it fails in Jupyter lab. I browsed around a lot and tried all that I found as suggestions, but all fail.

Do you have any suggestions?

Source files and notebook are attached
[pickle_error.zip](https://github.com/joblib/joblib/files/9981417/pickle_error.zip)

Error message is:
.
.
.
File /nfs/chess/user/rv43/python_parallel/parallelising-python/fit.py:1300, in FitMap.fit(self, **kwargs)
   1298 elif True:
   1299     with Parallel(n_jobs=num_proc) as parallel:
-> 1300         parallel(delayed(self._fit_parallel3)(pars, i, j, **kwargs)
   1301                 for i, j in ij)
   1302 else:
   1303     num = min(len(ij), 40)

File /nfs/chess/user/rv43/miniconda3/envs/parallel_sandbox/lib/python3.9/site-packages/joblib/parallel.py:1098, in Parallel.__call__(self, iterable)
   1095     self._iterating = False
   1097 with self._backend.retrieval_context():
-> 1098     self.retrieve()
   1099 # Make sure that we get a last message telling us we are done
   1100 elapsed_time = time.time() - self._start_time

File /nfs/chess/user/rv43/miniconda3/envs/parallel_sandbox/lib/python3.9/site-packages/joblib/parallel.py:975, in Parallel.retrieve(self)
    973 try:
    974     if getattr(self._backend, 'supports_timeout', False):
--> 975         self._output.extend(job.get(timeout=self.timeout))
    976     else:
    977         self._output.extend(job.get())

File /nfs/chess/user/rv43/miniconda3/envs/parallel_sandbox/lib/python3.9/site-packages/joblib/_parallel_backends.py:567, in LokyBackend.wrap_future_result(future, timeout)
    564 """Wrapper for Future.result to implement the same behaviour as
    565 AsyncResults.get from multiprocessing."""
    566 try:
--> 567     return future.result(timeout=timeout)
    568 except CfTimeoutError as e:
    569     raise TimeoutError from e

File /nfs/chess/user/rv43/miniconda3/envs/parallel_sandbox/lib/python3.9/concurrent/futures/_base.py:446, in Future.result(self, timeout)
    444     raise CancelledError()
    445 elif self._state == FINISHED:
--> 446     return self.__get_result()
    447 else:
    448     raise TimeoutError()

File /nfs/chess/user/rv43/miniconda3/envs/parallel_sandbox/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

PicklingError: Could not pickle the task to send it to the workers.

**Comment by rolfverberg** [comment]
OK, found out that the issue goes away if I use lmfit without an expression model. So it seems like adding an expression model creates it. This may not be something that joblib can answer or address.

**Comment by jjerphan** [comment]
Hi @rolfverberg, thank you for reporting this bug.

Next time, could you [craft a minimal reproducing example](https://scikit-learn.org/stable/developers/minimal_reproducer.html)?

**Comment by jjerphan** [comment]
Hi @rolfverberg, thank you for reporting this bug.

Note that [crafting a minimal reproducing example](https://scikit-learn.org/stable/developers/minimal_reproducer.html) would better help maintainers identify and resolve the issue.

**Comment by rolfverberg** [comment]
Sorry, have been out of the loop for a bit. I haven't had time to revisit this issue, so I will close it for now. If I reopen or have it resolved I will let you now or create a reporpducing example. Thanks!
