### ISSUE TITLE
THIS IS A JOBLIB ISSUE. If you can, kindly provide the joblib's team with an  example so that they can fix the problem.

### ISSUE THREAD

**Issue by isaacgerg** [joblib/joblib#1370]
Hi,  I am just passing this error along to the joblib devs.

I am passing large numpy arrays to a memoized function.  My guess is it taking a long time to hash those arrays. Maybe there is a staged way to hash them so that you can make the comparison faster?

**Comment by isaacgerg** [comment]
Here you go...

```
import numpy as np
import joblib


memory = joblib.Memory('.', verbose=0)

@memory.cache()
def sum_fct(x, y, z):
    print('executing')
    return x.sum() + y.sum() + z.sum()

N = 10000

m = np.zeros((N, N))
n = np.zeros((N, N))
p = np.zeros((N, N))

for k in range(10):
    print(sum_fct(m, n, p))

print('done')
```

yields:

```
executing
C:\Users\idg101\Desktop\rise\joblib_test.py:19: UserWarning: Persisting input arguments took 2.59s to run.
If this happens often in your code, it can cause performance problems 
(results will be correct in all cases). 
The reason for this is probably some large input arguments for a wrapped
 function (e.g. large strings).
THIS IS A JOBLIB ISSUE. If you can, kindly provide the joblib's team with an
 example so that they can fix the problem.
  print(sum_fct(m, n, p))
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
done
```

**Comment by jjerphan** [comment]
https://github.com/joblib/joblib/pull/1390 should clarify the warning messages.

Regarding a faster hashing, the best possible alternative would be to use pickle's protocol 5 (described by [PEP 574](https://peps.python.org/pep-0574/)) with a custom File Object (i.e. a class implementing the `write` and `close` methods) to avoid any memory copy. Such a File Object has to subclass the `Pickler` class.

**Comment by isaacgerg** [comment]
Great!  Are numpy arrays hashed in any special way?  I could imagine a stepped approach like, first check if arrays are same size, then check random elements, and if all those pass then do a full hash and compare.

You may close this ticket.  Again, just passing along the message to be a good user of open source.  Thank you for your efforts!

**Comment by jjerphan** [comment]
Thank you for the kind words, @isaacgerg. :handshake:

**Comment by ogrisel** [comment]
> Regarding a faster hashing, the best possible alternative would be to use pickle's protocol 5 (described by [PEP 574](https://peps.python.org/pep-0574/)) with a custom File Object (i.e. a class implementing the write and close methods) to avoid any memory copy. Such a File Object has to subclass the Pickler class.

That would indeed simplify the code a lot and make it more maintainable and extendable but in itself it would not significantly change the speed of hashing if we continue using md5 as the underlying hashing function.

> Great! Are numpy arrays hashed in any special way? I could imagine a stepped approach like, first check if arrays are same size, then check random elements, and if all those pass then do a full hash and compare.

That's interesting but I am afraid this would speed up only the case where the arrays have changed, when the cached expensive function needs to be recomputed anyway, so the time it takes to hash the inputs does not really matter.

I think we need to make the hashing function pluggable and allow to pass the name of hash function as an argument to `joblib.Memory` and `joblib.hash`. The user would then be able to choose between a slow but cryptographic hash function or faster hashing functions such as xxhash.

Note that md5 was supposed to be cryptographic originally but was proven to be weak and therefore unsecure, so it provides neither robustness to cache poisoning attacks nor speed.

Note sure about what should be the default though.
