### ISSUE TITLE
Incorrectly formed version '0.3.2d' on PyPi

### ISSUE THREAD

**Issue by mirekphd** [joblib/joblib#1372]
A python versions monitoring script used in our CI/CD (Jenkins) indicates that one of the `joblib` versions available from PyPI is incorrect (not conformant to semantic versioning standards):
```
joblib :
- version installed:  1.2.0
Invalid version: '0.3.2d'
- latest  available:  1.2.0
- package upgradeable:  False 
```

**Comment by jjerphan** [comment]
Hi @mirekphd, the first version of joblib were released before semantic versioning standards were one of the preferred versioning options.

**Comment by ogrisel** [comment]
Yes I don't think we want to delete old joblib release just because their version numbers where non-conforming with modern standards.
