### ISSUE TITLE
Jupyter + atexit + joblib

### ISSUE THREAD

**Issue by WesleyTheGeolien** [joblib/joblib#1377]
Hey thanks for the great work.

# Issue

I am running into some issues with declaring `atexit.register` inside my notebook (this is a minimal working example of code from a module I am writing) and using joblib. Running this same code with `n_jobs=1` works fine inside Jupyter and running this as a script `python test.py` works with n_jobs > 1. So I there is some interaction between Jupyter atexit and joblib. (Running with commenting out the joblib parallel call also works.

# Minimal example

Here is the test script:
```python
import atexit
from joblib import Parallel, delayed

def func(val):
    atexit.register(exit_func, val)
    print(val, flush=True)

def exit_func(val):
    print("Exiting: ",val,  flush=True)
    
def main(n_jobs=2):
    func("Outside")
    print()
    Parallel(n_jobs=n_jobs, backend="loky")(delayed(func)("Inside: " + str(i)) for i in range(3));
    print()
    func("Outside 2")
    
main(1)
```

this prints:
```
Outside

Inside: 0
Inside: 1
Inside: 2

Outside 2
```

Then If I stop the kernel in the same cell output I get this as well:
```
Exiting:  Outside 2
Exiting:  Inside: 2
Exiting:  Inside: 1
Exiting:  Inside: 0
Exiting:  Outside
```

Which makes sense, at least I think.

Now if I change `main(1)` to `main(2)` the atexit values are as follows:
```
Exiting:  Inside: 2
Exiting:  Inside: 1
Exiting:  Inside: 0
```

Also I am not consistently getting the atexit values printed out (or run, if I try creating a file) I am still trying to debug if this is related to joblib or ipython.

Sorry if this is not a joblib issue but an ipython issue, I can raise and issue there if needed.

# Environment

(I can provide more if needed)

- OS: Linux (Pop!_OS 22.04 LTS, Ubuntu derived)

- python: 3.9.13
- joblib: 1.2.0
- ipython: 8.6.0
- jupyter: 1.0.0
- jupyterlab: 3.5.0

**Comment by WesleyTheGeolien** [comment]
Some further debugging on this, the behaviour seems inconsitent across OS's and python versions. However I think it is due to the Jupyter stop condition and cleanup taking too long. In particular this line: https://github.com/jupyter/jupyter_client/blob/eded331c9f292a1838602414b6c05928917d13e8/jupyter_client/manager.py#L435 where the default `waittime` is 5.0 so a timeout of 2.5.

Running this code (taken from Stackoverflow):
```python
import atexit
class Capture:
    def __init__(self):
        self.captured = []
    def __eq__(self, other):
        self.captured.append(other)
        return False

c = Capture()
atexit.unregister(c)
s1 = set(c.captured)
display(c.captured)
```

I was able to look at the different functions registered see below:
```
[<function logging.shutdown(handlerList=[<weakref at 0x7f12ad6f6cc0; to 'StreamHandler' at 0x7f12ad705c40>, <weakref at 0x7f12ad6baa90; to 'StreamHandler' at 0x7f12afff6ac0>, <weakref at 0x7f11b2c84450; to 'NullHandler' at 0x7f11b2c25940>, <weakref at 0x7f11b297b720; to 'StreamHandler' at 0x7f11b2b25fa0>, <weakref at 0x7f11b29f3b30; to 'NullHandler' at 0x7f11b2cea820>, <weakref at 0x7f11b27f0d10; to 'NullHandler' at 0x7f11c13077c0>, <weakref at 0x7f11a9ac5cc0; to 'StreamHandler' at 0x7f11a9ac7880>, <weakref at 0x7f11a9ab72c0; to 'StreamHandler' at 0x7f11a9af66a0>])>,
 <function zmq.sugar.context._notice_atexit() -> None>,
 <function tornado.platform.asyncio._atexit_callback() -> None>,
 <function jupyter_client.channels.HBChannel._notice_exit() -> None>,
 <function TextIOWrapper.close()>,
 <function debugpy.common.log._close_files()>,
 <bound method IPKernelApp.close of <ipykernel.kernelapp.IPKernelApp object at 0x7f12b11aa0a0>>,
 <bound method IOPubThread.stop of <ipykernel.iostream.IOPubThread object at 0x7f12ad6a67c0>>,
 <bound method HistorySavingThread.stop of <HistorySavingThread(IPythonHistorySavingThread, started 139717702055488)>>,
 <bound method ScriptMagics.kill_bg_processes of <IPython.core.magics.script.ScriptMagics object at 0x7f12ac66f580>>,
 <bound method InteractiveShell.atexit_operations of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f12ac651400>>,
 <function multiprocessing.util._exit_function(info=<function info at 0x7f119e1c23a0>, debug=<function debug at 0x7f119e1c2310>, _run_finalizers=<function _run_finalizers at 0x7f119e1c29d0>, active_children=<function active_children at 0x7f11c133e040>, current_process=<function current_process at 0x7f11c13a4f70>)>,
 <function joblib._memmapping_reducer.TemporaryResourcesManager.register_folder_finalizer.<locals>._cleanup()>]
```

Running through these in reverse order as atexit is a LIFO this function: ` <function multiprocessing.util._exit_function(info=<function info at 0x7f119e1c23a0>, debug=<function debug at 0x7f119e1c2310>, _run_finalizers=<function _run_finalizers at 0x7f119e1c29d0>, active_children=<function active_children at 0x7f11c133e040>, current_process=<function current_process at 0x7f11c13a4f70>)>,` took ~4 minutes to exit (I wonder if it is the default Pool timeout for child threads?)

Registering this functions to cleanup AFTER calling Parallel, seemed to work but I do not have enough knowledge to know if it sustainable:
```python
def _kill_child_processes():
    from joblib.externals.loky import get_reusable_executor
    get_reusable_executor().shutdown(wait=True)
```

**Comment by ogrisel** [comment]
loky workers stay alive for 30 seconds or so when idling. Feel free to kill the loky processes if you wish, the next call to `get_reusable_executor()` will re-create new processes if needed.

**Comment by WesleyTheGeolien** [comment]
Thanks @ogrisel in retrospective I think this is an Ipyhton issue and not job lib will close
