### ISSUE TITLE
Stop using `flake8 --diff` and unpin `flake8<6`

### ISSUE THREAD

**Issue by fcharras** [joblib/joblib#1380]
After release `6.0.0` `flake8` no longer expose the `--diff` parameter (see https://flake8.pycqa.org/en/latest/release-notes/6.0.0.html#backwards-incompatible-changes )

We pin it to `<6` in https://github.com/joblib/joblib/pull/1379 as a hotfix.

The `--diff` approach had risks of actually not detecting some `flake8` issues and it's unfixable that's why it was removed (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3961 ).

**Comment by jjerphan** [comment]
Alternatively, one might want to consider [`ruff`](https://github.com/charliermarsh/ruff), a `flake8` alternative which has a `--diff` flag.

**Comment by ogrisel** [comment]
Closing. We can always explore using ruff in a follow-up PR, probably, after we have blacked the code-base, so that the "8" part of flake8 is no longer relevant.
