### ISSUE TITLE
[Question]: Code Update

### ISSUE THREAD

**Issue by celestinoxp** [joblib/joblib#1381]
I would like to know how updating the code on github works, as I currently see 57 pull-requests, many without errors and approved, but the "master" code has not been updated since November 25, 2022.

If I want to create a release, I will only have access to the code of November 25, 2022...

Question: When is the code changed and is it changed progressively or all at once?

**Comment by ogrisel** [comment]
It depends on how much time the maintainers of the project can allocate to it. It's true that this project was irregularly maintained over the past few years. We are currently investing a bit of effort to review pull requests and will probably cut a new release in the coming weeks (after loky).
