### ISSUE TITLE
Question about joblib functionality

### ISSUE THREAD

**Issue by ogennaesimai** [joblib/joblib#1402]
Thank you for your work on the library!

My apologies if there is a better way or place to ask this besides here.

I am wanting to run code on processes. The code that would go in delayed() returns non-integer types, for example, strings.

Please does joblib have functionality to be used on additional types as well as integers or other numerical data?

From https://joblib.readthedocs.io/en/latest/parallel.html, two examples are 

```
from math import sqrt
>>> from joblib import Parallel, delayed
>>> Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(10))
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
```

```
from math import sqrt
>>> from joblib import Parallel, delayed
>>> def producer():
...     for i in range(6):
...         print('Produced %s' % i)
...         yield i
>>> out = Parallel(n_jobs=2, verbose=100, pre_dispatch='1.5*n_jobs')(
...                delayed(sqrt)(i) for i in producer()) 
Produced 0
Produced 1
Produced 2
[Parallel(n_jobs=2)]: Done 1 jobs     | elapsed:  0.0s
Produced 3
[Parallel(n_jobs=2)]: Done 2 jobs     | elapsed:  0.0s
Produced 4
[Parallel(n_jobs=2)]: Done 3 jobs     | elapsed:  0.0s
Produced 5
[Parallel(n_jobs=2)]: Done 4 jobs     | elapsed:  0.0s
[Parallel(n_jobs=2)]: Done 6 out of 6 | elapsed:  0.0s remaining: 0.0s
[Parallel(n_jobs=2)]: Done 6 out of 6 | elapsed:  0.0s finished
```

I looked online for other uses of joblib that might be similar to what I am trying to do but other than this site, the other locations referred back to examples such as those in the docs above.

The code:

```
def function_name(set of strings):
    variable declaration
    for perm in itertools.permutations(set of strings):
        variable declaration
        for i in range():
            do something with perm and i
```

I am new and would appreciate any help in easy-to-understand English. Thanks in advance!

**Comment by tomMoral** [comment]
hello,

`joblib` can handle (almost) any python object returned by the `delayed` function. So you are not constrained to return integers, and returning strings will work.

I think it would be nice to precise this in the doc.

**Comment by ogennaesimai** [comment]
Please would you give an example of using Parallel(n_jobs=<number of jobs>)(delayed() with strings?

**Comment by tomMoral** [comment]
For instance:
```python
from joblib import Parallel, delayed

def test(i):
    return f"Task: {i}"

Parallel(n_jobs=2)(delayed(test)(str(i)) for i in range(10)) 
```

**Comment by ogennaesimai** [comment]
Thank you!
