### ISSUE TITLE
Suppressing the output functions. 

### ISSUE THREAD

**Issue by VEZcoding** [joblib/joblib#1410]
I want to suppress outputs in the function that contains parallelized function. 
```
from joblib import Parallel, delayed
import os
import contextlib
def start(): 
    print('HELLO')
    def para(i): 
        print('hello')
        
    a = Parallel(n_jobs = 2)(delayed(para)(i) for i in [0,1,2])

with contextlib.redirect_stdout(open(os.devnull, "w")):            
    start()    
    
Output: 
    'hello'
    'hello'
    'hello'
```

Which I don't want, I don't want any outputs of this function. If I try to do
```
with contextlib.redirect_stdout(None)):            
    start()  
```  

I get an error: 
```
  File "..../joblib/externals/loky/backend/popen_loky_posix.py", line 49, in __init__
    sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'
```

Any suggestions on how to achieve this? I tried adding flush to the __init__.py but its not working.

**Comment by VEZcoding** [comment]
Answered: 
https://stackoverflow.com/questions/75855883/ways-of-supress-prints-from-joblib-parallelization/75864228#75864228

**Comment by ogrisel** [comment]
Closing since the SO answer seems to solver the problem.

Alternatively, you could have wrapped the `para` function with another function in charge of calling `redirect_stdout` each time in the parallel workers.
