### ISSUE TITLE
https://joblib.readthedocs.io/ doesn't provide documentation for latest release

### ISSUE THREAD

**Issue by eenblam** [joblib/joblib#1438]
Hi there! I'm new to joblib, but finding it pretty cool so far! I did run into a bit of a hurdle with the docs, though.

Currently, https://joblib.readthedocs.io/ provides exactly one version of the docs, "latest". This seems to track `master`, and not the latest version published to PyPI. So, for example, visiting https://joblib.readthedocs.io/en/latest/parallel.html and trying to follow the examples in the first section breaks, since the `return_generator` parameter isn't actually available via PyPI yet. However, this isn't immediately clear when reading.

The user onboarding experience could be smoother if the docs were updated a bit:

1. compiling for multiple releases, so that the readthedocs version selector allows selection between different version
2. continuing to set `latest` as default, but have it instead point to the most recent release
3. providing `master` branch docs as a separate option

Just some small feedback. Anyway, thanks for making a cool thing and putting it out in the world!

**Comment by tomMoral** [comment]
Actually, it seems that it is possible to do this easily with readthedocs (see [doc on versionning](https://docs.readthedocs.io/en/latest/versions.html#versioned-documentation)).

I am not able to access the interface of readthedocs as I am not listed as a maintainer on the platform.
@ogrisel , @lesteve , @GaelVaroquaux you seem to be the only ones listed. Could you take a look to add me as a maintainer (or for the versionning ;) ).

**Comment by lesteve** [comment]
Done!

**Comment by tomMoral** [comment]
Ok, we now have by default the latest release as the landing page! It was simple configuration on readthedocs 😁

closing this but feel free to reopen if I missed something!

**Comment by ogrisel** [comment]
Thanks @tomMoral!
