### ISSUE TITLE
Wrong default values for `n_jobs`

### ISSUE THREAD

**Issue by ZvikaZ** [joblib/joblib#1448]
Hi.
I've benchmarked a simple code that calls 10 times a function that waits for 2 seconds (see code below). It gets good results if I manually set `n_jobs=10` (or more). However, if I don't explicitly set it, it takes roughly 20 seconds (i.e., like serial). Setting it to `None` gives same results. 

Setting it to `-1` is better: ~6 seconds. But still worse than manually setting it to 10.

That occurs either with `prefer=` `threads` or `processes`.

My code:
```Python
from joblib import Parallel, delayed
import multiprocessing
import time


def slowly(x):
    time.sleep(2)  # 2 seconds
    return x * 10


def work():
    for p in ['threads', 'processes']:
        for j in ['Default', None, -1, 10, 20]:
            start = time.time()
            if j == 'Default':
                res = Parallel(prefer=p)(delayed(slowly)(x) for x in range(10))
            else:
                res = Parallel(n_jobs=j, prefer=p)(delayed(slowly)(x) for x in range(10))
            delta = time.time() - start
            print(j, p, delta)


work()
print('Num of cpus:', multiprocessing.cpu_count())

```

And results of running:

	Default threads 20.02308940887451
	None threads 20.020164489746094
	-1 threads 6.019700765609741
	10 threads 2.007143020629883
	20 threads 2.009794235229492
	Default processes 20.020959615707397
	None processes 20.02199649810791
	-1 processes 8.453832387924194
	10 processes 4.232425689697266
	20 processes 4.099262475967407
	Num of cpus: 56

If it's relevant:

    $ uname -a
    Linux cs-cpu-08 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fcharras** [comment]
Wasn't this issue related to https://github.com/joblib/joblib/issues/1473 ? if so it has been adressed in the main branch already and will be fixed in an upcoming patch release.
