### ISSUE TITLE
Can Joblib benefit from PEP 703 (making the GIL optional)?

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [joblib/joblib#1459]
Hi!

I'm Gabriel de Marmiesse and I'm helping Sam Gross to find out if maintainers of selected Python packages would benefit from PEP703.

If you don't know what is PEP 703, it's about making the global interpreter lock (GIL) optional.
Long story short, there would be a ~10% performance impact on single threaded programs, but would allow multithreaded programms to take full advantage of multiple cores.
[You can play with it here](https://github.com/colesbury/nogil).

If you have the time, we would like to know is if the maintainers of Joblib would benefit from PEP 703 or not. There are multiple situation Joblib could be in.

1) Joblib already uses threads and PEP 703 will likely make some features faster by allowing parallelization of cpu computation without any change.
2) Joblib doesn't use threads, but PEP 703 would allow you to rewrite some features with multithreading, thus making it faster.
3) Joblib uses multithreading with a low-level language (rust, C, C++...) or multiprocessing and using PEP 703 would allow a rewrite and lower the maintenance burden.
4) There is no computation that can be parallelized.
5) Joblib wouldn't use multithreading, but it's very likely that users will call this package functions and classes from multiple threads because the workload can often be parralelized.

The Python language could never use multiple cores with multithreading, so it's hard to imagine what the future of the language would look like if we were to enable it. Feel free to tell us if you see new potential use cases with this PEP. Thanks for your time!

If you want to know more about PEP 703:
* [The PEP](https://peps.python.org/pep-0703/)
* [Python 3.9 implementation with install instructions](https://github.com/colesbury/nogil)
* [Python 3.12 implementation](https://github.com/colesbury/nogil-3.12)
* [Discussion about PEP 703](https://discuss.python.org/t/pep-703-making-the-global-interpreter-lock-optional-3-12-updates/26503/141)
* [Discussion about the multicore future of Python](https://discuss.python.org/t/a-fast-free-threading-python/27903)

**Comment by ogrisel** [comment]
Short answer is yes, as maintainers of joblib we would love the PEP to be adopted because it would allow us to not have to deal with complexity and various kinds of overhead when dealing with process-based parallelism and we could use threading as an efficient, low maintenance default backend for joblib.

Many of us are busy this week but we plan to give a more detailed reply later.

**Comment by lesteve** [comment]
I guess maybe a more detailed reply is what is already quoted in PEP 703: https://peps.python.org/pep-0703/#the-gil-affects-python-library-usability

> Over the years, scikit-learn developers have maintained ancillary libraries such as joblib and loky to try workaround some the limitations of multiprocessing: extra memory usage partially mitigated via semi-automated memory mapping of large data buffers, slow workers startup by transparently reusing a pool of long running workers, fork-safety problems of third-party native runtime libraries such as GNU OpenMP by never using the fork-only start-method, ability to perform parallel calls of interactively defined functions in notebooks and REPLs in cross-platform manner via cloudpickle. Despite our efforts, this multiprocessing-based solution is still brittle, complex to maintain and confusing to datascientists with limited understanding of system-level constraints. Furthermore, there are still irreducible limitations such as the overhead caused by the pickle-based serialization/deserialization steps required for inter-process communication. A lot of this extra work and complexity would not be  needed anymore if we could use threads without contention on multicore hosts (sometimes with 64 physical cores or more) to run datascience pipelines that alternate between Python-level operations and calls to native libraries.

@gabrieldemarmiesse it seems like this is in the context of trying to list projects that may benefit from nogil https://github.com/colesbury/nogil-3.12/issues/6. Let us know if you need something more specific and we would be very motivated to help.

You probably know this, but note that joblib is used as the parallelism engine in a lot of other Scientific Python packages (scikit-learn, scikit-image, mne-python, etc ...)

**Comment by gabrieldemarmiesse** [comment]
Thanks for the precision. Yes indeed, I've already used joblib in the past and it's great :) , sadly it seems discussion about pep703 is over, all discussions on python.org have been locked, I don't think we will add much more to the conversation. We just need to wait and see what the steering council decides

**Comment by lesteve** [comment]
> We just need to wait and see what the steering council decides

Sounds like a plan :crossed_fingers:
