### ISSUE TITLE
Failed to import joblib due to _MAX_WINDOWS_WORKERS not defined

### ISSUE THREAD

**Issue by orgonth** [joblib/joblib#1471]
Happens with:
- Python 3.7.3 and older
- joblib 1.3.0 (introduced in that PR: https://github.com/joblib/joblib/pull/1422)

Root cause: the following line fails because `_MAX_WINDOWS_WORKERS` variable was introduced in python 3.7.4.
```py
from concurrent.futures.process import _MAX_WINDOWS_WORKERS
```

Proposed mitigation:
```py
# Apparently, on older Python versions, loky cannot work 61 workers on Windows
# but instead 60: ¯\_(ツ)_/¯
if (3, 7, 4) <= sys.version_info < (3, 10):
    from concurrent.futures.process import _MAX_WINDOWS_WORKERS
    _MAX_WINDOWS_WORKERS = _MAX_WINDOWS_WORKERS - 1
```

**Comment by tomMoral** [comment]
Thanks for the report.
This issue has already been reported in #1469, closing in favor of the other issue.
