### ISSUE TITLE
[Question] does `joblib` support custom task scheduling?

### ISSUE THREAD

**Issue by UniverseFly** [joblib/joblib#1512]
As an example, I have tasks with a customized dependency as follows:

```
a1 -> a2 -> a3
b1 -> b2
c1 -> c2 -> c3
...
```

that is, $a_n$ should be executed after $a_{n-1}$. Assuming all the nodes are associated with the same function `f`, I want to run all of them in parallel (with a maximum number of $m$ workers), but it should avoid dependent tasks running together. Is it possible in `joblib`?

**Comment by ogrisel** [comment]
No, managing task dependencies is not a planned feature for joblib. You might want to have a look at dask, ray or celery for this kind of workloads.
