### ISSUE TITLE
Issue with 'return_as' Parameter in Parallel Processing

### ISSUE THREAD

**Issue by omatheuspimenta** [joblib/joblib#1513]
Hello,

I hope you are well.

I've encountered an issue while using the 'return_as' parameter set to 'Generator' for loading files. It seems that not all files are loaded, and the execution terminates prematurely. However, when I use the 'return_as' parameter set to 'list', the return is complete.

Here's an example of the function I'm currently working on:

```python
from Bio import SeqIO
from joblib import Parallel, delayed

with open(sequence_path, encoding='utf-8') as sequences:
    seq_records = Parallel(n_jobs=-2, return_as='generator')(
        delayed(run_buffer_sequences)(seq)
        for seq in SeqIO.parse(sequences, 'fasta')
    )

return seq_records
```

I'd appreciate any insights or assistance in resolving this issue. Thank you!

**Comment by tomMoral** [comment]
Hello,

`return_as="generator"` returns immediately a generator. This means that the results are processed in background. But if there is no operations to collect them and the interpreter shutdowns, there is no guarantees that the computations will have run before the shutdown.
To collect the results, or make sure you have processed all the data, you need to "consume" the generator.
The simpler would be to call `list(seq_records)`, which is equivalent to setting `return_as="list"`.

As this does not seem to be a bug, I am closing the issue but feel free to reopen if there is something I did not understood.
