### ISSUE TITLE
Keep cache on function code change

### ISSUE THREAD

**Issue by philippkeller** [joblib/joblib#1533]
Is there a way to keep the cache when I change the code of the function?
E.g. just a print() statement invalidates the cache.
In some situations I want to keep the cache even though the code changed.

**Comment by tomMoral** [comment]
no, there is no way to do this.

Not invalidating the cache when the code of the function change would make the cache too error prone and analyzing the code to inspect the exact change and detect when it does not change the output would be very hard.

**Comment by philippkeller** [comment]
ok, I guess I could code a wrapper around a function which I know will change the code frequently and then cache that wrapper function
