### ISSUE TITLE
Using CPU cores over an `ssh` connection in `joblib.Parallel`?

### ISSUE THREAD

**Issue by Schefflera-Arboricola** [joblib/joblib#1563]
Hi, If I have 8 CPU cores on my local machine and another 8 cores in a VM which I can access remotely through `ssh`, then is there a way I can set `n_jobs=16` in `joblib.Parallel` and utilize all of the 16 cores all at once to run processes in parallel? I couldn't find any docs related to this so I'm not sure if this is even possible in joblib. Any kind of guidance on how I can achieve this would be great!

Thank you :)

**Comment by tomMoral** [comment]
Hello,
To  use more than one computer, you need to use a distributed backend (either `dask` or `ray`).
You can specify the backend using [`parallel_config`](https://joblib.readthedocs.io/en/stable/generated/joblib.parallel_config.html).

For instance for `dask`, you would first create a [`SSHCluster`](https://docs.dask.org/en/latest/deploying-ssh.html) and them use it as the cluster in our [`dask` backend example](https://joblib.readthedocs.io/en/stable/auto_examples/parallel/distributed_backend_simple.html#sphx-glr-auto-examples-parallel-distributed-backend-simple-py), with something like:

```python
from joblib import Parallel, delayed
from joblib import parallel_config
from dask.distributed import Client, SSHCluster

cluster = SSHCluster(["localhost", "remotehost"])

client = Client(cluster)
with parallel_config(backend="dask"):
    Parallel()(
       delayed(long_running_function)(i) for i in range(10)
    )
```
