### ISSUE TITLE
Add fips compliancy to hashing

### ISSUE THREAD

**Issue by sohumh** [joblib/joblib#1603]
`md5` is not a fips compliant hash function, and `sha1` will be [deprecated soon](https://www.wolfssl.com/fips-140-3-and-sha-1-retirement/). These are the only [two options](https://github.com/joblib/joblib/blob/f70939cd06416676be6e2c038dbb93bb7c2e2556/joblib/hashing.py#L256) for hash functions, when executing `joblib.hash`. Would it be possible to use the `usedforsecurity=false` option, see here for an explanation of it in the [documentation](https://docs.python.org/3/library/hashlib.html), in the Hasher `__init__` method [here](https://github.com/joblib/joblib/blob/f70939cd06416676be6e2c038dbb93bb7c2e2556/joblib/hashing.py#L59), or add fips compliant hash options here?

**Comment by GaelVaroquaux** [comment]
Completed by #1604 , Thanks!!

**Comment by sohumh** [comment]
@GaelVaroquaux do you know when a release will come out with this commit? It's a bit urgent for me, so would appreciate if a minor version bump can come soon!
