### ISSUE TITLE
Caching decorated functions leads to collisions

### ISSUE THREAD

**Issue by jasonkena** [joblib/joblib#1606]
What's the recommended way to cache decorated functions? Currently `get_func_name(func_a)` and `get_func_name(func_b)` both map to `(['__main__', 'dumb_decorator', '<locals>'], 'wrapper')`.

Is it possible to get `func_id` or `func_name` as an optional argument into `@mem.cache`?

```python
mem = Memory(location='cache', verbose=0)
mem.clear()

def dumb_decorator(func):
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper

@mem.cache
@dumb_decorator
def func_a():
    print('func_a')
    return 'a'

@mem.cache
@dumb_decorator
def func_b():
    print('func_b')
    return 'b'

func_a()
func_b() # -> does not print
```

**Comment by jasonkena** [comment]
Seems that the functions have to be decorated using `functools.wrap` so it inherits the original name.

```python
from functools import wrap
def dumb_decorator(func):
    @wrap(func)
    def wrapper(*args, **kwargs):
        ...
```

**Comment by thisiswhereitype** [comment]
I think this is realted to #1234 and requires unwrapping first until this pr gets merged
