### ISSUE TITLE
Can joblib.Parallel work in interactive environments (e.g., IPython Notebook) in Windows?

### ISSUE THREAD

**Issue by herrlich10** [joblib/joblib#174]
The doc example

```
from joblib import Parallel, delayed
Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(10))
```

worked with importable functions like `sqrt`, but not with those defined in interactive environments including IPython Notebook and IPython console:

```
def myfunc(x):
    return sqrt(x)
Parallel(n_jobs=2)(delayed(myfunc)(i ** 2) for i in range(10))
```

and raised the following error:

```
AttributeError: 'module' object has no attribute 'myfunc'
```

I'm running Python 2.7.7, Anaconda 2.0.1 (64-bit), Windows 7 SP1 (64-bit), IPython 2.1.0, joblib 0.8.4.
The same works smoothly in Linux.

**Comment by cqcn1991** [comment]
@wikiped @herrlich10 Is there any suggestion on it?
I have the same problem. The code runs well in Mac OS, but give the same error as you in Windows.
I feel that joblib is much easier to use than `IPython.parallel`, so I personally don't want to swich to that.

**Comment by GaelVaroquaux** [comment]
Do you have the problem under Python 3.4 or 3.5?

**Comment by cqcn1991** [comment]
@GaelVaroquaux 2.7. It can be solved by putting the method into module and then import them. But that really complicated the code sometimes....

Is 3.x free with this problem? Then I might consider shifting into 3.x

**Comment by GaelVaroquaux** [comment]
> Is 3.x free with this problem? Then I might consider shifting into 3.x

I don't know, I don't run Windows, and I can't reproduce the problem,
under Python 2, or Python 3. But the issue seems to suggest that it is.
So I was checking.

**Comment by cqcn1991** [comment]
The example @herrlich10 gives is very simple. Just open a new notebook and type it, and then you can get the same error (mine is Windows 7, Python 2.7)

**Comment by GaelVaroquaux** [comment]
I don't get an error under Python 2.7. But I run linux, not windows.
Hence my question: do you get this error under Python 3.5?

**Comment by cqcn1991** [comment]
Well... I don't have 3.5 so I'm afraid I don't know the correct answer.  I can only tell that this is also occuring at http://stackoverflow.com/questions/35452694/python-joblib-parallel-on-windows-not-working-even-if-name-main

And from @wikiped above, he said this also fails on python 3.

**Comment by lesteve** [comment]
AFAIR this is not expected to work under Windows neither with Python 2 nor Python 3.



> @GaelVaroquaux 2.7. It can be solved by putting the method into module and then import them. But that really complicated the code sometimes....

Putting the method in a module is the cleanest work-around. If that helps, you have a built-in editor in Jupyter these days. If you insist of having all your code in the same notebook you can use a combination of `%%file` to write into an external file and `imp.reload` to make sure you always use the latest version of the module.

For completeness, the long-term fix for this is to use dill to serialize the function inside Parallel. The idea would be to just take #240 and only use dill to serialise the function inside Parallel. This is something we really want to do so that we can switch to fork_server as the default joblib start method. We just haven't had the time to do it ... PR more than welcome !

**Comment by cqcn1991** [comment]
@lesteve can you be more specific on that? I just don't know about the `dill` stuff....

**Comment by DreamFlasher** [comment]
https://github.com/joblib/joblib/pull/240 got closed in favor of cloudpickle -- but it still doesn't work.

**Comment by ogrisel** [comment]
This problem is fixed in joblib master that now uses cloudpickle and loky by default.

**Comment by GF-Huang** [comment]
How about 2021? Can joblib for parallel computing works well in jupyterlab?

**Comment by ogrisel** [comment]
> How about 2021? Can joblib for parallel computing works well in jupyterlab?

If it does not work, please open a new issue with the details:

- the code of a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example),
- the full traceback of the error message you observe;
- the expected results and the observed results in case you do not get an error message.

**Comment by GF-Huang** [comment]
I just asked before using joblib whether the interactive environment was considered in the design of joblib, because I saw that the built-in python module could not overcome this problem, so I was curious.

**Comment by ogrisel** [comment]
Yes joblib should work in interactive jupyter sessions (for interactively defined Python functions with picklable arguments). If it's not the case, then it's probably a bug and then we need a minimal reproducible example to be able to fix it.

**Comment by ogrisel** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/89061/125270670-2d0df680-e30a-11eb-82b2-d8a0c9d04719.png">
