### ISSUE TITLE
Cannot load dumped dok_matrix objects

### ISSUE THREAD

**Issue by wejradford** [joblib/joblib#177]
I had problems trying to `load` a `dok_matrix`. Here's the minimal script to replicate:
```python
from __future__ import print_function
import sys
import joblib
import numpy as np
from scipy.sparse import bsr_matrix, coo_matrix, csc_matrix, csr_matrix, dia_matrix, dok_matrix, lil_matrix

for cls in (bsr_matrix, coo_matrix, csc_matrix, csr_matrix, dia_matrix, lil_matrix, dok_matrix):
    print('Dumping/loading {}'.format(cls))
    m = cls(np.random.normal(size=(100, 100)))
    joblib.dump(m, 'foo')
    joblib.load('foo')
```

It looks like `shape` isn't appropriately set as we load the matrix back out (`pickle`/`cPickle` seems to work though). I get the following:
```
Dumping/loading <class 'scipy.sparse.bsr.bsr_matrix'>
Dumping/loading <class 'scipy.sparse.coo.coo_matrix'>
Dumping/loading <class 'scipy.sparse.csc.csc_matrix'>
Dumping/loading <class 'scipy.sparse.csr.csr_matrix'>
Dumping/loading <class 'scipy.sparse.dia.dia_matrix'>
Dumping/loading <class 'scipy.sparse.lil.lil_matrix'>
Dumping/loading <class 'scipy.sparse.dok.dok_matrix'>
Traceback (most recent call last):
  File "/Users/wradford/Desktop/fail.py", line 11, in <module>
    joblib.load('foo')
  File "/Users/wradford/repos/joblib/joblib/numpy_pickle.py", line 425, in load
    obj = unpickler.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1206, in load_setitems
    dict[stack[i]] = stack[i + 1]
  File "/Users/wradford/repos/joblib/ve/lib/python2.7/site-packages/scipy/sparse/dok.py", line 236, in __setitem__
    0 <= i < self.shape[0] and 0 <= j < self.shape[1]):
  File "/Users/wradford/repos/joblib/ve/lib/python2.7/site-packages/scipy/sparse/base.py", line 499, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: shape not found
```

**Comment by aabadie** [comment]
Digging this up.

Looking at your stacktrace, I think the problem comes from pickle itself. 
Following http://stackoverflow.com/a/12181159, it seems the problem with matrix_dok comes from the pickle protocol version.

In joblib, the pickle protocol version used is 3 (Default) for python 2 and 4 for python 3 (highest). When calling `pickle.dump` directly with python 2, the pickle protocol is by default 'None' (0) and it's the only case where the matrix_dok can be reloaded. With any pickle protocol > 0, it fails, hence joblib will fail.

One potential solution is to explicitly set `protocol=0` when calling `joblib.dump`. For instance, the following code works:

```python
from __future__ import print_function
import sys
import joblib
import numpy as np
from scipy.sparse import bsr_matrix, coo_matrix, csc_matrix, csr_matrix, dia_matrix, dok_matrix, lil_matrix

for cls in (bsr_matrix, coo_matrix, csc_matrix, csr_matrix, dia_matrix, lil_matrix, dok_matrix):
    print('Dumping/loading {}'.format(cls))
    m = cls(np.random.normal(size=(100, 100)))
    joblib.dump(m, 'foo', protocol=0)
    joblib.load('foo')
```

**Comment by wejradford** [comment]
Thanks @aabadie! That makes sense. I wonder if some kind of warning to catch these cases might help users avoid this problem. Very much on the "nice to have" rather than "need to have pile" - I'll take advice on what to do with the issue from here...

**Comment by aabadie** [comment]
@wejradford, I just noticed that the issue with dok_matrix and pickle is already reported on scipy here: https://github.com/scipy/scipy/issues/1188

**Comment by wejradford** [comment]
Nice catch. Happy to close this and mark as a duplicate.

**Comment by aabadie** [comment]
@lesteve, I think this one can be closed.

**Comment by wejradford** [comment]
Thanks guys!
