### ISSUE TITLE
Limit processing time of function

### ISSUE THREAD

**Issue by thirdOctet** [joblib/joblib#185]
Is there a way in which joblib can utilise a timeout setting to terminate the process if it takes too long? I have looked at a couple of issues related to this problem where threading seems to hang, but in fact in my case there is a function which can take anywhere between 2ms and 15 mins (this is ok, but in the case where it extends beyond an hour we would like to handle this). 

An example would be to apply a transformation to an image, if the process does not complete after a specified time then terminate:

    Parallel(n_jobs=num_jobs)(delayed(applyTransformsToImage)(anImage) for anImage in imageSet)

If not then can you point me in the right direction. Thanks.

**Comment by GaelVaroquaux** [comment]
I think that such a functionality is something that can be implemented
fully outside of joblib. Specifically, you could have a decorator for the
function that you call that does the job.

I will close this issue for now, as we have other pressing problems that
only be solved by modifying the joblib codebase.
