### ISSUE TITLE
Programmatic interrupt?

### ISSUE THREAD

**Issue by wmayner** [joblib/joblib#186]
Would it be possible to send an interrupt to all parallel processes programmatically?

For instance, if we are performing some calculation across many processors but we know that if any of them returns 0, then the rest are unnecessary, it would be efficient to stop all the other ones from continuing the unnecessary computation as soon as one has returned 0.

**Comment by fcharras** [comment]
You could define the tasks such as it raises an error before returning the result, if the result match the interrupt condition. Raising an error in one task will trigger the early interrupt of the whole workflow. Enclose the parallel call in a try/except if you want to keep the main python process alive and do something else.
