### ISSUE TITLE
Compressed pickle compatibility impact on python 3 performance

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#194]
Just checked how #192 impacts performance and the difference is quite sizable for Python 3 (probably due to changing the pickle protocol)

Summary (time is in seconds):

Python 3.4        | joblib 0.8.4 | joblib master
-------------------|--------------|---------------
big array dumping |          4.6 |           6.8 
big array loading |          0.9 |           2.1 
big dict dumping  |         11.7 |          14.7 
big dict loading  |          4.8 |           6.2 

For completeness the same thing for python 2.7

| Python 2.7        | joblib 0.8.4 | joblib master |
|-------------------|--------------|---------------|
| big array dumping |          4.4 |           4.4 |
| big array loading |          0.7 |           0.8 |
| big dict dumping  |         10.2 |          10.2 |
| big dict loading  |          3.3 |           3.2 |

Benchmark script is [here](https://gist.github.com/lesteve/f85bdee54e582165b40f)

Output from the script:

```
Python: 2.7
================================================================================
('joblib file:', '/home/lesteve/anaconda/envs/py2/lib/python2.7/site-packages/sklearn/externals/joblib/__init__.pyc')
--------------------
big array
Dumping took 4.4 s
Loading took 0.7 s
--------------------
big dict
Dumping took 10.2 s
Loading took 3.3 s
================================================================================
('joblib file:', 'joblib/__init__.pyc')
--------------------
big array
Dumping took 4.4 s
Loading took 0.8 s
--------------------
big dict
Dumping took 10.2 s
Loading took 3.2 s
```

```
Python: 3.4
================================================================================
joblib file: /home/lesteve/anaconda/lib/python3.4/site-packages/sklearn/externals/joblib/__init__.py
--------------------
big array
Dumping took 4.6 s
Loading took 0.9 s
--------------------
big dict
Dumping took 11.7 s
Loading took 4.8 s
================================================================================
joblib file: /home/lesteve/dev/joblib/joblib/__init__.py
--------------------
big array
Dumping took 6.8 s
Loading took 2.1 s
--------------------
big dict
Dumping took 14.7 s
Loading took 6.2 s
```

**Comment by GaelVaroquaux** [comment]
Shit! I care more about speed than about compatibility across Python
version. Joblib has always been meant to be used as an internal data
storage.

My feeling would be to revert this. What do people think?

**Comment by lesteve** [comment]
> My feeling would be to revert this. What do people think?

Maybe I can try to investigate a little more where the performance difference is coming from first.

**Comment by lesteve** [comment]
Part of the story (only looked at the difference in dumping the big array so far): the issue seems to be that when the size of the array is less than the cache_size we just pickle the array via the standard pickler [here](https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle.py#L257). Between protocol 2 and 4 (for python 3.4), the size of the pickle can vary up to a factor 1.5 which explains the timing differences.
