### ISSUE TITLE
Pickling lambdas for `memory.cache`

### ISSUE THREAD

**Issue by simonzack** [joblib/joblib#225]
I'm using `memory.cache` to cache previous calls in sklearn, which usually involve tokenizers and preprocessors. Sometimes it's convenient to use lambda functions for these. `dill` extends pickle to serialize lambdas. Can switching to dill or letting the user choose some other pickle lib be considered?

**Comment by lesteve** [comment]
There was some work done towards using dill although I seem to remember it was to hash function arguments rather than for serialization purposes, see https://github.com/joblib/joblib/pull/219 for more details.

PR on this front are more than welcome!

**Comment by simonzack** [comment]
@lesteve Thanks! That looks like what I'm after. I'll try to work on it when I have time.
