### ISSUE TITLE
remaining time estimation could be better

### ISSUE THREAD

**Issue by nilsbecker** [joblib/joblib#234]
It seems that when estimating the remaining time, joblib uses the order in which jobs were started, not the currently remaining jobs. to show what i mean, here an example where individual jobs take different amounts of time to complete:
```
[Parallel(n_jobs=-2)]: Done   4 out of  12 | elapsed: 11.8min remaining: 23.6min
49996 samples
Pickling array (shape=(21,), dtype=float64).
Pickling array (shape=(21,), dtype=object).
Pickling array (shape=(21,), dtype=float64).
now running (0.5, 2.0, 'straight', 0.1, 1, 800, 200, inf)
dt = 0.05 subsample to dt = 0.05
max length of correlations 20
[Parallel(n_jobs=-2)]: Done   7 out of  12 | elapsed: 17.4min remaining: 12.4min
49993 samples
Pickling array (shape=(21,), dtype=float64).
Pickling array (shape=(21,), dtype=object).
Pickling array (shape=(21,), dtype=float64).
now running (1.0, 2.0, 'straight', 0.1, 1, 800, 200, inf)
[Parallel(n_jobs=-2)]: Done   8 out of  12 | elapsed: 17.6min remaining:  8.8min
dt = 0.05 subsample to dt = 0.05
max length of correlations 20
49930 samples
Pickling array (shape=(21,), dtype=float64).
Pickling array (shape=(21,), dtype=object).
Pickling array (shape=(21,), dtype=float64).
now running (0.5, 0.0, 'straight', 0.1, 1, 400, 200, inf)
[Parallel(n_jobs=-2)]: Done   6 out of  12 | elapsed: 21.8min remaining: 21.8min
```
so after job 8 is done apparently the system thinks there is only 4 to go although job 6 is still running. later, when job 6 finishes it seems not to take into account that 7 and 8 are already done.

instead, one could keep a running list of how many jobs remain and estimate from there?

**Comment by GaelVaroquaux** [comment]
> instead, one could keep a running list of how many jobs remain and estimate
> from there?

As the loop is expended as go, we do not know the total number of jobs,
or the remaining number of jobs. So I am afraid that it is not very
simple.

I am closing this issue, because I don't know how to solve it, but please
feel free to send a pull request showing us how to do it. Thanks!

**Comment by nilsbecker** [comment]
hmm, i had not thought about it but it seemed that since `Done   8 out of  12` is known at that point, the total number of jobs _is_ known? so why not count how many have already finished? i don't think i'm getting it?

**Comment by GaelVaroquaux** [comment]
> hmm, i had not thought about it but it seemed that since Done 8 out of
> 12 is known at that point, the total number of jobs is known? so why
> not count how many have already finished? i don't think i'm getting it?

Because results do not arrive in the order that they have been sent.

It may be the case that we can improve our code doing this. But I don't
see a trivial way of doing it, as the whole sent/recieve set of code is
somewhat intricated. Please do feel free to give it a try. It would be
awesome!

**Comment by lesteve** [comment]
To add to Gaël's answer I am not 100% sure, but I think that you get the "out of N" output when you pass a list to `Parallel.__call__` in which case it's easy to know how many jobs you have in total. In most cases I have seen you pass an iterator to the `Parallel.__call__` though.

**Comment by GaelVaroquaux** [comment]
> To add to Gaël's answer I am not 100% sure, but I think that you get the "out
> of N" output when you pass a list to Parallel.__call__ in which case it's easy
> to know how many jobs you have in total.

You're correct.

We could special-case the code to test if we have a '__len__' and use it,
but it would be probably for a very little amount of use cases.

**Comment by lesteve** [comment]
> it would be probably for a very little amount of use cases.

Also I seem to remember that the 'auto' dispatch to group tasks automatically depending on execution time only works for generators.

**Comment by GaelVaroquaux** [comment]
> Also I seem to remember that the 'auto' dispatch to group tasks automatically
> depending on execution time only works for generators.

Yes

**Comment by nilsbecker** [comment]
don't know if this is relevant but my call is of this form:
`dict(Parallel(-2, verbose=80)(delayed(hist_snapshots)(25,k,"f3") for k in cct))` where cct is a dictionary. that's a generator, not a list, right?

**Comment by lesteve** [comment]
Interesting, this is a generator indeed.

What's your joblib version, i.e. `python -c 'import joblib; print(joblib.__version__)` (amend the import if you are using joblib from sklearn.externals) ?

**Comment by nilsbecker** [comment]
0.8.4 , python 2.7.10 from current anaconda.

**Comment by GaelVaroquaux** [comment]
> that's a generator, not a list, right?

Yes, and that's why showing progress is hard.

**Comment by nilsbecker** [comment]
my point was that although it's only a generator, joblib knew that there are 12 jobs in total, so the information seems to be available somehow?

**Comment by lesteve** [comment]
It looks like when exactly you get the total number of tasks has something to do with the predispatch mechanism. In my toy case I was able to get the total number of tasks to show up at different times by playing on the pre_dispatch parameter (and the verbose a little bit to control the number of messages).

```
In [43]: joblib_084.Parallel(verbose=10, n_jobs=2, pre_dispatch='all')(joblib_084.delayed(my_square)(x) for x in range(10))
[Parallel(n_jobs=2)]: Done   1 out of  10 | elapsed:    1.2s remaining:   11.0s
[Parallel(n_jobs=2)]: Done   2 out of  10 | elapsed:    1.2s remaining:    4.9s
[Parallel(n_jobs=2)]: Done   4 out of  10 | elapsed:    1.5s remaining:    2.2s
[Parallel(n_jobs=2)]: Done   6 out of  10 | elapsed:    2.3s remaining:    1.5s
[Parallel(n_jobs=2)]: Done   8 out of  10 | elapsed:    3.3s remaining:    0.8s
[Parallel(n_jobs=2)]: Done  10 out of  10 | elapsed:    4.4s finished
Out[43]: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [44]: joblib_084.Parallel(verbose=10, n_jobs=2, pre_dispatch='2 * n_jobs')(joblib_084.delayed(my_square)(x) for x in range(10))
[Parallel(n_jobs=2)]: Done   1 jobs       | elapsed:    1.2s
[Parallel(n_jobs=2)]: Done   2 jobs       | elapsed:    1.2s
[Parallel(n_jobs=2)]: Done   5 jobs       | elapsed:    2.3s
[Parallel(n_jobs=2)]: Done   8 out of  10 | elapsed:    3.3s remaining:    0.8s
[Parallel(n_jobs=2)]: Done  10 out of  10 | elapsed:    4.4s finished
Out[44]: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [45]: joblib_084.Parallel(verbose=10, n_jobs=2, pre_dispatch='n_jobs')(joblib_084.delayed(my_square)(x) for x in range(10))
[Parallel(n_jobs=2)]: Done   1 jobs       | elapsed:    1.2s
[Parallel(n_jobs=2)]: Done   2 jobs       | elapsed:    1.2s
[Parallel(n_jobs=2)]: Done   5 jobs       | elapsed:    2.3s
[Parallel(n_jobs=2)]: Done   8 jobs       | elapsed:    3.3s
[Parallel(n_jobs=2)]: Done  10 out of  10 | elapsed:    4.4s finished
```

Note that by pre_dispatch is a fairly subtle thing withing joblib so I don't recommend changing it from the default unless you understand what you are doing. 

This serves merely an illustration that in the generic case you have no way of knowing how many tasks remain to be run.

**Comment by nilsbecker** [comment]
i see, so it was only a coincidence that i saw the full number... maybe then a solution would only work in some lucky cases not in general. not sure if that's worth pursuing then..
