### ISSUE TITLE
filter_args should return a sorted list of pairs

### ISSUE THREAD

**Issue by arthurmensch** [joblib/joblib#235]
Related to https://github.com/nilearn/nilearn/issues/771

Providing hashing.hash with a dictionary of arguments that have the same hash returns a different cash, causing cache recomputation.

**Comment by GaelVaroquaux** [comment]
Can you explain better / give us a minimal example to reproduce.

**Comment by GaelVaroquaux** [comment]
hashing.hash sorts dictionaries internally. Elsewhere it would not be able to reproducibly hash dictionaries, as their iteration order is random.
