### ISSUE TITLE
Replace deprecated usage of inspect.getargspec

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#247]
inspect.getargspec has been deprecated since 3.0 (in favor of inspect.getfullargspec until 3.2 and in favor of inspect.signature since 3.3) and will be removed in 3.6. It also creates visible DeprecationWarning in 3.5.

**Comment by mangecoeur** [comment]
+1 - it also has issues if you use function annotations (such as type annotations in 3.5)

**Comment by lesteve** [comment]
> it also has issues if you use function annotations (such as type annotations in 3.5)

Indeed this was noted in #182.

**Comment by mangecoeur** [comment]
Note (from Python docs): Consider using the new Signature Object interface, which provides a better way of introspecting functions. 

https://docs.python.org/3.4/library/inspect.html?highlight=getfullargspec#inspect-signature-object

**Comment by lesteve** [comment]
Yep we know about it. The problem is that we need to have a compatible interface for python 2 and python 3 and we haven't settled on the way forward yet. scikit-learn went for kind of backporting  Signature whereas other projects (scipy, django for example off the top of my head) went for keeping a getargspec-like interface.
