### ISSUE TITLE
test_numpy_persistence fails in windows

### ISSUE THREAD

**Issue by fabianp** [joblib/joblib#25]
pristine win32 with python(x,y) 2.7.2.1. The backtrace can be found here (sorry but I couldn't copy from that console, it's driving me crazy).

![backtrace](https://lh5.googleusercontent.com/-r4rhGBQRkyk/Tw2NpVE2UlI/AAAAAAAAAKM/ys5FQxa370w/s800/Screenshot-Windows%252520XP%252520Professional%252520-%252520VMware%252520Player.png)

**Comment by lesteve** [comment]
Has been fixed since.
