### ISSUE TITLE
Implement a real subprocess backend that does not rely on multiprocessing

### ISSUE THREAD

**Issue by ogrisel** [joblib/joblib#256]
Multiprocessing is problematic under Python 2.7 because it used fork instead of fork+exec which causes various problems.

Instead we could implement our own backend, for instance taking inspiration of this gist:

   https://gist.github.com/albertz/4177e40d41cb7f9f7c68

Maintaining our own backend would also make it possible to implement support for nested parallelism.

**Comment by ogrisel** [comment]
We should also have a look at multiprocess: https://pypi.python.org/pypi/multiprocess

**Comment by GaelVaroquaux** [comment]
Prototyping work to establish the basics to fix this issue is ongoing in https://github.com/tomMoral/loky

**Comment by ogrisel** [comment]
Indeed.
