### ISSUE TITLE
format_records attempts to tokenize .pyc file

### ISSUE THREAD

**Issue by mfrodl** [joblib/joblib#258]
This issue was originally reported as https://github.com/scikit-learn/scikit-learn/issues/5412, but since the root cause appears to be in Joblib, let us discuss it here instead.

Steps to reproduce:
```python
# imported.py
def raise_exc(x):
    raise Exception
```

```python
# test.py
from joblib import delayed, Parallel
from imported import raise_exc

print Parallel(n_jobs=2)(delayed(raise_exc)(i) for i in range(2))

```
Now try to run the test.py script:
```
$ python test.py
An unexpected error occurred while tokenizing input file /home/mfrodl/sandbox/imported.pyc
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (4, 0))

An unexpected error occurred while tokenizing input file /home/mfrodl/sandbox/imported.pyc
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (4, 0))

...
```
Proposed fix follows, see the original issue for a more detailed justification:
```diff
diff --git a/joblib/format_stack.py b/joblib/format_stack.py
index bef5c3b..1abd496 100644
--- a/joblib/format_stack.py
+++ b/joblib/format_stack.py
@@ -195,6 +195,10 @@ def format_records(records):   # , print_globals=False):
             # the abspath call will throw an OSError.  Just ignore it and 
             # keep the original file string.
             pass
+
+            if file.endswith('.pyc'):
+                file = file[:-4] + '.py'
+
         link = file
         try:
             args, varargs, varkw, locals = inspect.getargvalues(frame)
```

**Comment by GaelVaroquaux** [comment]
Should this be closed? The corresponding PR has been merged.

**Comment by mfrodl** [comment]
Okay with me.

**Comment by kw-moeller** [comment]
FYI, I seem to get the same issue with .so files: 

    An unexpected error occurred while tokenizing input file /xxx/anaconda2/lib/python2.7/site-packages/h5py/_objects.so
    The following traceback may be corrupted or invalid
    The error message is: ('EOF in multi-line statement', (1918, 0))

**Comment by lesteve** [comment]
@kw-moeller I think .so files were tackled in 90deace. Please open an issue with a stand-alone snippet reproducing the problem if that is not the case.
