### ISSUE TITLE
Parallel progress in IPython notebook

### ISSUE THREAD

**Issue by stefdoerr** [joblib/joblib#266]
Hey all, I wanted to ask if someone has gotten the progress (like with verbose=11) to show in an IPython notebook. If I use 1 CPU it prints nicely but once I parallelize with more CPUs no output is shown until the Parallel call has finished executing. In a normal IPython console session it prints fine but not in the Notebook.
I tried creating my own Callback class and monkey-patching it in with
`joblib.parallel.CallBack = CallBack`
to see if flushing the stdout helps, but with no success.

**Comment by lesteve** [comment]
Maybe just try to increase the verbose parameter?

With this snippet, I can see the stderr in the IPython notebook:

```python
from math import sqrt

import joblib

def my_sqrt(x):
    return sqrt(x)

joblib.Parallel(n_jobs=2, verbose=11)(joblib.delayed(my_sqrt)(i**2) for i in range(10))
```

**Comment by stefdoerr** [comment]
Try range(100000). Then you will see that it only print on completion, not during computation

**Comment by GaelVaroquaux** [comment]
@lesteve: are we using stderr or stout to print progress?

If we are using stderr, its a bug of IPython, not of us (the semantics of
stderr are that it should be printed immediatly). If we are using stdout,
we should probably switch to stderr, and hopefully this solves the
problem.

**Comment by stefdoerr** [comment]
Looks like stderr to me since it's painted with red background in the Notebook.
Okay then I will try my luck with the IPython devs, thank you :) 

Also, if I want to add my own progress bar is there a nicer way than that ugly patching I did before? Would it be possible to just pass to Parallel a callback method to call whenever a job finishes? (with some thread lock)

**Comment by GaelVaroquaux** [comment]
> Also, if I want to add my own progress bar is there a nicer way than
> that ugly patching I did before? Would it be possible to just pass to
> Parallel a callback method to call whenever a job finishes? (with some
> thread lock)

I don't think that it is a priority right now: we have many things that
we need to improve with Parallel (specifically support nested parallel
computing and support Parallel as a generator).

**Comment by lesteve** [comment]
> Try range(100000). Then you will see that it only prints on completion, not during computation

Still printing into the notebook for me...

About stdout vs stderr, it depends on the verbosity, if verbosity > 50 we print to stdout and stderr otherwise. As mentioned [here](https://github.com/joblib/joblib/blob/fcb6f05e452aa2de3c292c902927c00ca9403331/joblib/parallel.py#L259). Not sure exactly why, maybe @GaelVaroquaux remembers?

**Comment by GaelVaroquaux** [comment]
> About stdout vs stderr, it depends on the verbosity, if verbosity > 50
> we print to stdout and stderr otherwise. As mentioned here. Not sure
> exactly why, maybe @GaelVaroquaux remembers?

I remember doing that. I think it was for tests. I think doctests.

With hindsight, it might be a stupid thing to do.

**Comment by lesteve** [comment]
> I remember doing that. I think it was for tests. I think doctests. 

For the record, I can run the tests (including doctests) removing this `verbose < 50` condition.

**Comment by GaelVaroquaux** [comment]
> For the record, I can run the tests (including doctests) removing this verbose
> < 50 condition.

Than I would vouch for removing it. Let's wait for @ogrisel's point of
view on this, but I think that it would be good to simplify the behavior.

**Comment by stefdoerr** [comment]
@lesteve you mean it's printing out in real-time? It prints the stderr for me as well but only at the end of the computations.

Could you maybe tell me your ipython / notebook versions? Although I think I am at the latest one but who knows...

**Comment by lesteve** [comment]
My bad I read your original post too quickly: I thought you were saying you weren't getting any ouput in the notebook.

I see the same as you then, i.e. the stderr is only printed at completion and not while the jobs are executing.

An updated snippet showing more clearly the problem:

```python
import time
from math import sqrt

import joblib

def my_sqrt(x):
    time.sleep(0.1)
    return sqrt(x)

joblib.Parallel(n_jobs=2, verbose=11)(joblib.delayed(my_sqrt)(i**2) for i in range(100))
```

**Comment by lesteve** [comment]
I am going to close this one, since it doesn't seem related to joblib. @stefdoerr feel free to reopen if I turn out to be wrong.

**Comment by MInner** [comment]
Here's an ugly workaround, but it works

```
from tqdm import tqdm_notebook as tq
from joblib import Parallel, delayed
import time

import random

def func(x):
    time.sleep(random.randint(1, 10))
    return x

def tp(seq):
    ## text progessbar
    step = 1
    tick = time.time()
    while True:
        time_diff = time.time()-tick
        avg_speed = time_diff/step
        print('step', step, '%.2f' % time_diff, 'avg: %.2f iter/sec' % avg_speed)
        step += 1
        yield next(seq)

print(Parallel(n_jobs=5)(tq(
            (delayed(func)(i ** 2 + j) for i in range(5) for j in range(5)), 
            total=25)))

print(Parallel(n_jobs=5)(tp(delayed(func)(i ** 2 + j) for i in range(5) for j in range(5))))
```

**Comment by lesteve** [comment]
@MInner I haven't looked at what your gist does in detail, but this problem has been fixed in ipykernel 4.3. Please update your jupyter notebook and dependencies.

**Comment by lesteve** [comment]
More details at https://github.com/jupyter/notebook/issues/700 and associated PR.

**Comment by stefdoerr** [comment]
I think his gist is about my other question which was how to register your own progress bar

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.

**Comment by lesteve** [comment]
> His gist is about my other question which was how to register your own progress bar which AFAIK is still not supported by joblib.

Ah right, out of curiosity what kind of information do you want in your progress bar on top of what Parallel already prints? It would be great to create a separate issue for this custom progress bar/callback and explain your use case there, in order to maintain sanity in our tracker.
