### ISSUE TITLE
Try lzma for compression on Python >= 3.3 in our persistence

### ISSUE THREAD

**Issue by GaelVaroquaux** [joblib/joblib#273]
Once #260 is merge, we should consider using (maybe optionally) lzma for compression under Python >= 3.3.

Indeed, lzma is shipped in the standard library in Python >= 3.3:
https://docs.python.org/3/library/lzma.html

I think that it is much faster than gzip.

It means that object persisted in Python 3 won't load in Python 2, but that's fine.

**Comment by lesteve** [comment]
It'd be nice to make small realistic benchmark to estimate how much we can gain from using lzma vs gzip.

> It means that object persisted in Python 3 won't load in Python 2, but that's fine.

It is already the case anyway so we just need to make sure that the error message is reasonably user-friendly.

The thing I am not sure about is how you want to use it in real-life, maybe something like this:

```python
import joblib

joblib.dump(obj, '/tmp/pickle.gz', compressed=True)  # creates a gz
joblib.dump(obj, '/tmp/pickle.lzma', compressed=True, use_lzma=True)  # creates a lzma
```

Maybe a heuristic based on the filename extension would make the signature slightly nicer?

Other better suggestions?

**Comment by GaelVaroquaux** [comment]
> joblib.dump(obj, '/tmp/pickle.gz', compressed=True)  # creates a gz
> joblib.dump(obj, '/tmp/pickle.lzma', compressed=True, use_lzma=True)  # creates a lzma

> Maybe a heuristic based on the filename extension would make the signature
> slightly nicer?

> Other better suggestions?

compressed=True => lmza if available
compressed=[number] => corresponding lzma compression if available, if
not corresponding gzip compression
compressed='lmza[number]' or compressed='gz[number]' => explicit choice

I would like this scheme because it pushes for good default, and is an
extension of what we currently have.

**Comment by lesteve** [comment]
> compressed=True => lmza if available compressed=[number] => corresponding lzma compression if available, if not corresponding gzip compression compressed='lmza[number]' or compressed='gz[number]' => explicit choice I would like this scheme because it pushes for good default, and is an extension of what we currently have.

This seems more or less acceptable. The slight problem with this approach is that it may surprise people when switching from Python2 to Python3 that:

```python
joblib.dump(obj, '/tmp/pickle.gz', compressed=True)
```

actually produces a lzma file rather than a gzip one as you would expect with Python 2. Quite surprising, but maybe this is not such a big deal.

A note to ourselves for later we would need to figure out which lzma default we want for compressed=True.

**Comment by aabadie** [comment]
> A note to ourselves for later we would need to figure out which lzma default we want for compressed=True.

The actual implementation is compress=value, with value as an int (0,1,3,9) accepted. So True is equivalent to 1.

**Comment by lesteve** [comment]
> The actual implementation is compress=value, with value as an int (0,1,3,9) accepted. So True is equivalent to 1.

IIRC compressed=True is equivalent to compress=3.

**Comment by aabadie** [comment]
> IIRC compressed=True is equivalent to compress=3.

Indeed, but I changed this behavior in PR #260 as it appears to me like a regression from the behavior described in http://gael-varoquaux.info/programming/joblib-beta-release-fast-compressed-persistence-python-3.html.

**Comment by lesteve** [comment]
> Indeed, but I changed this behavior in PR #260 as it appears to me like a regression from the behavior described in http://gael-varoquaux.info/programming/joblib-beta-release-fast-compressed-persistence-python-3.html.

My take on it: PR #260 is involved enough that we don't want to add additional changes that are not really related to the single-file feature.

**Comment by GaelVaroquaux** [comment]
> My take on it: PR #260 is involved enough that we don't want to add additional
> changes that are not really related to the single-file feature.

+1. It is often wise to change only one feature per PR.

**Comment by aabadie** [comment]
Ok, I see. In PR #260, some line of code were removed by mistake. I'll update the docstring to better reflect this behavior.

**Comment by GaelVaroquaux** [comment]
Should this be closed?

**Comment by lesteve** [comment]
Yep.
