### ISSUE TITLE
Make it easier to extend joblib.Parallel with a custom backend

### ISSUE THREAD

**Issue by jdemeyer** [joblib/joblib#276]
I know this title is very generic but let me explain:

I am a developer for SageMath and I learned about joblib recently during some talk at the OSI day in Paris-Saclay (Orsay). One problem with Python is that the `multiprocessing` module sucks badly. It seems that `joblib.Parallel` tries to make the front-end more user-friendly by adding a better API. However, all the problems which really come from the `multiprocessing.Pool` backend are not addressed.

In SageMath, we have implemented a module to run [doctest](https://docs.python.org/2/library/doctest.html) in parallel. It has a custom implementation of something like `multiprocessing.Pool` features using `multiprocessing.Process`. This works very well but it's really a custom-built solution just for doctesting.

We would like to use multiprocessing (the principle, not the Python module) also in other places in SageMath. There are two options: either we make our custom-built parallel doctester into a proper Python package or we look for existing solutions (we don't want to reinvent the wheel). For the latter, I looked at `joblib.Parallel` but I really don't like the `multiprocessing.Pool` backend.

Since `joblib.Parallel` is more about providing a nice front-end and the SageMath parallel doctester is more about providing a solid backend, it would be useful to combine efforts and make it possible to allow `joblib.Parallel` to use a backend written by SageMath.

Note that the SageMath code is not 100% portable (it assumes POSIX) and has dependencies other than Python (in particular Cython), so it probably will not be possible to add the SageMath backend to the `joblib` codebase.

**Comment by lesteve** [comment]
Maybe loosely related to #256 ?

**Comment by GaelVaroquaux** [comment]
@jdemeyer : it's a great idea in general. We have been discussing making it possible to plug generic backends into joblib. So we do like the idea in general.

What would need to be done is to define an interface for an object that could be used as a replacement of the pool. And then we could add a global registry to set such an object as used by joblib. Also, we could pass the constructor of the object to the 'threading' argument in a given Parallel, to override this global default.

Also, as you can see from #256, it seems that we agree on limitations of multiprocessing. While it seems that your code cannot be added as such to joblib, maybe we can draw some inspiration from it. However, I fear licensing problems. Joblib is BSD-licensed, as most of Python's stack. Sage is GPL licensed. As such we cannot copy code from Sage to Joblib. Even reading the codebase can be dodgy from a licensing perspective (IANAL :D ). We would need someone that knows the codebase to guide us through what you have learned (https://en.wikipedia.org/wiki/Clean_room_design).

**Comment by jdemeyer** [comment]
I made a small mistake: the SageMath doctester does not use `subprocess`, but `multiprocess.Process`.

**Comment by jdemeyer** [comment]
> What would need to be done is to define an interface for an object that could be used as a replacement of the pool.

I am thinking in the direction of an event loop model: have a `Pool`-like base class with various methods which can be called from the outside (e.g. start a worker, kill all workers, evaluate a function) and with event handlers which can be provided by a subclass (e.g. computation of one function is finished, worker raised exception).

**Comment by GaelVaroquaux** [comment]
> I am thinking in the direction of an event loop model: have a Pool-like base
> class with various methods which can be called from the outside (e.g. start a
> worker, kill all workers, evaluate a function) and with event handlers which
> can be provided by a subclass (e.g. computation of one function is finished,
> worker raised exception).

You're moving us away significantly from the current design. I am not
completely against such a model, but it will require much much more work,
and will take much longer to be merged.

**Comment by jdemeyer** [comment]
Well, I haven't looked at the `joblib.Parallel` code so I don't know how easy/hard this would be.

**Comment by jdemeyer** [comment]
> You're moving us away significantly from the current design.

Feel free to propose something else. I'll probably end up writing such an event-loop based backend anyway and then adapt it to use with `joblib.Parallel`.

Also keep in mind that I want this hypothetical backend to be used for much more than just `joblib.Parallel`. It should really support all kind of multiprocessing use-cases.

**Comment by lesteve** [comment]
There were some developments since and there are now a distributed and an IPython.parallel backend. @jdemeyer if that is the kind of thing that you were looking for, maybe you could try to your own backend. Here is a [link](http://www.slideshare.net/AlexandreAbadie/pydata-joblib-abadie/19) from @aabadie's presentation at PyData Paris 2016 which explains the basic.

**Comment by lesteve** [comment]
@jdemeyer just curious, have you had any chance at trying writing a joblib.Parallel backend for your use case?

**Comment by jdemeyer** [comment]
No sorry, I currently don't have the time for this.

**Comment by lesteve** [comment]
No worries I understand we have many many things on our hands. Well if you find the time to try it out and get stuck, let us know.

**Comment by hristog** [comment]
I could be wrong (I can see that the most recent comments here are from after the opening and merge of the latter) but to me it seems this can be closed, as a result of https://github.com/joblib/joblib/pull/306 having been merged a while ago.

**Comment by tomMoral** [comment]
Indeed, there is now an API to subclass the parallel backend: https://joblib.readthedocs.io/en/latest/parallel.html#custom-backend-api-experimental that was merged in #320

Let's close this issue.
