### ISSUE TITLE
Raise an error instead of a warning when numpy_pickle.load is called with both compress and mmap_mode parameters set

### ISSUE THREAD

**Issue by aabadie** [joblib/joblib#281]
I know this is open to discussion but the idea here is to force users to call functions the right way instead of internally fix their mistakes.

So the idea here is just replace the warning message by a ValueError exception being raised when the `load` function is called with `compress` and `mmap_mode`.

**Comment by lesteve** [comment]
@aabadie we staid with the warning in the end right?

**Comment by aabadie** [comment]
I think I entered this one because there was no consensus on this. I have no strong opinion about this.

**Comment by lesteve** [comment]
From what I remember we staid with the warning, so let's close this one.

**Comment by GaelVaroquaux** [comment]
Indeed, suppose a user is doing a computation, ie "in production mode". The
error crashes the computation, and when the user comes back from week end,
he doesn't have his results. Or, it brings down the web server. So, it's
not great for the default user.

I guess that the power user knows that he can convert warnings to errors,
so if he really wants to capture warnings, he can.
