### ISSUE TITLE
joblib not available via conda

### ISSUE THREAD

**Issue by ericmjl** [joblib/joblib#299]
I just noticed that the latest version of joblib is not available via `conda install`. Would it be helpful if I started uploading it to anaconda? I am happy to do this small task.

**Comment by GaelVaroquaux** [comment]
> I just noticed that the latest version of joblib is not available via conda
> install.

Indeed.

> Would it be helpful if I started uploading it to anaconda?

I think that it would be. Thanks!

Note that there is also some relevent discussion about this on:
https://github.com/ContinuumIO/anaconda-issues/issues/599

**Comment by ericmjl** [comment]
Hmm... seeing as they've started on it, I think I will wait on it for a bit before acting. I will keep tabs on that anaconda thread though. Thanks! :smile:

**Comment by GaelVaroquaux** [comment]
> I will keep tabs on that anaconda thread though. Thanks! :smile:

You may want to :+1: it.
