### ISSUE TITLE
SEGFAULT when doing parallel linear algebra

### ISSUE THREAD

**Issue by ivannz** [joblib/joblib#310]
I stumbled upon a very strange system crash, when trying to perform linear algebra
in parallel jobs using **joblib**. I noticed that the crash seemed to go away when I was
explicitly **not** importing **matplotlib.pyplot** in the main thread. This made me
hypothesise that somehow the plotting library was involved. However, a brief discussion
with one of the developers (@jenshnielsen) of **matplotlib** [here](https://github.com/matplotlib/matplotlib/issues/5966) eliminated this hypothesis.

@jenshnielsen and I were able to produce a minimal python script that reproduces
the fault. I enclose this script together with the relevant information with this report.

[numpy_joblib_crash.zip](https://github.com/joblib/joblib/files/117956/numpy_joblib_crash.zip)

**Comment by ivannz** [comment]
Forgot to mention, this [issue](https://github.com/numpy/numpy/issues/5752) might be relevant.

**Comment by ivannz** [comment]
The example works fine when the size of the matrix is **127x127**, but crashes for **128x128**.

```
import numpy as np
from joblib import Parallel, delayed

X = np.ones((128, 128), dtype=np.float)
y = np.dot(X, X)

jobs_ = (delayed(np.linalg.det)(X) for i in range(2))
Parallel(n_jobs=-1, verbose=1)(jobs_)
```

**Comment by lesteve** [comment]
This may be related to https://pythonhosted.org/joblib/parallel.html#bad-interaction-of-multiprocessing-and-third-party-libraries.

**Comment by ogrisel** [comment]
I am pretty sure this is the reason and int that case you can use the forkserver start method or recompile numpy (and possibly scipy) to use another BLAS/LAPACK implementation that is not subject to this problem. If not please feel free to reopen.
