### ISSUE TITLE
[Feature request] Allow dump and load to use file handles rather than strings

### ISSUE THREAD

**Issue by jlopezpena** [joblib/joblib#312]
I have noticed that the `load` and `dump` functions are limited to using strings as filenames, 
and always write/read to/from disk.

At work I often need to dump sklearn models and save them into a database (mongodb/gridfs).
To do that, right know I just save to disk, and then `open` the saved file from the disk in order to get a file handler that subsequently I push into GridFS, which introduces unnecessary overhead. For this purpose, it would be very convenient to allow `joblib.dump` to return the file handler without saving to disk.

For loading model from the database, I tweaked my own version of the `load` function that takes as an input the file handler (coming from the db request) and then makes the appropriate calls to the unpickler:

```python
def load_handle(file_handle):
    """Reconstruct a Python object from a (compressed) file persisted with joblib.dump.

    Parameters
    -----------
    file_handle: File-type object
        The file from which to load the object
    Returns
    -------
    result: any Python object
        The object stored in the file.

    """
    unpickler = ZipNumpyUnpickler("whatever", file_handle=file_handle)
    obj = unpickler.load()
    return obj
```

It seems that `ZipNumpyUnpickler` is also expecting some filename string, which is not used when a file_handle is passed. I believe this could be done in a cleaner way.

**Comment by aabadie** [comment]
@jlopezpena, your idea is interesting and this is something we already discussed with @ogrisel while working on PR #260. When this PR will be merged, I hope soon :), it will be easy to extend `dump` and 'load` functions with what you suggest.

Regarding the required `filename` parameter, it's is required in the current master implementation with numpy arrays in 2 cases : when the arrays size is greater than `cache_size`(default is 10MB) and when using memory mapped arrays. I guess your use case is not compatible with the latter.
