### ISSUE TITLE
Parallel job takes more time than non-parallel job? 

### ISSUE THREAD

**Issue by chengguangnan** [joblib/joblib#317]
It seems that my batches are executed one by one rather than been parallel? I'm using iPython. It's 32 core machine. 

```
import pandas, numpy, hashlib
from joblib import Parallel, delayed

d = pandas.DataFrame({'a': numpy.random.randn(1000 * 1000)})

def hash(x):
    return hashlib.sha256(x.encode('utf-8')).hexdigest()
```

The output:
```

In [35]: Parallel(n_jobs=-1, batch_size=100 * 1000, verbose=20) (delayed(hash) (str(row[1:])) for row in (d.itertuples()))
[Parallel(n_jobs=-1)]: Done  32 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 100032 tasks      | elapsed:    6.8s
[Parallel(n_jobs=-1)]: Done 200032 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done 300032 tasks      | elapsed:   20.1s
[Parallel(n_jobs=-1)]: Done 400032 tasks      | elapsed:   26.9s
[Parallel(n_jobs=-1)]: Done 500032 tasks      | elapsed:   33.9s
[Parallel(n_jobs=-1)]: Done 600032 tasks      | elapsed:   40.8s
[Parallel(n_jobs=-1)]: Done 700032 tasks      | elapsed:   47.5s
[Parallel(n_jobs=-1)]: Done 800032 tasks      | elapsed:   54.2s
```

**Comment by GaelVaroquaux** [comment]
> It seems that my batches are executed one by one rather than been parallel?

What makes you think that?

**Comment by chengguangnan** [comment]
From the verbose log, you can see that, each step finishes in for 7 seconds in between. 

Also `htop` shows  only on one core is active. Change n_jobs form 2 to 16 doesn't seem to change the performance. Also, the paralleled steps takes more time than single thread step.

Here is the testing code:

```
from joblib import Parallel, delayed
import pandas, numpy
import hashlib
import time
import sys



def hash(x):
    return hashlib.sha256(str(x).encode('utf-8')).hexdigest()[:30]

if __name__ == '__main__':
    ## Create pairs of points for line segments
    d = pandas.DataFrame({'a': numpy.random.randn(500 * 1000)})

    now = time.time()
    if len(sys.argv) >= 2:
        res = Parallel(n_jobs=int(sys.argv[1])) (delayed(hash) (x[1]) for x in d.itertuples())
    else:
        res = [hash(x[1]) for x in d.itertuples()]
    print("Finished in", time.time()-now , "sec")
```

**Comment by chengguangnan** [comment]
Sorry, it seems that it does created processes to do the job. However, it just takes a longer time to run than single process. 

Maybe because this task is heavily IO? A lot of strings is passing around, but the computing is fast? That's why this job doesn't parallel well?

**Comment by GaelVaroquaux** [comment]
First thing is that I suppose that iterating on "d.itertuples()" in the main process isn't very cheap. You would be better off creating a few large chunks dataframes from your original dataframe, and pass these to subprocesses, that then use the list comprehension in the subprocesses.

I am closing this, as it is not an issue, but the discussion can continue.

**Comment by chengguangnan** [comment]
Thanks for the tip! I will try that.

**Comment by GaelVaroquaux** [comment]
> Thanks for the tip! I will try that.

Don't hesitate to report here if it worked or not: it can be useful for
people stumbling on this issue.

**Comment by chengguangnan** [comment]
It worked. Thanks. The execution time is 2 seconds rather than 12 seconds. 
```
    chunks = []
    for i in range(1, len(d), 1000):
       chunks.append(d[i:min(i + 1000, len(d))])

    res = Parallel(n_jobs=-1) (delayed(hash) (d) for d in chunks)

    def hash(d):
        return [hashlib.sha256(str(x).encode('utf-8')).hexdigest()[:30] for x in d.itertuples(index=False, name=None)]
```

**Comment by chengguangnan** [comment]
Question, what is a good size to split? So for a 16 core machine, maybe we should just split into 16 chunks? I assume that smaller chunks, saying 32 or 64 chunks for a 16 core machines could reduce the initial IO load? 

Should I use my own chunks? Or use the joblib batch_size? What's the difference? 



So what is pre_dispatch?

**Comment by GaelVaroquaux** [comment]
> Question, what is a good size to split? So for a 16 core machine, maybe
> we should just split into 16 chunks? I assume that smaller chunks,
> saying 32 or 64 chunks for a 16 core machines could reduce the initial
> IO load?

I don't know. I'd be curious to hear but what you find empirically.

> Should I use my own chunks? Or use the joblib batch_size? What's the
> difference?

When you are chunking with your own chunks, you can benefit from the fact
that it's a panda dataframe, and thus it is easier to chunk and to persit
than a list of possible heterogeneous items.

> So what is pre_dispatch?

Something that sends jobs in advance. Also useful to speed up things.

**Comment by ogrisel** [comment]
I would chunk into `n_workers * 2` or `n_workers * 4`, that is  32 or 64 chunks if you expect some chunk to take more time than others (data dependent running time in case of iterative solvers for instance). The goal would be to limit the impact of stragglers on the overall run time.

If you are sure that chunks will take a very similar time to run, then splitting in `n_workers` chunks (e.g. 16 in your case) is likely to be slightly faster.

There is a tradeoff between mitigating scheduling overhead and better CPU cache prefetch usage which favors a lower number of larger chunks and mitigating stragglers which favors a larger number of smaller chunks.

**Comment by ogrisel** [comment]
`pre_dispatch` should probably be left to the default value now that we have auto batching of very small tasks. But you can do some experiments.

I think you performance problem stems from the early conversion to heterogeneous tuples that incurs large serialization overhead w.r.t. chunks of pandas dataframes.

**Comment by Debabrataadak** [comment]
from math import sqrt
from joblib import Parallel, delayed
from numpy import square
import numpy as np
import time

n=10000000
def sim(x):
   # time.sleep(100)
    return x**2

chunk=[]
arr=np.arange(n)
for i in range(0,len(arr),100):
        chunk.append(arr[i:(i+100)])


if __name__ == "__main__":

    result = Parallel(n_jobs=1, backend="threading", verbose=5) \
        (delayed(square)(x) for x in chunk)

    #print result




I did the same. But the time taken by a single core is less than using 8 cores.
