### ISSUE TITLE
Number of task done exceeds total amount of tasks

### ISSUE THREAD

**Issue by jaksmid** [joblib/joblib#327]
I run Parallel job - 8 workers, input arguments was list of 2 paths.
Job completed and on the commandline I got:

```
[Parallel(n_jobs=8)]: Done   3 out of   2 | elapsed:  8.9min remaining:  -178.2s
[Parallel(n_jobs=8)]: Done   2 out of   2 | elapsed:  8.9min finished
```

3 out of 2 does not make sense

I am using python 2.7.11 in the virtual evironmnet on Mac - El Captain

**Comment by aabadie** [comment]
Thanks for reporting the issue @jaksmid. I could reproduce the issue with the following snippet:
```python
from math import sqrt
from joblib import Parallel, delayed
Parallel(n_jobs=2, verbose=5)(delayed(sqrt)(i**2) for i in range(2))
```
which returns:
```
[Parallel(n_jobs=2)]: Done   3 out of   2 | elapsed:    0.0s remaining:   -0.0s
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.0s finished
```

It looks like a race condition somewhere, the first line shouldn't be displayed. @ogrisel, any idea ?
