### ISSUE TITLE
Calling script containing joblib from another file on Windows

### ISSUE THREAD

**Issue by rowanwins** [joblib/joblib#331]
So I've managed to script up a process which is working well as a standalone process, as the docs specify the parallel process currently resides within ````if __name__ == '__main__':````

Im now trying to call my script from another python file however if I try to call my script from another file the check on __main__ does not pass and my parallel script can be executed?

I have tried calling my script via subprocess and this allows me into __main__ however it's having some other adverse affects on my script

Am I missing anything obvious?
Thanks in advance

**Comment by GaelVaroquaux** [comment]
Do a function, call this function in __main__ and also call this function
from another file.

**Comment by rowanwins** [comment]
I've tried this sort of setup but unfortunantly I get 
````
ImportError: [joblib] Attempting to do parallel computing without protecting your import on a system that does not support forking. To use parallel-computing in a script, you must protect your main loop using "if __name__ == '__main__'". Please see the joblib documentation on Parallel for more information
````

Am using python 2.7 on windows.

It looks like in my task manager that multiple python processes are happening but I think they are in some state of error...
