### ISSUE TITLE
Exclusive (no-overwrite) mode for joblib.dump

### ISSUE THREAD

**Issue by anntzer** [joblib/joblib#333]
It would be nice if `dump` gained an `exclusive=False` keyword, similar to the `"x"` mode of `open`: raise `FileExistsError` if a pre-existing file would be overwritten.

This would also help against a rather silly vulnerability of uncompressed pickles, i.e. `joblib.dump(..., "foo.pkl")` may not only overwrite a preexisting "foo.pkl" (which is sort-of fine), but also a preexisting "foo.pkl_01.npy" (which I think is a bit awkward).

**Comment by lesteve** [comment]
Can you expand on why this is a problem, maybe with some kind of use case ?

FWIW #260 is going to change joblib pickles so that they are always in a single file. Does that alleviate your problem ?

**Comment by anntzer** [comment]
This is exactly the same reason as to why `open` gained an `"x"` mode: to avoid accidentally overwriting a preexisting file.
The issue with split-pickles is secondary and rather theoretical (especially as I always compress my pickles anyways...).

**Comment by lesteve** [comment]
> This is exactly the same reason as to why open gained an "x" mode: to avoid accidentally overwriting a preexisting file.

OK fair enough (I was hoping to hear more what you meant by "silly vulnerability"), I guess it's quie easy to do (note: the 'x' mode is only supported since Python 3.3, see [this](https://docs.python.org/3/whatsnew/3.3.html#io)). The focus is currently on getting #260 merged but when that's done, we'll try to get back to this issue.

**Comment by GaelVaroquaux** [comment]
Could you detail why joblib would have to implement this, rather than the
user via a check?

Also, if we implement a mode where you can take an open file handle
rather than a file name, would that solve your usecase?

**Comment by anntzer** [comment]
Mostly for practicality.  A minor advantage is also to get rid of a (again, somewhat theoretical) race condition: `if not os.path.exists(filename): joblib.dump(..., filename)` could still overwrite a file that is created between the two function calls, whereas an exclusive open would not.

But I now realize that it may be tricky to support this behavior on older Pythons (namely those that don't support `open(..., "x")`), so perhaps letting the user pass an open file handle (which he can create in whatever mode works for him) would be best.  So feel free to close this.

**Comment by GaelVaroquaux** [comment]
I think that we'll close this, in the name of feature creep, and also
because I think that we should focus on enabling to pass in a file
handle.

**Comment by lesteve** [comment]
Agreed, closing.
