### ISSUE TITLE
Adding timeout to Parallel class so that jobs can timeout 

### ISSUE THREAD

**Issue by iandewancker** [joblib/joblib#337]
Added small amount of code to support time outs.  Old pull request I had : #201.

**Comment by ogrisel** [comment]
Can you please add some tests and open a PR? Also I would recommend you not to commit your master branch but use one branch per new feature / bug fix instead.

**Comment by iandewancker** [comment]
created a new PR because did pull merge instead of rebase : https://github.com/joblib/joblib/pull/340.  Diff looks clean now, no conflicts with master

**Comment by iandewancker** [comment]
Darn, looks like the executor.Future class in distributed doesn't support the timeout arg

`<class 'distributed.executor.Future'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8bb9ae192202> in <module>()
      5
      6 with parallel_backend('distributed', scheduler_host='localhost:8786'):
----> 7         res = Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(10))

/home/ian/joblib/joblib/parallel.pyc in __call__(self, iterable)
    753                 # consumption.
    754                 self._iterating = False
--> 755             self.retrieve()
    756             # Make sure that we get a last message telling us we are done
    757             elapsed_time = time.time() - self._start_time

/home/ian/joblib/joblib/parallel.pyc in retrieve(self)
    674             try:
    675                 print type(job)
--> 676                 self._output.extend(job.get(timeout=self.timeout))
    677             except tuple(self.exceptions) as exception:
    678                 # Stop dispatching any new job in the async callback thread

TypeError: result() got an unexpected keyword argument 'timeout'`
