### ISSUE TITLE
Update installation instructions in docs

### ISSUE THREAD

**Issue by mangecoeur** [joblib/joblib#339]
Documentation currently recommends `easy_install` at the first option, which is not really the recommended way to do things these days. Probably would be better to recommend `pip install` and also mention that it can be installed with common scientific python packages like anaconda using `conda install`.

**Comment by ogrisel** [comment]
+1, would merge a PR that does the change.

**Comment by GaelVaroquaux** [comment]
> +1, would merge a PR that does the change.

+1.
