### ISSUE TITLE
command line unpickling

### ISSUE THREAD

**Issue by anntzer** [joblib/joblib#346]
`python -mpickle foo.pkl` prints the pickled value to stdout, which is practical for quick command line checking.  It would be nice if joblib provided the same, e.g. via `python -mjoblib unpickle foo.pkl`.

**Comment by lesteve** [comment]
I didn't know about that pickle feature, nice!

Given that this is two lines of python, I am not sure this is really worth it, unless you can come with a very good use case.

**Comment by anntzer** [comment]
As you say yourself, it's a nice feature for pickle :-) so the use case is the same for joblib -- checking the contents of a pickle without firing up an interpreter.

**Comment by lesteve** [comment]
> As you say yourself, it's a nice feature for pickle :-)

Given the number of years I have used Python without knowing about this hidden pickle feature, I would say that there are more important things to do in joblib than this ...

I am going to close this one, feel free to reopen if you feel strongly about it.
