### ISSUE TITLE
Regression: joblib.hash fails on 0d array

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#347]
```python
import numpy as np
import joblib

arr = np.array(0)
joblib.hash(arr)
```

Works with joblib 0.9.4 and fails on master with the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-c182cb63f185> in <module>()
----> 1 joblib.hash(arr)

/home/le243287/dev/alt-scikit-learn/sklearn/externals/joblib/hashing.py in hash(obj, hash_name, coerce_mmap)
    256     else:
    257         hasher = Hasher(hash_name=hash_name)
--> 258     return hasher.hash(obj)

/home/le243287/dev/alt-scikit-learn/sklearn/externals/joblib/hashing.py in hash(self, obj, return_digest)
     66     def hash(self, obj, return_digest=True):
     67         try:
---> 68             self.dump(obj)
     69         except pickle.PicklingError as e:
     70             e.args += ('PicklingError while hashing %r: %r' % (obj, e),)

/volatile/le243287/miniconda3/lib/python3.5/pickle.py in dump(self, obj)
    406         if self.proto >= 4:
    407             self.framer.start_framing()
--> 408         self.save(obj)
    409         self.write(STOP)
    410         self.framer.end_framing()

/home/le243287/dev/alt-scikit-learn/sklearn/externals/joblib/hashing.py in save(self, obj)
    205             # taking the memoryview.
    206             self._hash.update(
--> 207                 self._getbuffer(obj_c_contiguous.view(self.np.uint8)))
    208 
    209             # We store the class, to be able to distinguish between

ValueError: new type not compatible with array.
```

Full disclosure I discovered this when running the nilearn tests using joblib master.

**Comment by aabadie** [comment]
The problem comes from the `np.view()` which is called on an array with a `shape == ()`

I locally happened :
```python
if len(obj_c_contiguous.shape) == 0:
                obj_c_contiguous.shape = (1, )
```
just before the call to `view()` and it works. Any thoughts on this ?

**Comment by lesteve** [comment]
I don't think that's the right solution because a 0d array would have the same hash as a 1d array of shape (1, ) unless I am missing something. We should check what the previous code was doing and try to do the same.

**Comment by aabadie** [comment]
>  We should check what the previous code was doing and try to do the same.

I had a look : previously the `ValueError` exception was catch by a `try except` where the input was simply flattened.
I tested this solution in master and the hash results are the same as before this regression was introduced. The two lines above should be:
```python
if len(obj_c_contiguous.shape) == 0:
    obj_c_contiguous = obj.flatten()
```
@lesteve, let me know if it's ok and I'll open a PR with a test.

**Comment by ogrisel** [comment]
LGTM.

**Comment by lesteve** [comment]
This solution does the same as changing the shape to (1,) so has the same problem. I agree this was the previous behaviour but that seems like a bug to me. Is there nothing better we can do here?

**Comment by aabadie** [comment]
> This solution does the same as changing the shape to (1,) so has the same problem.

Indeed, but I compared the results of hashing and they are not the same. See PR #350.

**Comment by lesteve** [comment]
> Indeed, but I compared the results of hashing and they are not the same. See PR #350.

The hash is different indeed, the shape is actually used in the hash on top of the flattened array seen as bytes. It all makes sense.
