### ISSUE TITLE
Clean TODO.rst file, please?

### ISSUE THREAD

**Issue by kuraga** [joblib/joblib#348]
Clean TODO.rst file, please?

**Comment by lesteve** [comment]
Welcome to the real world, which is not always perfect, as you may already have realised. In particular don't expect a file that is called TODO.rst and hasn't been changed in almost four years to reflect the reality.

`<irony>`
If this answer fails to satisfy you, maybe you can modify your joblib checkout with this patch:
```diff
diff --git a/TODO.rst b/TODO.rst
index 8357163..ca96575 100644
--- a/TODO.rst
+++ b/TODO.rst
@@ -49,3 +49,4 @@ Tasks at hand on joblib, in increasing order of difficulty.
   frequency of use.
 
 
+* Clean TODO.rst file, please?

```
`</irony>`

**Comment by GaelVaroquaux** [comment]
I am to blame here. We could transform it in a set of enhancement
tickets, and then remove it from the repo.
