### ISSUE TITLE
python parallel computing using joblib in pycharm on windows

### ISSUE THREAD

**Issue by shahlaebrahimi** [joblib/joblib#368]

**Comment by FI-Mihej** [comment]
Hello shahlaebrahimi,
There is a very basic bug in your own code. Really, you should learn Python basics at first. Parallel computing is an advanced technology - try to return to it some later - when you'll be able to create some simple Python scripts.
Best regards

**Comment by lesteve** [comment]
@shahlaebrahimi closing this one. Feel free to reopen if you have a more precise question to ask.

**Comment by shahlaebrahimi** [comment]
@lesteve  Thanks. I solved that issue, but now I do not know how to deal with the following one:
[](https://github.com/danielhomola/mifs/issues/2). regards,

**Comment by lesteve** [comment]
@shahlaebrahimi from the look of it, it looks like you are starting with Python and github. Here are a few words of advice:
* start with tutorials to learn the basics
* read the documentation if you get stuck
* Google is your friend, use it
* Ask on StackOverflow if you can't figure it out on your own

Also a little bit of etiquette: it is really really really frowned upon to email directly developers.

**Comment by shahlaebrahimi** [comment]
It seems unpleasant to inform developers of bugs!
