### ISSUE TITLE
Virtual Memory blows up when passing an object argument to a function in a Parallel process 

### ISSUE THREAD

**Issue by MartinHjelm** [joblib/joblib#369]
I couldn't find any warning about this in the documentation so I thought I would create an issue as it created a bit of confusion for me. I am using Python 3.5.1 and joblib version 0.9.4 on OSX Capitan. I have a Parallel loop in the following manner 

```
    cfgObj = cfg(some_parameters)
    results = Parallel(n_jobs=3)(delayed(computeScore)(cfgObj,i) for i in range(0,cfgObj.iterations))
```

The cfgObj contains a set of lists, dictionaries, and some data, a couple of 100 kB at most. If I pass the cfgObj to the computeScore the Parallel process starts out fine but after a while the memory starts to really blow up and go from a 1-2 GB to 13-15GB for each process,   

<img width="556" alt="screen shot 2016-06-20 at 11 24 28" src="https://cloud.githubusercontent.com/assets/1571080/16224863/47ec8d02-37a4-11e6-962c-ae0c7431c9f2.png">

whereupon everything eventually grinds to a halt. 

However, if I pickle the cfg object and load it in the computeScore function everything works great without the memory blowing up. Like this,

```
cfgObj = cfg(some_parameters)
with open('cfgObj.pkl', 'wb') as output:
    pickle.dump(cfgObj, output, pickle.HIGHEST_PROTOCOL)
results = Parallel(n_jobs=3)(delayed(computeScore)(i) for i in range(0,cfgObj.iterations))

def computeScore(iter):
    with open('cfgObj.pkl', 'rb') as input:
        cfgObj = pickle.load(input)
```

I am also using the forkserver,

```
import multiprocessing
if __name__ == '__main__':
    multiprocessing.set_start_method('forkserver')
```

Maybe this is something that should be added to the documentation.

**Comment by GaelVaroquaux** [comment]
Are you using 'pred_dispatch' to avoid creating a very long list of jobs
at the beginning of the parallel loop?

**Comment by lesteve** [comment]
> Are you using 'pred_dispatch' to avoid creating a very long list of jobs at the beginning of the parallel loop?

From his snippet it looks like he is using the default `pre_dispatch` which is `2 * n_jobs`.

@MartinHjelm could you try to reproduce the behaviour in a stand-alone snippet? This way we could see if we manage to reproduce the problem. This behaviour is certainly unexpected.

**Comment by MartinHjelm** [comment]
@GaelVaroquaux  I tried using the pre_dispatch like this

    results = Parallel(verbose=11, n_jobs=3,pre_dispatch=3)(delayed(computeScore)(cfgObj,i) for i in range(0,cfgObj.iterations))

The memory still blows up, but just a bit more slowly. I thinking here that it might be the creation and running of the gradient descent object(see pseudo code below) that might be the problem. I don't explicitly delete the object after it has run since I was thinking that it automatically would get released after the computeScore function has finished. 

@lesteve I think it will be difficult to create a stand alone snippet there is a lot of code...but I can try. I have a paper deadline so after that. A general outline of my code is:

**file1.py**
    
    import multiprocessing
    if __name__ == '__main__':
        multiprocessing.set_start_method('forkserver')
        ....
        cfgObj = cfg(some_parameters)
        runJob(cfgObj)

**file2.py**

    class cfg():
       # Where cfg is set up 
   
    # Stand alone functions
    def runJob(cfgObj):
        results = Parallel(verbose=11, n_jobs=3,pre_dispatch=3)(delayed(computeScore)(cfgObj,i) for i in range(0,cfgObj.iterations))

    def computeScore(cfgObj,i):
        grdObj = gradientDescent(cfgObj.some_of_the_parameters_and_data)
        grdObj.run()

**file3.py**

    # Gradient Descent Class
    class gradientDescent(): 
    ...
        def run():
            # Run gradient descent on the data, i.e., for loops over numpy arrays.

**Comment by MartinHjelm** [comment]
Ok. Sorry for getting back so late to this. My bad. 

So the major problem was that I was caching a lot of matrix products inside the gradientDescent class in a dictionary. Those matrix product's memory consumption blew up as the dimensions of the data increased and some other properties changed. In addition these cached matrices weren't getting released in the proper way when the the function inside the loop exited, that is, it seems the garbage collection took a bit too long before the next iteration(here I am just guessing since I don't know anything about garbage collection in Python). Deleting the objects at the end of the function call for each loop call seemed to fix this. 

So all along my crappy coding was to blame. Sorry.

**Comment by lesteve** [comment]
OK, thanks for letting us know, do reopen if you see the problem reappear!
