### ISSUE TITLE
expose ParallelBackendBase?

### ISSUE THREAD

**Issue by mheilman** [joblib/joblib#377]
It seems like it'd be nice to make `ParallelBackendBase` public so that people could use it to implement custom backends without having to import from a "private" module (i.e., `from joblib._parallel_backends import ParallelBackendBase`).

Would it make sense to include `ParallelBackendBase` in the import [here](https://github.com/joblib/joblib/blob/62c0914fb52e69360c8724183f6d06c1e236532b/joblib/parallel.py#L30-L31), or in `__all__` for the top-level package (i.e., [here](https://github.com/joblib/joblib/blob/62c0914fb52e69360c8724183f6d06c1e236532b/joblib/__init__.py#L135))?

**Comment by ogrisel** [comment]
I think that would make sense. Any opinion @GaelVaroquaux?

**Comment by jnothman** [comment]
`distributed.joblib` also [imports](https://github.com/dask/distributed/blob/master/distributed/joblib.py#L3) `AutoBatchingMixin` from the private module.

**Comment by GaelVaroquaux** [comment]
+1 for exposing it (as well as the AutoBatchingMixin) in a public place,
but maybe not in the __init__ of the package.

**Comment by ogrisel** [comment]
Ok done as 1eb46cae54e71b5625ea9adad47f6a83b6531024. Will be part of joblib 0.10.1.
