### ISSUE TITLE
Inconsistent suffix behavior in joblib.dump()

### ISSUE THREAD

**Issue by banilo** [joblib/joblib#379]
There appear to be different cases in which joblib.dump() actually adds a .npy suffix to the end of the file.

1) dump() without compress leading to one output file seems to add .npy to the specified filename
2) dump() without compress leading to more than one output file adds .npy only to the 2nd, 3rd, etc. file created
3) dump() with compress does not add a .npy

Is it possible to harmonize the cases to common behavior. More generally, it would be nice to dump() and load() with the exact same filename string, rather than having to add '.npy' in some but not all cases.

**Comment by ogrisel** [comment]
The `.npy` filenames are for auxiliary files. The main filename is always the one you pass to `dump` irrespective of the compress option.

Anyway auxiliary files have disappeared altogether in joblib 0.10.
