### ISSUE TITLE
SafeFunction is now private?

### ISSUE THREAD

**Issue by nspies** [joblib/joblib#380]
I've just updated to the latest joblib and it appears that the `SafeFunction` class has been moved from a public module (`joblib.parallel`) to a "private" module (`joblib._parallel_backends`). Was there a rationale for this? I guess I understand the refactoring in general, but I'm hoping that the move to an underscore module means that this class isn't available to external code.

**Comment by GaelVaroquaux** [comment]
Why were you using it?

In my mind, it was undocumented, hence not used.

**Comment by nspies** [comment]
I'm not honestly sure -- I wrote the code that uses it many years ago. I'm not using the rest of joblib, I think I just use `SafeFunction` as a wrapper for my own multiprocessing code so that I can use ctrl-c and `transportableexception`s. I believe the ctrl-c thing still doesn't work properly with the latest version of multiprocessing on python 2.7?

**Comment by nspies** [comment]
...and it's not really a huge deal if it disappears, obviously I could copy the parts that I use.

**Comment by GaelVaroquaux** [comment]
I am trying to figure if there are really usecases that we should
support, or if we should keep it private.

**Comment by nspies** [comment]
Just did a bit of testing and it looks like the latest version of multiprocessing fixes some of these issues, or that there are at least some workarounds, so I'll update my code to no longer use joblib.
