### ISSUE TITLE
Parallel class does not use temporary directory

### ISSUE THREAD

**Issue by jetheurer** [joblib/joblib#391]
I do not have `/dev/shm` on the instance I'm using (an AWS lambda) and therefore, I thought joblib would be an appropriate solution to allow me to use a [different directory](http://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda/34032458#34032458).  However even after specifying: `temp_folder='/tmp'`, I'm getting the following error message:

```
'NoneType' object has no attribute 'current_process': AttributeError
Traceback (most recent call last):
File "/var/task/world.py", line 74, in handler
r = Parallel(n_jobs=1, verbose=9, temp_folder=temp_folder, backend = 'multiprocessing')(delayed(worker)(i, user_vars) for i in range(user_vars['worlds']))
File "/var/task/deps/joblib/parallel.py", line 728, in __call__
n_jobs = self._initialize_backend()
File "/var/task/deps/joblib/parallel.py", line 540, in _initialize_backend
**self._backend_args)
File "/var/task/deps/joblib/_parallel_backends.py", line 288, in configure
n_jobs = self.effective_n_jobs(n_jobs)
File "/var/task/deps/joblib/_parallel_backends.py", line 268, in effective_n_jobs
if mp.current_process().daemon:
AttributeError: 'NoneType' object has no attribute 'current_process'
```

mp imports from `_multiprocessing_helpers` and I must fail at [line 27](https://github.com/joblib/joblib/blob/master/joblib/_multiprocessing_helpers.py#L27).  I dont think I can create an `mp.Semaphore()`

```
[Errno 38] Function not implemented: OSError
Traceback (most recent call last):
File "/var/task/world.py", line 74, in handler
mp.Semaphore()
File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 197, in Semaphore
return Semaphore(value)
File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 111, in __init__
SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX)
File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 38] Function not implemented
```

Using `backend='threading'` works just find, so this is a `multiprocessing` issue.  How can I get around this?  **Should I be using an environmental variable to define the directory?**

**Comment by jetheurer** [comment]
@lesteve Thanks for your insights.  

* I have been able to get the `Process` class from multiprocessing to work on AWS Lambda, however you are right, none of the classes that depend on Semaphones like `Queue`, `Pool`.  Are you familiar with a python library that lets me take advantage of multiple cores?  Its been suggested that I try [Eventlet](http://eventlet.net/doc/examples.html)

* You are right, the actual failure is further down the line.

**Comment by yarikoptic** [comment]
I am observing first issue (`AttributeError: 'NoneType' object has no attribute 'current_process'`) also while building fresh sklearn against the fresh joblib 0.10.2.  To not starve build hosts I set JOBLIB_MULTIPROCESSING=0 which is just supposed to turn joblib multiprocessing off, while still performing the execution (worked e.g. with joblib 0.9.4 and before).  Unfortunately logic in 0.10.2 seems to be flawed since if `0` it sets mp to None, but then without check tries to access its attributes.

I guess it would be nice if there also was a test which would set this variable to 0 and attempts perform computation(s).

**Comment by lesteve** [comment]
@yarikoptic thanks for raising this issue and sorry about that. I'll take a look at this one shortly.

**Comment by lesteve** [comment]
Closing this one, there is nothing joblib can do about this.

**Comment by manojkumar1412** [comment]
If anyone is still facing this issue, updating sklearn will resolve this. installing scikit-learn using conda version 4.3.14, put a line at 268 of  checking mp is none then return 1. which resolve this issue.
