### ISSUE TITLE
BinaryZlibFile: self._fp may not have seekable() function in python 2.7

### ISSUE THREAD

**Issue by csfoo** [joblib/joblib#398]
The file object created by [`open()`](https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle_utils.py#L303) does not support the `seekable()` function in python 2.7 (but it does in python 3), which will lead to an `AttributeError: 'file' object has no attribute 'seekable'` error on the following calls:

https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle_utils.py#L351
https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle_utils.py#L389

A possible solution would be to replace `open`  with `io.open`, but that wouldn't help if the user passed in a file object.

**Comment by aabadie** [comment]
Thanks @csfoo for reporting this. I could reproduce this problem locally.
Note that the BinaryZlibFile object is not meant to be used outside of joblib and is used only internally as a convient file-like object for zlib/gzip compression.
Joblib pickling functions don't use seek and the `seekable()` function is just here for compatibility with io buffering objects.
Do you have a specific use-case in mind (with an example snippet) ?

**Comment by csfoo** [comment]
I actually discovered this issue while adapting BinaryZlibFile for use with the Zstd library (to get around a bug in python 2.7's zlib which limits file sizes to < 4GB) because joblib does a seek to detect the file type at the beginning.

**Comment by aabadie** [comment]
The seek is only used to determine the file type is only performed in the internal [_detect_compressor()](https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle_utils.py#L68) function. Of course, the top-level file-like object has to be seekable and not compressed. So if you pass there a BinaryZlibFile (which is not meant for that), you can expect troubles. Supported file-like objects in this case here are io.open or open which are seekable.

If you try with other file-like object (gzip.GzipFile, bz2.Bz2File, lzma.LzmaFile), the compressor detection is skipped so there's no seek in this case.

**Comment by lesteve** [comment]
@aabadie should this one have been closed by #400 being merged?

**Comment by aabadie** [comment]
@lesteve, yes. Closing.

**Comment by lesteve** [comment]
Great thanks!
