### ISSUE TITLE
malloc seg fault

### ISSUE THREAD

**Issue by samuela** [joblib/joblib#415]
I'm seeing a peculiar seg fault when running joblib via scikit-learn: 

```
python(92117,0x7fff762ef000) malloc: *** mach_vm_map(size=18446744065559752704) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11
```

For whatever reason it appears as though joblib is attempting to malloc a gargantuan object. On some runs I see this behavior and on others, joblib runs briefly and then hangs without producing an error. I'll work on narrowing down a cleaner example that I can post publicly to demonstrate the issue.

**Comment by samuela** [comment]
cc @iandewancker

**Comment by ogrisel** [comment]
Thats 18 exabytes if I am not mistaken...

I would really be interested in a minimal reproduction script.

Which version of scikit-learn are you using? Which operating system (and architecture)?

I assume that you are using the version of joblib embedded in scikit-learn, is that right?

**Comment by samuela** [comment]
This is with scikit-learn version 0.18 and joblib versions 0.10.2 and 0.10.3 (I tried both). I'm on Mac OS X 10.11.6. I'll work on some example code...

I can't say for certain but I'm also seeing behavior similar to what's described in https://github.com/joblib/joblib/issues/125. Might be related.

**Comment by GaelVaroquaux** [comment]
You should give us some code to reproduce the problem.

I suspect that it is just that you are trying to process data that is too
big for your memory.

**Comment by samuela** [comment]
@GaelVaroquaux That was my initial suspicion as well, but I've done some quick math and it doesn't seem to be the case. There's really no way that it could possibly end up being 18 exabytes.

**Comment by magbone** [comment]
I have the same issue. My mode dumped on Windows and loaded well at the same machine,  but It didn't work well on MacOS(Big Sur 11.5.2).

**Comment by ogrisel** [comment]
Unfortunately, we cannot attempt to fix this problem without a minimal reproducer. Please feel free to open a new issue if you manage to craft one.

See https://scikit-learn.org/dev/developers/minimal_reproducer.html for help on how to do this in a machine learning / scikit-learn context for instance.
