### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by jakirkham** [joblib/joblib#416]
Please add a license file and please add it to `MANIFEST.in`.

**Comment by eickenberg** [comment]
fyi the license is in the readme.
but it is true that github would automatically tag the repo with the license if there were a license file

**Comment by jakirkham** [comment]
Yes, I do see that. However, it is a bit cleaner to have a license file. Also it is also easier for auditors to confirm the license as opposed to having it contained in some other document that they have to look through.

I'd be willing to open a PR if it would be accepted.

**Comment by lesteve** [comment]
> I'd be willing to open a PR if it would be accepted.

Go for it!

**Comment by lesteve** [comment]
License added in 5319efa6a4ddcb830db95eaeb6ac97f66cb9fc1c.
