### ISSUE TITLE
Registering custom progress bars

### ISSUE THREAD

**Issue by stefdoerr** [joblib/joblib#423]
It would be nice if we could register our own progress bar through some callback as mentioned in this thread: https://github.com/joblib/joblib/issues/266

@MInner posted a solution for that here: https://github.com/joblib/joblib/issues/266#issuecomment-258345306

To follow on @lesteve's question, the current "progress bar" leaves a bit to be desired as it just prints red text line by line on notebooks. Notebooks support fancy JS widgets for progress bars as the one shown by @MInner. 

But in general I would prefer to register my own progress bar to keep my project visually consistent and not have each software print a different progress bar.

**Comment by stefdoerr** [comment]
Well the solution by @MInner worked perfectly for me. I just modified it to use my progressbar class ending up with this:

```python
def progessbar(seq, description=None, total=None):
    p = ProgressBar(total, description=description)
    while True:
        try:
            yield next(seq)
            p.progress()
        except StopIteration:
            p.stop()
            raise

def ParallelExecutor(use_bar='txt', **joblib_args):
    def aprun(bar=use_bar, **tq_args):
        def tmp(op_iter):
            foo = lambda args: lambda x: progessbar(x, **args)
            bar_func = foo(tq_args)
            return Parallel(**joblib_args)(bar_func(op_iter))
        return tmp
    return aprun
```

**Comment by lesteve** [comment]
Great if it works from you, apart from the fact that the snippet could be tidied up a bit to look less lispy (the nested lambda in particular) ;-).

Originally I thought maybe there could be some weird interaction with the task batching but think it will be just fine. If you want to make sure you can try with `batch_size=2` for example and make sure that your progress bar still works as expected.

Out of interest, what does your progress bar look like?

**Comment by stefdoerr** [comment]
I can choose between the text one or the widget one

![screenshot from 2016-11-04 13-28-46](https://cloud.githubusercontent.com/assets/7935362/20005496/ef3b80fa-a292-11e6-9fda-f8b901090182.png)

**Comment by anntzer** [comment]
You may want to look into tqdm (https://tqdm.github.io/) which provides nice progress bars for both the terminal and the notebook.

**Comment by MInner** [comment]
@anntzer my original [snippet](https://gist.github.com/MInner/12f9cf961059aed1a60e72c5531a697f) used tdqm, if you're interested :) I suggest leaving `tdqm` as a default progressbar handler, but give an option to register a custom one.

Btw, one obvious drawback of the generator I posted above is that it counts "started" jobs, not "finished" ones. I just realized that an easy workaround is to use the following wraper:

```
def wrap_gen(op_seq, **tqdm_args):
   bar = tqdm(**tqdm_args)
   while True:
       yield next(op_seq)
       next(bar)
```

instead of `tqdm(op_seq, **tqdm_args)`.

**Comment by stefdoerr** [comment]
@MInner yeah I noticed it as well. But I think I'll have to live with it for now

**Comment by lesteve** [comment]
I'll close this one, since there is a work-around and we do not plan to work on this feature in the near future. Feel free to reopen if you strongly disagree.

**Comment by marscher** [comment]
I just wonder why people dont just use the provided Callback interface. Of course this is also "hacky" ;)
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/_base/estimator.py#L291-L311

Maybe joblib should provide an Observer pattern, where clients can register to catch these events.

**Comment by stefdoerr** [comment]
I tried in the past but it was much hackier than the above solution.
Also broke quite often as there were some changes in the CallBack class.

**Comment by MInner** [comment]
I found some solution that used `CallBack` on stackoverflow, but it didn't work either
