### ISSUE TITLE
Rewrite getfullargspec function in func_inspect module

### ISSUE THREAD

**Issue by aabadie** [joblib/joblib#442]
This is a follow-up of #435 (partially fixed by #437 and #440)

As described in the docstring, this is function is a
```Compatibility function to provide inspect.getfullargspec in Python 2
    This should be rewritten using a backport of Python 3 signature
    once we drop support for Python 2.6. We went for a simpler
    approach at the time of writing because signature uses OrderedDict
    which is not available in Python 2.6.
```

**Comment by lesteve** [comment]
Thanks for creating the issue. Also this https://github.com/joblib/joblib/pull/437#issuecomment-264476963 is relevant. The idea I think is to do like scikit-learn does and use a `inspect.signature` backport for Python 2.

**Comment by lesteve** [comment]
I just checked and `inpect.getfullargspec` does not produce DeprecationWarning in python 3.6.0rc1. I don't think this is super high priority.

**Comment by aabadie** [comment]
Was this already addressed ? Can it be closed ?

**Comment by lesteve** [comment]
Python 2 support has been dropped so probably yes.
