### ISSUE TITLE
Verify if the _read_bytes() function in numpy_pickle_utils.py module could be dropped

### ISSUE THREAD

**Issue by aabadie** [joblib/joblib#443]
Follow-up of #435 (and #440).

As reported in this [comment](https://github.com/joblib/joblib/pull/440#issuecomment-265187410), we should check if this function could be simply replaced with a call to `file.read()`.

For the record, `_read_bytes()` is called [here](https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle.py#L133).

**Comment by aabadie** [comment]
@lesteve, this issue seems very outdated. Do you think we could close it ?

**Comment by lesteve** [comment]
Still seems relevant but we can close this one and I'll open a more recent issue after remaining things from droping Python 2.

My opinion about lingering open issues, they are not bothering me too much, trying to close them manually in active open-source software projects like joblib (or even more hopeless scikit-learn) is a lost battle ... at the same time I can understand that when someone is used to look at one's open issues/PRs old issues like this can be seen as unnecessary noise ...

**Comment by aabadie** [comment]
For looking into stale Issues/PRs, you may want to have a look at https://github.com/apps/stale. We are using it in another project and it's useful.

**Comment by lesteve** [comment]
I have heard of it but not used it. I am not fully convinced but this is an alternative approach indeed.
