### ISSUE TITLE
Parallel should be able to take a backend instance as an argument

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#448]
At the moment it can only take strings or a multiprocessing context (as given for example by `multiprocessing.get_context()`).

A simple solution would be to check `isinstance(backend, ParallelBackendBase)` somewhere around [there](https://github.com/joblib/joblib/blob/master/joblib/parallel.py#L494).

**Comment by GaelVaroquaux** [comment]
> A simple solution would be to check isinstance(backend, ParallelBackendBase) somewhere around there.

+1. I like this solution.
