### ISSUE TITLE
Use comma-separated string rather than tuple in pytest parametrize arguments

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#455]
@karandesai-96 From http://doc.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions

> In versions prior to 2.4 one needed to specify the argument names as a tuple. This remains valid but the simpler "name1,name2,..." comma-separated-string syntax is now advertised first because it’s easier to write and produces less line noise.

**Comment by karandesai-96** [comment]
@lesteve sure, this way seems better. I will take care about this from #454 onwards. The previous ones will be handled separately.

**Comment by lesteve** [comment]
Yeah that's what I mean we can do that from now on and then remember to fix all of them at the end of the pytest migration.
