### ISSUE TITLE
Use pytest importorskip for numpy

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#456]
I came across importorskip while reading the pytest doc:
http://doc.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency

I am wondering whether we can use it an simplify our pytest code for skipping numpy tests.

cc @karandesai-96.

**Comment by karandesai-96** [comment]
@lesteve I tried it. Using it outside a function body will skip the whole module. Using it inside a function body is no better than a decorator.

**Comment by lesteve** [comment]
> Using it inside a function body is no better than a decorator.

But maybe we could have something like this?

```py
with_numpy = pytest.importorskip('numpy')
```

**Comment by karandesai-96** [comment]
The moment I do `from joblib.test.common import `with_numpy`, whole module gets skipped. Even I am confused why is it designed in this manner.

**Comment by lesteve** [comment]
OK fair enough it was just naive I guess (it's probably the same that decorator happens at import time so by decorating the function you are actually skipping the whole module) you are just meant to use it like this instead:

```py
def test_some_numpy_stuff():
    np = pytest.importorskip('numpy')
    arr = np.array([1., 2., 3.])
```

I think this does not make so much difference and I am fine with how we are currently doing it, so closing this one.

**Comment by karandesai-96** [comment]
This issue can be reopened and worked upon if pytest adds more to this "importorskip".
