### ISSUE TITLE
Remove setting / unsetting of verbose output in smoke tests.

### ISSUE THREAD

**Issue by karandesai-96** [joblib/joblib#457]
I have seen this in a few tests now, a block similar to this format:
```python
try:
    orig_stdout = sys.stdout
    orig_stderr = sys.stderr
    # test body
finally:
    sys.stdout = orig_stdout
    sys.stderr = orig_stderr
```

Well, pytest by default captures all the stdout and stderr, if a test fails then its captured output is displayed in the error log. I think it is safe to get rid of these blocks now.

* Reference: http://doc.pytest.org/en/latest/capture.html#default-stdout-stderr-stdin-capturing-behaviour

We can even perform regex comparisons to check content printed by the methods. Along with this, if any test needs to have a mandatory capturing disabled, then pytest also provides `capsys.disabled`.

* Reference: http://doc.pytest.org/en/latest/capture.html#accessing-captured-output-from-a-test-function

**Comment by karandesai-96** [comment]
@lesteve If you agree upon this, I think tackling this issue before moving further would be a nice idea. (Considering the length of **test_memory.py**).

**Comment by lesteve** [comment]
I saw that as well while browsing the documentation and I think it would be great to do.
