### ISSUE TITLE
ReadOnly python objects will make threading backend work perfectly on pure python code with shared variables?

### ISSUE THREAD

**Issue by jamartinh** [joblib/joblib#471]
Hello, just a question.

Suppose python had a feature to make an object read-only.

Does this will make threading backend work perfectly without locking when reading values from this read-only object ?

Does this will solve the main issue when using the "threading backend" when using pure python code using shared variables in each thread effectively bypassing a GIL lock ?

And if so, is this feature useful enough to ask for a python enhanced proposal ?

Thanks,
jamh.

**Comment by lesteve** [comment]
This seems like a very generic python question. I am afraid the joblib issue tracker is not meant for that.
