### ISSUE TITLE
Cannot pickle the result of SciPy linear regression

### ISSUE THREAD

**Issue by mangecoeur** [joblib/joblib#477]
SciPy linregress returns a namedtuple  of `slope : float,  intercept : float, rvalue : float, pvalue : float, stderr : float`. Joblib fails to serialize this:

```
MaybeEncodingError: Error sending result: '[LinregressResult(...)]'. Reason: 'PicklingError("Can't pickle <class 'scipy.stats._stats_mstats_common.LinregressResult'>: attribute lookup LinregressResult on scipy.stats._stats_mstats_common failed",
```

Seems to be related to the LinregressResult being defined withing the linregress function.

**Comment by lesteve** [comment]
Does it work with pickle? If not, this is a scipy problem.

**Comment by mangecoeur** [comment]
You are right, doesn't work with `pickle.dump` either. Will open an issue with SciPy.

**Comment by lesteve** [comment]
Thanks for closing the issue. FWIW a work-around would be to do a linear regression with scikit-learn. I am not sure whether scipy.stats.linregress has some functionalities that scikit-learn hasn't.

**Comment by mangecoeur** [comment]
thanks, for a workaround I ended up copy-pasting the namedtuple definition into my script and re-creating the result (`MyLinregressResult(*result)`. scikit-learn would work too, scipy is a bit simpler.
