### ISSUE TITLE
Parallel execution failing to catch exceptions

### ISSUE THREAD

**Issue by Dimpl** [joblib/joblib#480]
I am calling joblib.Parallel()(joblib.delayed(...)). When an exception is thrown by the function at ..., I receive the error: "TypeError: cannot concatenate 'str' and 'NoneType' objects" instead of the actual exception. I have tried and failed to diagnose the cause (of the above TypeError). Running the function in a regular for loop gives the expected exception (i.e. not the above TypeError).

**Comment by lesteve** [comment]
What is the error with n_jobs=1, i.e. using `Parallel(n_jobs=1)(...)`? With n_jobs=1 you can then use a debugger of your choice by running your snippet with `ipython --pdb` to further debug the problem.

If that does not help, could you post a stand-alone snippet reproducing the problem?

**Comment by Dimpl** [comment]
I'm encountering the problem in a specific execution environment. When I try to reproduce it, the expected exception handling appears. I don't know what the issue is, but it could be as straightforward as an old version.

**Comment by skynyrd** [comment]
I've got the same problem.

```
all_results = Parallel(n_jobs=1, verbose=50, timeout=5)((delayed(process_rule)(rule, command_processor) for rule in all_rules))
```

In `process_rule` method, a `KeyError` raises as it cannot find a specific field on a dictionary. When I set `n_jobs=1` and I wrap above line with a try-except block, I can catch the error. But if `n_jobs=-1`, it just hangs. 

How can I catch it? I also couldn't find a solution in the documentation.

**Comment by tomMoral** [comment]
@skynyrd Thanks a lot for reporting. Could you give us more information on the failure you observed and on the system you are using:
- The version of joblib you are running : 
```
$ python -c "from joblib import __version__; print(__version__)"
```
- A script reproducing the failure (with the `process_rule` function), so we can try locally to reproduce the issue.
