### ISSUE TITLE
Any known MPI backend for joblib?

### ISSUE THREAD

**Issue by XericZephyr** [joblib/joblib#481]
Hi, All

Are there any present MPI backend for MPI at this moment? If anyone knows that, please let me know. Thanks.

**Comment by lesteve** [comment]
Not that I know of.

**Comment by rth** [comment]
I could be wrong, but joblib has a [dask.distributed](http://distributed.readthedocs.io/en/latest/joblib.html) backend, and there is occastional talk about MPI support in that community https://github.com/dask/dask/issues/218 , https://github.com/dask/distributed/issues/776 , and
> Whether or you hate or love ZeroMQ you can now pick and choose. Antoine’s branch allows for easy swapping between transport mechanisms and opens the possibility for more in the future like intra-process communication with Queues, MPI, etc.. This doesn’t affect most users, but some Dask deployments are on supercomputers with exotic networks capable of very fast speeds.

from [this post](https://matthewrocklin.com/blog/work/2017/01/30/dask-dev-6) so maybe joblib could get a MPI backend indirectly that way one day..

**Comment by XericZephyr** [comment]
On many cluster, there is a shared NFS system, so I believe this could help 
https://distributed.readthedocs.io/en/latest/setup.html#using-a-shared-network-file-system-and-a-job-scheduler

**Comment by jakirkham** [comment]
There's an MPI launcher in Distributed and a joblib backend. It's only used to launch jobs on an MPI cluster. Distributed doesn't use MPI for anything else (meaning networking goes through TCP).

ref: https://distributed.readthedocs.io/en/latest/joblib.html
ref: https://github.com/dask/distributed/blob/1.22.0/distributed/cli/dask_mpi.py
