### ISSUE TITLE
joblib.Parallel gives different result w.r.t calling the function directly

### ISSUE THREAD

**Issue by xiaohan2012** [joblib/joblib#498]
I have a function (`experiment_multiple_rounds` in the code) that I would like to repeat with different input parameters (`epsilon`  in the code). 

However, the result by calling the function directly and by calling it via Parallel gives inconsistent result. 

Basically, `experiment_multiple_rounds` repeats certain rounds of experiments  in which input is randomly generated  for an algorithm to solve. 

The  cost of  each experiment is returned. Thus, the return result is a list of costs.

Then, I compute the mean and median of the list. 

The code:

```
rounds = 500
infp = 0.7
fraction = 0.02
epsilon = 0.8
sampling_method = 'late_nodes'

# calling it outside 
result = experiment_multiple_rounds(rounds, g, infp, fraction,
                                    epsilon=epsilon,
                                    sampling_method=sampling_method)
cnts, _ = zip(*result)
print(np.mean(cnts))  # 10.252
print(np.median(cnts)) # 8.0

# calling it using parallel
epsilons = [epsilon]
results = Parallel(n_jobs=-1)(
    delayed(experiment_multiple_rounds)(rounds, g, infp, fraction,
                                        epsilon=eps,
                                        sampling_method=sampling_method)
    for eps in epsilons)

cnts, _ = zip(*results[0])
print(np.mean(cnts))  # 14.208
print(np.median(cnts))  # 11.0
```

As you can see the result by `print`. The two ways of calling the function gives very different results. 

I repeatedly run the above code however their results are consistently far.

The definition of `experiment_multiple_rounds` is:

```
def experiment_multiple_rounds(rounds, g, infp, fraction, epsilon, sampling_method):
    np.random.seed(None)
    random.seed(None)
    results = []
    for i in range(rounds):
        source, obs_nodes, infection_times, tree = make_input(g, infp, fraction, sampling_method=sampling_method)
        r = mwu(g, source, obs_nodes, infection_times, epsilon)
        results.append(r)
    return results
```

For the relevant function `make_input` and `mwu`, please refer to [here](https://github.com/xiaohan2012/active-infection-source-finding/blob/master/simulations.py#L86) and [here](https://github.com/xiaohan2012/active-infection-source-finding/blob/master/multiplicative_weight_update.ipynb)

I am using:

- `joblib==0.10.3`
- `Python 3.5.2`

**Comment by GaelVaroquaux** [comment]
Could it be:
https://github.com/joblib/joblib/issues/36

http://stackoverflow.com/questions/31740561/random-number-generator-using-joblib

**Comment by xiaohan2012** [comment]
Thanks for informing this. 

However, I added the following to the function I called to make it random:

```
    np.random.seed(None)
    random.seed(None)
```

It still produces the same phenomenon.

**Comment by GaelVaroquaux** [comment]
I think that you need a different seed per function call, specifying it
in the call signature, with the seed set in the main loop.

**Comment by lesteve** [comment]
For the record, I had a quick look and it seems like the problem only affects `numpy.random` and not `random`:

```py
import random

import numpy as np

from joblib import delayed, Parallel


def my_random(set_seed_to_none=False, use_numpy=False):
    if use_numpy:
        if set_seed_to_none:
            np.random.seed(None)
        return np.random.randint(0, 10, size=3)
    else:
        if set_seed_to_none:
            random.seed(None)
        return [random.randint(0, 10) for _ in range(3)]

if __name__ == '__main__':
    print('stdlib')
    print(Parallel(n_jobs=2)(delayed(my_random)() for _ in range(6)))
    print('stdlib setting seed to None')
    print(Parallel(n_jobs=2)(delayed(my_random)(set_seed_to_none=True)
                             for _ in range(6)))
    print('numpy')
    print(Parallel(n_jobs=2)(delayed(my_random)(use_numpy=True)
                             for _ in range(6)))
    print('numpy setting seed to None')
    print(Parallel(n_jobs=2)(delayed(my_random)(
        set_seed_to_none=True, use_numpy=True)
                             for _ in range(6)))
```

Output:
```
stdlib
[[7, 10, 10], [4, 9, 6], [3, 7, 1], [8, 2, 6], [10, 9, 6], [0, 4, 8]]
stdlib setting seed to None
[[4, 3, 4], [4, 2, 8], [4, 0, 6], [9, 2, 2], [5, 0, 2], [3, 4, 0]]
numpy
[array([1, 9, 4]), array([1, 9, 4]), array([4, 6, 4]), array([4, 6, 4]), array([7, 8, 5]), array([5, 4, 7])]
numpy setting seed to None
[array([9, 1, 0]), array([3, 4, 2]), array([4, 4, 3]), array([5, 6, 0]), array([1, 9, 4]), array([4, 8, 8])]
```
