### ISSUE TITLE
ReadTheDocs documentation

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#506]
When I was releasing 0.11 I realised the way we upload the doc to pythonhosted.org was not working (at least I could not get the website to update although I was getting a status 200 from the website). At the very least it is deprecated and using ReadTheDocs seems to be the recommended approach.

I enabled ReadTheDocs and the doc for master is available https://joblib.readthedocs.io. For 0.11 I can make it available but it will have the default readthedocs theme which does not look great for the settings we use in our conf.py. I guess we just need to enable it next time we do a release.

I just opened this issue mostly to get feed-back and potentially suggestions about improvements we can make going forward. If everybody is happy with the way the doc on ReadTheDocs looks, I'll close it after some time.

**Comment by aabadie** [comment]
+1 in general

There's a small visual bug at the bottom of the main page between the footer and the `v:latest` popup menu.
Another improvement could be to add the [readthedocs badge](http://docs.readthedocs.io/en/latest/badges.html) in the README.

**Comment by GaelVaroquaux** [comment]
The ReadTheDocs site looks good. I am +1. We should update the
information in the setup.py.

**Comment by GaelVaroquaux** [comment]
> Another improvement could be to add the readthedocs badge in the README.

1 am -1 on that: it makes the README harder to read when you open it in
an editor and doesn't bring much.

**Comment by lesteve** [comment]
> There's a small visual bug at the bottom of the main page between the footer and the v:latest popup menu.

Do you mean they overlap? To be honest I did not spot that the ReadTheDocs popup was still here since it normally is on the bottom left.

Before I forget something we will need to do at one point is to upload to pythonhosted some basic html that redirects after a few seconds (there is no way to remove a project from pythonhosted IIRC). Something like this was done in sphinx-gallery at one point.

**Comment by jakirkham** [comment]
Sounds like all that is needed is the redirect now; given the docs appear to be on the ReadTheDocs.

**Comment by GaelVaroquaux** [comment]
Yes indeed. We need to update thev links in the docs and the Readme to point to read the docs. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by aabadie** [comment]
I checked readthedocs and actually the builds are failing since the LZ4 PR was merged. Apparently the compression example requires too much memory... I can have a look when time permits. Maybe we could also consider not building on (and using) readthedocs ?

**Comment by GaelVaroquaux** [comment]
Then we need to build on circleci and push somewhere (github  pages or packages.python.org).

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by ogrisel** [comment]
To use circleci to build the doc, we might want to try to use doctr:

https://drdoctr.github.io/doctr/

**Comment by jakirkham** [comment]
Would it possible to share the traceback of the failure?

**Comment by lesteve** [comment]
+1 for trying out doctr, it has been mentioned a few times already.

> Would it possible to share the traceback of the failure?

There is no traceback, here is the relevant piece of information from a [failed build](https://readthedocs.org/projects/joblib/builds/7383417/):
```
 python /home/docs/checkouts/readthedocs.org/user_builds/joblib/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

Command killed due to excessive memory consumption 
```

According to [this](https://docs.readthedocs.io/en/latest/builds.html#build-process) it seems like the memory limit is 1GB.

**Comment by aabadie** [comment]
+1 for doctr! From the documentation, it seems to only work with Travis. So we will need another line in the Travis build matrix.

Other comment: we can use a `gh_pages` and have the doc hosted in `joblib.github.com/joblib` or create a new project `joblib.github.io` in the `joblib` organization and push the doc there. I prefer the latter.

I can also work on that.

**Comment by GaelVaroquaux** [comment]
> +1 for doctr! From the documentation, it seems to only work with Travis. So we
> will need another line in the Travis build matrix.

OK. The reason that we use circle for building the docs is that it offers
more power machine, and longer build times. I hope that travis will be
enough 

> Other comment: we can use a gh_pages and have the doc hosted in
> joblib.github.com/joblib or create a new project joblib.github.io in the joblib
> organization and push the doc there. I prefer the latter.

I prefer the latter too.

However, is it possible to push to https://packages.python.org/joblib/,
as we used to do before the move to ReadTheDocs?

Gaël

**Comment by lesteve** [comment]
> From the documentation, it seems to only work with Travis.

I was not aware of that. Slightly annoying because it means this is not a solution that will be applicable to scikit-learn. I am wondering how much of doctr is Travis specific. I guess setting up the SSH keys is Travis specific but I am hoping that maybe deploying to github pages is not. FWIW there is an issue about supporting other CIs [here](https://github.com/drdoctr/doctr/issues/189). Also another option would be doing it ourselves, i.e. doing something similar to scikit-learn.

> However, is it possible to push to https://packages.python.org/joblib/, as we used to do before the move to ReadTheDocs?

Short answer no.

* when I created this issue I was not able to upload the documentation to pythonhosted.org as I mentioned in the original post.
* packages.python.org is now pythonhosted.org according to [this](https://wiki.python.org/moin/PyPiDocumentationHosting).
* pythonhosted.org is deprecated according to [this](https://github.com/pypa/pypi-legacy/issues/672#issuecomment-316125918).

**Comment by lesteve** [comment]
Goold old days 😉 this can be closed.
