### ISSUE TITLE
Cross-platform Memory.cache to tempfs

### ISSUE THREAD

**Issue by rth** [joblib/joblib#510]
Currently it is not possible use RAM / tempfs as the cache directory for the `Memory` class in a cross-platform way.

The corresponding logic is embedded within the [`MemmapingPool` class](https://github.com/joblib/joblib/blob/8fa1ca24be1af58b391dca6a0c0ec34d5b9f6ca6/joblib/pool.py#L531), 

```py
        if temp_folder is None:
            temp_folder = os.environ.get('JOBLIB_TEMP_FOLDER', None)
        if temp_folder is None:
            if os.path.exists(SYSTEM_SHARED_MEM_FS):
                try:
                    temp_folder = SYSTEM_SHARED_MEM_FS
                    pool_folder = os.path.join(temp_folder, pool_folder_name)
                    if not os.path.exists(pool_folder):
                        os.makedirs(pool_folder)
                    use_shared_mem = True
                except IOError:
                    # Missing rights in the the /dev/shm partition,
                    # fallback to regular temp folder.
                    temp_folder = None
        if temp_folder is None:
            # Fallback to the default tmp folder, typically /tmp
            temp_folder = tempfile.gettempdir()
```
and cannot be easily applied to the `Memory` class. 

Maybe it could be worth moving this chunk of code into a separate private function, that could also be called for some pre-defined values of the `cachedir` `Memory` parameter (for instance `cachedir=True`, since `cachedir=None` is already taken)?

**Comment by lesteve** [comment]
Can you explain your use case in more details? Do you want to use `/dev/shm` for your `Memory` `cachedir`?

**Comment by rth** [comment]
Yes, I want to use `/dev/shm` on Linux, but for the `Memory` `cachedir` to fall back to something reasonable on Windows without coding the logic myself (similarly to how `joblib.Parallel` is determining `temp_folder` when it's not explicitly provided)...

**Comment by GaelVaroquaux** [comment]
> Yes, I want to use /dev/shm on Linux,

I am worried that you'll blow your memory if you're not careful about
that.

**Comment by lesteve** [comment]
> I am worried that you'll blow your memory if you're not careful about
that.

Yeah that's what I thought as well. Also bear in mind that the current expectation about the cache is that it is persistent across python sessions. I would say that your use case is a bit off the beaten path.

**Comment by rth** [comment]
True, this might not be the typical use of the `Memory` class.. To give a bit more context, I'm trying cache computationally expensive intermediary steps in unit-tests, the [cache directory would be cleaned by `py.test`](http://stackoverflow.com/questions/42652228/removing-cached-files-after-a-py-test-run) when the tests exit, so the memory usage should (hopefully) be fine.

I see your point about not making the `Memory` class have this option by default. Still, maybe it could be worthwhile to put the `temp_dir` logic from `MemmapingPool` into some private function, so it could be potentially reused elsewhere?

**Comment by GaelVaroquaux** [comment]
> Still, maybe it could be worthwhile to put the temp_dir logic from MemmapingPool into some private function, so it could be potentially reused elsewhere?

I agree. Though we would probably still consider it as private.

**Comment by lesteve** [comment]
> To give a bit more context, I'm trying cache computationally expensive intermediary steps in unit-tests, the cache directory would be cleaned by py.test when the tests exit, so the memory usage should (hopefully) be fine.

Just curious why not use a `cachedir` in `/tmp` that lives for the duration of your tests ? Do you see a big performance difference ?

Also I am guessing that you are not that interested by using the JOBLIB_TEMP_FOLDER environment variable for your use case, right? It seems like you just want to do:

```py
cachedir = '/dev/shm' if os.path.exists('/dev/shm') else tempfile.gettempdir()
```
Not sure it is worth adding a function for this in joblib if that is all you want to do.

**Comment by rth** [comment]
> Just curious why not use a cachedir in /tmp that lives for the duration of your tests ? Do you see a big performance difference ?

Well probably not a huge performance difference, more avoiding writing to disk when it's not necessary (also with each of my stored objects in the 1-20 MB range, after loading these objects from cache several times due to `@pytest.mark.parametrize` that can become a non negligible amount of I/O).

> Also I am guessing that you are not that interested by using the JOBLIB_TEMP_FOLDER environment variable for your use case, right?
> Not sure it is worth adding a function for this in joblib if that is all you want to do.

True, but then there is also the case when `/dev/shm` is not writable for some reason, which the original function handles. 

It any case it's a non issue (I can just use that code), more an  observation that it was a shame to have that logic embedded within the `MemmapingPool`. Thanks for your response, I understand better why there is no such option in `Memory` by default. Closing this issue...

**Comment by lesteve** [comment]
> Well probably not a huge performance difference, more avoiding writing to disk when it's not necessary (also with each of my stored objects in the 1-20 MB range, after loading these objects from cache several times due to @pytest.mark.parametrize that can become a non negligible amount of I/O).

This may be premature optimization but it's hard to tell without numbers. Not sure this applies to your use case but it could help to use module-level fixtures that would allow to load your objects once per test module rather than once per test function.

> True, but then there is also the case when /dev/shm is not writable for some reason, which the original function handles.

Fair enough I missed the non-writable part. Feel free to open a PR with a test if you feel like it. Probably keeping the function private as mentioned @GaelVaroquaux, i.e. starting with an underscore, is more appropriate.
