### ISSUE TITLE
Is there a way to "checkpoint" the Parallel job?

### ISSUE THREAD

**Issue by XericZephyr** [joblib/joblib#512]
Hi, 

I ran into a situation that a long-run joblib parallel job could be terminated after a specific timeout, e.g., 24 hrs. I have to restart the entire process if terminated, which is quite frustrating. I was wondering if there is a way to persistent the current Parallel state and resume it after restart? Thanks.

**Comment by GaelVaroquaux** [comment]
You can use joblib.Memory on specific functions inside the code. This is
how I do it.
