### ISSUE TITLE
Pickling and unpickling numpy array changes hash

### ISSUE THREAD

**Issue by draustin** [joblib/joblib#517]
Hi there,

Thanks for joblib, I've found it very useful in scaling up my laser pulse propagation simulation.

I'm getting unexpected behaviour when combining caching of function results with multiprocessing. Pickling and unpickling a multidimensional numpy array appears to change the joblib hash. Numpy's array_equal function reports the original and pickled arrays are equal, as it should. I realize this could be a numpy and/or pickle issue. I do get the same results with dill, and do not see them with equivalent 'multidimensional' lists.

Here is a MWE:

```python
import joblib,pickle,dill
import numpy as np

hash=joblib.hashing.hash

def test(array,pickler):
    array_reloaded=pickle.loads(pickler.dumps(array))
    print(np.array_equal(array,array_reloaded),hash(array)==hash(array_reloaded))

# Output with numpy.__version__=1.11.1, joblib.__version__=0.11, Python 3.5.2, Windows 10
# Using pickle
test([1,2,3],pickle) # True True    
test(np.array([1,2,3]),pickle) # True True
test([[1],[2],[3]],pickle) # True True
test([[1,2,3]],pickle) # True True
test(np.array([1,2,3])[:,None],pickle) # True False
test(np.array([1,2,3])[None,None],pickle) # True False
# Using dill
test([1,2,3],dill) # True True    
test(np.array([1,2,3]),dill) # True True
test([[1],[2],[3]],dill) # True True
test([[1,2,3]],dill) # True True
test(np.array([1,2,3])[:,None],dill) # True False
test(np.array([1,2,3])[None,None],dill) # True False
```

**Comment by lesteve** [comment]
The reloaded array does not have the same strides as the original array, which is the source of the hash difference. In other words the reloaded array is a copy of the original array.

Possible work-arounds I can see:
* do a copy of the array before passing it to the cached function
* change the API of the cached_function to have a `slice` argument and doing the slicing inside the cached function body.

If you give us more details about what you are trying to achieve, we may be able to give better piece of advice.

**Comment by draustin** [comment]
Thanks for the information. I ended up solving my problem a different way, but your answer was very helpful. My aim was to use joblib to cache the results of a calculation that used a numpy array as its inputs (among other things). The calculation and the caching could take place in the main process or in child processes created using multiprocessing - the idea was for the multiprocessing to be transparent.
