### ISSUE TITLE
Parallel always was stuck in the end

### ISSUE THREAD

**Issue by qxde01** [joblib/joblib#518]
My parallel uses:
> sdf = Parallel(n_jobs=3, verbose=1, pre_dispatch='1.5*n_jobs')(delayed(char_etl)(x,k1,k2,k3) for x in X) 

X is a list .char_etl is a sring match function.
version : python2.7.11,centos6.7,joblib 0.11
Every time  was stuck,like this

>[Parallel(n_jobs=3)]: Done  89 tasks      | elapsed:   10.9s                    
[Parallel(n_jobs=3)]: Done 258 tasks      | elapsed:   46.8s
[Parallel(n_jobs=3)]: Done 552 tasks      | elapsed:  1.7min
[Parallel(n_jobs=3)]: Done 902 tasks      | elapsed:  2.7min
[Parallel(n_jobs=3)]: Done 997 out of 1000 | elapsed:  2.9min remaining:    0.5s

Thanks.

**Comment by lesteve** [comment]
Can you provide a stand-alone script to reproduce the problem ? Please read https://stackoverflow.com/help/mcve.

**Comment by simonzcaiman** [comment]
Try to have a try and catch in your char_etl function. This happened to me before and it was throwing out exception during the parallel loops and it didn't know what to do so it became stuck. Try to catch the exception inside your function.

**Comment by qxde01** [comment]
I have solved it ,thank you,It was my  `char_etl`'s problem.
