### ISSUE TITLE
Parallel Processing Of Two Infinite Loops

### ISSUE THREAD

**Issue by codingbond** [joblib/joblib#521]
Hi Guys,
I want to processes two infinite loop in parallel. Like One loop is appending data in numpy array or list while other loop is reading array/list and doing some processing.
I already tried SyncManager, but i found SyncManager slower for my requirement.
Any body help me with this. I am new any help/direction would be appreciated.

Here i am putting my sample code - 
```
import tempfile
import os
import pcap
import string
import sys
from joblib import load, dump, parallel, Memory
from collections import deque
import datetime
from multiprocessing import Process


def dump_Data(q_buffer, mem):
    filename = os.path.join(mem, str(datetime.datetime.now()) + 'joblib_test')
    dump(q_buffer, filename)


p = pcap.pcapObject()
dev = sys.argv[1]
p.open_live(dev, 65000, 0, 100)
p.setfilter(string.join(sys.argv[2:], ' '), 0, 0)
q_buffer = deque()

try:
    while 1:
        q_buffer.append(p.next())
        if len(q_buffer) > 1000000:
            print "write"
            mem = Memory(cachedir='/tmp/dump_data')

            # ------ Write Deque data in mmap in another parallel process without waiting of dump competition ------ #
            p_worker = Process(target=dump_Data, args=(q_buffer, mem,))
            p_worker.start()
            p_worker.join()
            q_buffer.clear()

except KeyboardInterrupt:
    print '%s' % sys.exc_type
    print 'shutting down'
    print '%d packets received, %d packets dropped, %d packets dropped by interface' % p.stats()
```

Thanx in Advance

**Comment by lesteve** [comment]
It is hard to help you from your post without doing a lot of wild guessing. Maybe you could make your use case easier to understand by posting some snippets? In particular what do you mean by infinite loops and how would you implement it using joblib ...

It is very likelly that joblib can not do what you want but I am still asking for clarification out of sheer curiosity.

**Comment by codingbond** [comment]
Thanx for reply and my example code is added.
I want to dump date in another parallel process so that while loop don't have to wait.

**Comment by lesteve** [comment]
From what I understand from your snippet I don't think joblib is useful for what you want to do. I am going to close the issue.
