### ISSUE TITLE
.pkl files stored in temp_folder take up a huge amount of disk space

### ISSUE THREAD

**Issue by alexwms** [joblib/joblib#531]
Hello,

I'm parallelizing a for loop using `joblib.Parallel()`. Each time I run my code I execute around 50,000 - 60,000 jobs in a single call to `joblib.Parallel()`. Each `.pkl` file that gets stored to temp_folder (one for each job executed) is 1.2MB. This means that the total disk space used (for all 50K+ jobs) is greater than 60GB (This is so large that I'm running out of space and getting `OSError: [Errno 28] No space left on device`). I have a few questions:

1. I am not familiar with joblib. Am I correct in thinking that each of the `.pkl` file the serialized result of each job executed? Is there any additional information stored in a `.pkl` file by joblib other than the return value of a single job?

2. Is there any way to get around using up so much memory? Perhaps there is a better way to store/serialize the result of each job. Each of my jobs return objects that are far smaller than 1.2MB. 

Thanks,
Alex

**Comment by lesteve** [comment]
From your description I gathered that memmapping is to blame. Try setting `max_nbytes` to `None` to completely disable memmapping or to a higher value e.g. `'5M'` so that your 1.2M arrays do not get memmapped.

**Comment by alexwms** [comment]
Your suggestion solved my problem. Thank You.
