### ISSUE TITLE
Parallel runs function correctly but too many times

### ISSUE THREAD

**Issue by Oedon** [joblib/joblib#532]
Hello,

I have a function `Jeffreys` (shown below) that uses an array `theta` of shape `(2,3)` (currently small for debugging) that I'm trying to parallelize. The other arrays `z`, `y`, and `s` are all of shape `(2, 2, 100)` (also for debugging). The whole function is shown below.
```
def Jeffreys(pArr):
    jArr = []
    for i, j, k in itertools.izip(z, y, s):
        h = 0.
        for l, m, n in itertools.izip(i, j, k):
            logp = lambda p: (np.sum(-0.5 * (((m - (5. * np.log10(((1. + l) * c/p[2] * (simpson((lambda l: (1./(np.sqrt(p[0]*((1.+l)**3) + (1.-p[0]-p[1])*((1.+l)**2) + p[1])))), 0., l, 100))) / (10 ** (-5)))))**2)/(n**2)) - np.log(n*np.sqrt(2.* np.pi))))
            #logp is so long because numdifftools.Hessian requires the function to be callable on one line
            h += (-numdifftools.Hessian(logp)([p[0], p[1], p[2]]))
        jeff = np.sqrt(np.linalg.det(h/(float(sets))))
        jArr.append(jeff)
    jArr = np.array(jArr) #turned into array for easier use later
    return jArr
```
I'm trying to run each row of `theta` on a separate CPU, so I use `Parallel`:
```
Parallel(n_jobs=4, verbose = 500)(delayed(Jeffreys)(p) for p in theta)
```
and this is the output:
```
Out [ ]:
Pickling array (shape=(3,), dtype=float64).
Pickling array (shape=(3,), dtype=float64).
Pickling array (shape=(2,), dtype=float64).
Pickling array (shape=(2,), dtype=float64).
[Parallel(n_jobs=4)]: Done   1 tasks      | elapsed:    7.9s
[Parallel(n_jobs=4)]: Done   2 out of   2 | elapsed:    7.9s remaining:    0.0s
[Parallel(n_jobs=4)]: Done   2 out of   2 | elapsed:    7.9s finished
Out[19]:
[array([ 49.40486933,  81.11986464]), array([ 49.40486933,  81.11986464])]
```
When I run the function in a non-parallelized way, it takes the same amount of time `(7.9 seconds)` to output one array as the `Parallel` method takes to output two of the same array, indicating to me that it is properly parallelizing the code but I'm doing something wrong in the syntax and making it run twice instead of once. Not too sure how to fix it, though any help would be appreciated. 

P.S.: also, terribly sorry if a similar question has been asked before, I don't even have a good description of my issue to search for it.

EDIT: I'm going to close this issue since apparently the two methods give different results, so i'll have to figure that out first before I tackle this.

**Comment by aabadie** [comment]
Why closing ? Could you fix your problem ?
