### ISSUE TITLE
When I create an instance of Parallel, via `p = Parallel(n_jobs=4)` and use it it does not appear to parallelize. 

### ISSUE THREAD

**Issue by DavoudTaghawiNejad** [joblib/joblib#533]
When I create an instance of Parallel, via `p = Parallel(n_jobs=4)` and use it it does not appear to parallelize. 

    Python 3.5.2 (default, Jun 27 2016, 03:10:40)
    IPython 4.2.0 -- An enhanced Interactive Python.

    In [1]: from joblib import Parallel, delayed

    In [2]: def bsqrt(x):
                 for x in range(1000):
                    x ** x
                 return x ** 2
       ...:

    In [3]: %timeit Parallel(n_jobs=4)(delayed(bsqrt)(i ** 2) for i in range(3000))
    1 loop, best of 3: 6.86 s per loop

    In [4]: p = Parallel(n_jobs=4)

    In [5]: %timeit p(delayed(bsqrt)(i ** 2) for i in range(3000))
    1 loop, best of 3: 25.6 s per loop

    In [6]: %timeit [bsqrt(i ** 2) for i in range(3000)]
    1 loop, best of 3: 25.5 s per loop

**Comment by GaelVaroquaux** [comment]
I think that what you mean is that the simple example that you are
showing is slower in parallel than non parallel. Right?

This is due to the fact that parallel has an overhead, hence it gives a
speed up only for tasks that are not extremely fast.

**Comment by lesteve** [comment]
> I think that what you mean is that the simple example that you are showing is slower in parallel than non parallel. Right?

What @DavoudTaghawiNejad is showing is that creating a `Parallel` object and calling it on two separate lines is faster than the one-liner. 

```py
Parallel(n_jobs=4)(...)
```

```py
p = Parallel(n_jobs=4)
p(...)
```

Thanks for the stand-alone snippet to reproduce the problem. This seems like a surprising behaviour indeed and it needs some investigation to understand what is going on.

**Comment by lesteve** [comment]
Actually troubleshooting a bit more, it seems like the problem happens when reusing p across multiple calls (which `%timeit` does behind the hood):

```py
import time

from joblib import Parallel, delayed


def bsqrt(x):
    for x in range(1000):
        x ** x
    return x ** 2


p = Parallel(n_jobs=4)

t0 = time.time()
Parallel(n_jobs=4)(delayed(bsqrt)(i) for i in range(100))
print(time.time() - t0)

t0 = time.time()
p(delayed(bsqrt)(i) for i in range(100))
print(time.time() - t0)

t0 = time.time()
p(delayed(bsqrt)(i) for i in range(100))
print(time.time() - t0)
```

Output:
```
0.7328484058380127
0.6334123611450195
1.4357304573059082
```

Still not sure why this is happening ...

**Comment by lesteve** [comment]
Having looked at it a bit more, my hunch is that this is related to https://github.com/joblib/joblib/issues/373. `pre_dispatch` does not use the batch size and after the first run `p._backend._effective_batch_size` is ~20 and `pre_dispatch` is not big enough so that the workers starve.

A quick fix would be to reset `p._backend.__dict__` when all the tasks are done.

Another maybe more appropriate solution would be that `pre_dispatch` takes `p.batch_size` into account if not 'auto' and `p._backend._effective_batch_size` if `p.batch_size == 'auto'`.

**Comment by lesteve** [comment]
Maybe that's something you could look at @aabadie?

**Comment by aabadie** [comment]
@lesteve, I opened #556 to try to address this issue.
