### ISSUE TITLE
Progress not being reported correctly for large numbers of tasks

### ISSUE THREAD

**Issue by chrisspen** [joblib/joblib#536]
The [documentation](https://pythonhosted.org/joblib/generated/joblib.Parallel.html) states that launched tasks with:

     r = Parallel(n_jobs=2, verbose=5)(delayed(sleep)(.1) for _ in range(10)) 

should output progress info that looks like:

    [Parallel(n_jobs=2)]: Done   1 out of  10 | elapsed:    0.1s remaining:    0.9s

However, this appears to change when the number of tasks is increased. Running:

     r = Parallel(n_jobs=2, verbose=5)(delayed(sleep)(.1) for _ in range(100)) 

now shows:

    [Parallel(n_jobs=4)]: Done  12 tasks      | elapsed:    0.4s

which does not include the total number of tasks. When this total number varies, this makes it very difficult to interpret the progress output.

How can I include the total number of tasks in the progress output for large numbers of tasks?

**Comment by lesteve** [comment]
Looks like the documentation is misleading. I don't remember exactly when the behaviour changed but because we consume an iterator the only time we know how many tasks were executed is at the end when the iterator has been fully consumed.

A PR fixing the doc would be great.

**Comment by elsander** [comment]
I'm a first time contributor-- I can make a fix for this, if no one else is working on it.
