### ISSUE TITLE
Performance tuning suggestion on method getfullargspec, which in func_inspect.py.

### ISSUE THREAD

**Issue by earoc** [joblib/joblib#546]
Hi guys, 
When using `Joblib` in a long range loop, we found that method `getfullargspec` **costs**. 
After we looked into the `Joblib`'scode, we found that as the initial of `namedtuple tuple_type` was triggered every time when method `getfullargspec` called, while it's unnecessary as the `namedtuple tuple_type` could be defined in the module rather than in the method.
Below are some simple tests on the 2 calls, using `timeit` it in the ipython.
```
In [8]: timeit tuple_type = collections.namedtuple('FullArgSpec', tuple_fields)
1000 loops, best of 3: 460 µs per loop
                      ^^^
```
```
In [9]:timeit tuple_type(args=[1232,123], varargs=(1,2,3), varkw=[123,213], defaults=(), kwonlyargs=[], kwo
...: nlydefaults=None, annotations={})
The slowest run took 5.16 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.32 µs per loop
                           ^^^
```
If move below 4 lines into the module, that would reduce the latency of the method into about `1-5µs` level, while now it's about `450µs now`.

Considering we are using `Joblib` in a big loop. There's a huge difference. And that's verified.
FYI
![1](https://user-images.githubusercontent.com/3624952/29965445-20cffd5e-8f40-11e7-9343-f26a18f4106d.png)

Thanks for your great job.

**Comment by lesteve** [comment]
What is your joblib version?

**Comment by lesteve** [comment]
Having said that I don't see any problems with your change. So if you open a PR, I will be fine with merging it.

**Comment by earoc** [comment]
@lesteve Thanks for the quick revert.  Heve open a PR already. Thanks for your advice on how to make things clear to communicate in Github.
