### ISSUE TITLE
Cache files get deleted sometimes

### ISSUE THREAD

**Issue by philippkeller** [joblib/joblib#551]
I'm trying to persist my cache objects which sometimes get deleted. Looking at the number of metadata files the number raised to about 50'000 during program execution, then I `Ctrl-C`-ed the program and started again and **after** the script started again the number of files dropped to about 30'000 and `verbose=2` showed me a lot of cache misses even though it should have been all been hits.

So there's no question that the files get deleted, my question is: why is that the case and is there a way to circumvent that?

Here's my code:

```
from joblib import Memory
memory = Memory(cachedir='.', verbose=0)

@memory.cache
def complexById(id):
    ...
```

I want to cache about 90K objects, the `joblib` directory gets about 60 MB in size and I'm running on Windows 10 on Python 3.5.2.

**Comment by lesteve** [comment]
Short answer: this is quite a surprising behaviour, this should not happen and I don't have a good explanation for it off the top of my head. If you can provide a stand-alone way of reproducing the problem I would be more than happy to look into it.

Longer answer: files can be deleted in some cases, e.g. if we detect a change in the code of the cached function, or if we detect that output.pkl has been corrupted. I don't see at all how this could explain what you are seeing though ...

**Comment by philippkeller** [comment]
thanks for the quick answer. Since my use case is fairly easy I rolled with my own implementation (~50 lines) for now, plus since I have many small objects I get better performance when pickling the whole cache (defaultdict) as a whole instead into separate files.

**Comment by lesteve** [comment]
Fair enough, if you manage to put together a stand-alone example reproducing the problem, I would be interested to see if I can reproduce because the behaviour you are seeing is rather puzzling to say the least.
