### ISSUE TITLE
Memory leak when dumping R objects

### ISSUE THREAD

**Issue by jlopezpena** [joblib/joblib#557]
This is kind of a weird issue to raise, but I thought it might be of general interest. Will cross-post it to `rpy2` repo as well, as the leak only seems to appear on the interaction between `joblib` and `rpy2`.

I have observed a memory leak when using `joblib.dump` to persist R objects created in python through `rpy2`. Here is some code that will reproduce the leak (WARNING: Running this **might** eat up your RAM):

```python
import joblib
import tempfile
import rpy2.robjects as R

def test_R_object_dump(N=1000):
    """Test creating big R matrices in a loop and dumping them to a temp file"""
    for i in range(N):
        print(i, end=", ")
        with tempfile.TemporaryFile() as f:
            a = R.r.matrix(1., 5000, 5000)
            joblib.dump(a, f)
``` 

Now, here are some weird things:

1. I observe the leak in Linux (Ubuntu 16.04), using both R 3.3.2 and 3.4.1
2. Memory use stays stable when running the code in Mac OSX
3. Running the garbage collector(s) (either the python or the R one) doesn't help.
4. Removing the `joblib.dump` line, or replacing it by R native pickling `R.r.saveRDS(a, "tempfile.RDS")` **DOES** get rid of the leak, hence the leak only appears when mixing up `rpy2` and `joblib`.

I am aware this was perhaps not the goal of `joblib`, but I found very convenient that I could persist both python and R objects using the same function call (in my company we have to deal with python and R simultaneously in a transparent way).

Amy ideas?

**Comment by lesteve** [comment]
Weird indeed, does the same happen with `pickle.dump(a, f)` rather than `joblib.dump(a, f)`?

**Comment by jlopezpena** [comment]
It does, indeed! I guess that points out at an `rpy2` issue then?

**Comment by lesteve** [comment]
Looks like a `rpy2` issue indeed unless `pickle` is to blame but I don't have a good suggestion off the top of my head how this could happen.

**Comment by jlopezpena** [comment]
I think I managed to track down the issue as an `rpy2` problem:
https://bitbucket.org/rpy2/rpy2/issues/432/memory-leak-when-pickling-r-rpy2-objects

Thanks for your help!

**Comment by lesteve** [comment]
Good stuff, thanks for following up. I have to say I was quite relieved joblib was not to blame on this one ;-).
