### ISSUE TITLE
Failure on Travis

### ISSUE THREAD

**Issue by aabadie** [joblib/joblib#560]
We have some failures that happen on Travis (not sure this is only related to Travis). A lot of tests are failing for the same reason apparently.

The issue happens today after #556 has been merged.

I created a gist containing one of the outputs: https://gist.github.com/aabadie/93996ad367e180df3b15a6e3cd61f1be

**Comment by lesteve** [comment]
I saw that and assumed this was another instance of https://github.com/tomMoral/loky/issues/101.

**Comment by lesteve** [comment]
@ogrisel any opinion on this?

**Comment by ogrisel** [comment]
That should be fixed by #561. If not, let's reopen.
