### ISSUE TITLE
Decorator

### ISSUE THREAD

**Issue by ruxandraburtica** [joblib/joblib#562]
I would like to make a contribution with a decorator that that can be used directly on functions/methods.

I don't want to reinvent if it already exists, or commit code that it's not useful, so wanted to ask if anyone else sees the value in this.

**Comment by lesteve** [comment]
I am afraid your issue is very generic and it is very hard for us to understand what it is about exactly and how it is related to joblib.

Can you post a short snippet explaining your use case and how the code looks like with using your decorator and when using your decorator?

**Comment by batflyer** [comment]
Bit of an old issue, but there's a [distributed execution framework called "ray"](https://github.com/ray-project/ray) which uses decorators as a way to mark portions of code for parallel execution.

**Comment by lesteve** [comment]
Closing this issue: it was very hard to understand the issue and there was no answer from the OP in a few months.
