### ISSUE TITLE
self sacrifice of joblib or  a homocide by pytest?

### ISSUE THREAD

**Issue by yarikoptic** [joblib/joblib#566]
Trying to troubleshoot some failing tests while running debian package build of 0.11. It is running as root... 
So decided to try current master (0.11-24-g8892839). When I run  'py.test -s -v joblib' at some point tests start to fail. I have noted that somehow pytest picks up some tests even in `__init.__.py`, so decided to run just that one and discovered that codebase is gone:

```shell
root@smaug:/tmp# git clone git://github.com/joblib/joblib
Cloning into 'joblib'...
remote: Counting objects: 6224, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6224 (delta 0), reused 0 (delta 0), pack-reused 6222
Receiving objects: 100% (6224/6224), 2.75 MiB | 18.91 MiB/s, done.
Resolving deltas: 100% (4072/4072), done.
root@smaug:/tmp# cd joblib/
root@smaug:/tmp/joblib# /usr/bin/py.test -s -v joblib/__init__.py
============================================= test session starts ==============================================
platform linux2 -- Python 2.7.14, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: .cache
rootdir: /tmp/joblib, inifile: setup.cfg
collected 1 item                                                                                                

joblib/__init__.py::joblib PASSEDTraceback (most recent call last):
  File "/usr/bin/py.test", line 11, in <module>
    load_entry_point('pytest==3.2.1', 'console_scripts', 'pytest')()
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 58, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 139, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 129, in wrap_session
    session.startdir.chdir()
  File "/usr/lib/python2.7/dist-packages/py/_path/local.py", line 565, in chdir
    py.error.checked_call(os.chdir, self.strpath)
  File "/usr/lib/python2.7/dist-packages/py/_error.py", line 85, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: chdir('/tmp/joblib',)
root@smaug:/tmp/joblib# ls
root@smaug:/tmp/joblib# apt-cache policy python-pytest
python-pytest:
  Installed: 3.2.1-2
  Candidate: 3.2.1-2
  Version table:
 *** 3.2.1-2 500
        500 http://127.0.0.1:3142/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

tested also on the local system -- the same drill.

BTW, did with `python -m trace --trace `which py.test` ....` -- nothing got removed. 
Tried on another project which uses py.test, didn't observe such an act

never saw such evil.. sure thing could be an operator error.  Just wanted to ask if anyone has a clue on what is going on?  

I just can't take it any longer, needed to share and warn ;)

**Comment by lesteve** [comment]
Hmmm never seen that before, sorry for the pain! Looking at the rootdir from your pytest output it looks like you have joblib checked out in `/tmp/joblib`, can you confirm?

I can reproduce your error if I do that:
```
rm -rf /tmp/joblib
cd /tmp/
git clone https://github.com/joblib/joblib
cd joblib
pytest joblib/__init__.py -s -v
```

The reason behind this is because there is a doctest in `joblib/__init__.py`, here is an excerpt:

```
      >>> mem = Memory(cachedir='/tmp/joblib')
      >>> import numpy as np
      >>> a = np.vander(np.arange(3)).astype(np.float)
      >>> square = mem.cache(np.square)
      >>> b = square(a)

..
    >>> import shutil ; shutil.rmtree('/tmp/joblib/')

```

So we assume that we can just create `/tmp/joblib` and delete it afterwards ... which obviously is not great if you have the joblib code checked out in `/tmp/joblib` :disappointed:

**Comment by ogrisel** [comment]
Better use the `tempfile.mkdtemp` function in that doctests. I did not do it because I wanted to keep as readable as possible but intdeed this is confusing.

**Comment by yarikoptic** [comment]
ha ha ha -- I should have grepped for the specific path -- Debian rotten soul never had guessed that someone could commit such a crime ;)  As @ogrisel commented out, it is bad practice to rely on having deterministic filenames to be created/edited/removed in /tmp.  Opens possibility for attacks etc (e.g. if evil user created `ln -s /etc /tmp/joblib` relying on the sysadmin for some reason to run this test (damn -- I just did) and pollute or do other nasty things to /etc

**Comment by ogrisel** [comment]
Would you like to submit a PR ? :)
