### ISSUE TITLE
Documentation implies Memory bytes limit will be enforced automatically

### ISSUE THREAD

**Issue by itamarst** [joblib/joblib#574]
The docs for `Memory` don't mention the need to call ``reduce_size()`` manually to make sure the cache size is enforced, in fact it's not mentioned at all: https://pythonhosted.org/joblib/memory.html. (This *is* mentioned in the changelog, but not in the reference docs which are more likely to be read.)

As a result, naive usage of `bytes_limit` will result in disk usage not being limited.

**Comment by lesteve** [comment]
That's a very good point, do you you want to open a PR?

Also if you have used `bytes_limit` + `reduce_size` and have some feed-back about it, I would be interested to hear about it.

**Comment by jebob** [comment]
Bumped into this today. Two solutions could be calling this when adding to the cache (not sure how much of a performance problem this could be) and when initialising the cache (allows the limit to be exceeded during and after runtime, but for many cases will meet the need of not having a massive cache all the time.)

**Comment by stefanv** [comment]
I just got caught by this too.

Could `reduce_size` be run every time that `.cache` is used (or, at least, have a keyword argument for `.cache` to enable that?).

**Comment by lesteve** [comment]
For now I open #1166 to improve the doc.

There was some plan a long while ago to have clever cache cleaning but it never quite materialized. IIRC the complexity had to do with:
- scenarios when the cache is being used (read or writen to) and cleaned at the same time. I think I did some tests at the time so maybe this is fine
- when and how do you launch the cleaning process? There was some idea about launching a cleaning subprocess that would survive the main process, but I don't remember how it was supposed to work exactly.

Caling `reduce_size` is time `.cache` is used seems rather costly. Some researchers around me use joblib.Memory with ~100GB joblib cache, so walking the cache and finding the oldest elements to delete will probably be a too big overhead.

Full disclosure : I very likely won't have time to work on this in the foreseeable future.
