### ISSUE TITLE
Bad Timing Results  and Bad Performance with Parallel Numpy operations

### ISSUE THREAD

**Issue by mattcbro** [joblib/joblib#575]
As a test I used joblib to test taking the inverse of many large matrices.  When parallelized the timer shows a factor of 3-4 improvement on my 6 core machine.  However the actual time to run is 14 times slower.  I don't trust the timer since any number of n_jobs from 2 to 6 shows the fake improvement.

```python
# file: tparallel.py 
import numpy as np
from numpy.random import randn
from numpy.linalg import inv
from joblib import Parallel, delayed
from joblib import load, dump
from joblib.pool import has_shareable_memory

def subjob( carr, k, N) :
    # carr, k = ctuple
    rix = np.r_[k*N:((k+1)*N)]
    cmat = carr[rix,:]
    cout = inv(cmat)
    return(cout)   


def parrun(numjobs) :
    N = 1000
    K = 10
    cm = randn(N * K, N)
    # cout = np.zeros((N*K,N),dtype=np.float64)
    with Parallel(n_jobs=numjobs) as parallel : 
        results = parallel(delayed(subjob) (cm, k, N) for k in range(K))
    return(results)
        


```
Here is the main script that is called:
```python
# file: runparallel.py

import os
import time

import numpy as np

from tparallel  import *

t = time.clock()
cmat = parrun(6)
print('%%%%%%%%%%%%%%%%%%%%%%\n')
print('finished parrun: %g s' % (time.clock()-t))

```

Now observe what happens when I call this from a bash shell.  The first call uses a single process,
cmat = parrun(1)

$ time python runparallel.py
%%%%%%%%%%%%%%%%%%%%%%

finished parrun: 7.83523 s

real	0m1.357s
user	0m5.272s
sys	0m3.088s

The python timer says 7.8s elapsed but actually only 1.4 s elapsed.   Now I run with 6 processes:
cmat = parrun(6)

$ time python runparallel.py
%%%%%%%%%%%%%%%%%%%%%%

finished parrun: 2.06145 s

real	0m18.317s
user	2m28.952s
sys	0m50.564s

Supposedly only 2 s passed but actually it took 18s,  which is 14 times longer.  Multiple runs give the same approximate results.  What's going on here?

I think I'm going to use the parallel module in cython and convert the hotspot in the code to vanilla C.  But this is a pain the arse.

**Comment by ogrisel** [comment]
If you have built numpy with an optimized BLAS like OpenBLAS or MKL (which is the case if you got numpy from pypi or anaconda), it's likely that the `inv` operation which is probably the bottleneck of your code is already multithreaded. Therefore there is no point trying to parallelize on top of that. Use your system monitor while running a naive for loop version of your code to check whether it already uses all the CPU cores of your host.

If it's not using them all, I would try to use `backend='threading'` in the `Parallel` call to skip the interprocess communication overhead (hoping that the GIL will not put too much contention on your workload).

Finally, depending on the size of your problem, it might also be the case that your workload is memory bound (not arithmetic intensive enough to fully benefit from all your CPU cores).

**Comment by mattcbro** [comment]
We are talking about fined grained vs coarse grained parallelism here.  
It is embarrassingly parallel inasmuch as each matrix inversion is 
independent of the others.  I have seen speedups for these sorts of 
operations using openmp and pure C code calling the blas libraries in 
the past,  so I know there is plenty of performance to be gained.

In general the inversions use some fined grained parallelism but not a 
lot from my use of various blas libraries.  In this case we are using 
openblas.  However what I would like to understand is why I can't get 
accurate timing information out of my python code.  Should I be using 
another tool?

Being memory bound is a potential bottleneck,  but I'm guessing that the 
order N^3 matrix inversion dominates.  This is just a toy case I created 
to approximate my real problem, which will have a lot of linear algebra 
operating on completely independent parts of memory.

What will backend=threading do if I'm still required to have the GIL 
when I do my numpy inversion operation?

**Comment by ogrisel** [comment]
I am pretty sure that numpy releases the GIL whenever it calls into BLAS or LAPACK routines.
