### ISSUE TITLE
Feature request: LZ4 compression

### ISSUE THREAD

**Issue by lsorber** [joblib/joblib#583]
Somewhat similarly to #343, it would be great to support LZ4 [1] as an optional compression engine for users who have `lz4` installed. LZ4 (de)compresses so quickly it is possible to reach faster than memcpy speeds in certain situations. Supporting Blosc [2] as a meta-compressor (which includes LZ4) might be even more interesting.

[1] https://github.com/lz4/lz4
[2] http://blosc.org/

**Comment by aabadie** [comment]
Some times ago, I started to look into integrating [Snappy](http://google.github.io/snappy/) as a fast compressor/decompressor and it was working at some point.
I think adding LZ4 could be done the same way: modifying the [BinaryZlibFile object](https://github.com/joblib/joblib/blob/master/joblib/numpy_pickle_utils.py#L272) to make it accept other compressors (that's what I did).
If I find some time, I'll look at that again.

**Comment by lesteve** [comment]
@lsorber it's not clear whether you are talking about hashing or compressed pickles. #343 is about hashing. @aabadie what you are talking about is compressed pickles. Mabye @lsorber you can add more details in order to understand your issue better.

In general a real use case where having lz4 would make your life easier would be great! Bonus points if you provide a stand-alone snippet that is representative of your use case.

**Comment by lsorber** [comment]
@lesteve This issue is really just a feature request for adding support for LZ4 compression (or Blosc). Every use case that benefits from compression could potentially benefit from a faster compressor like LZ4.

To give one example: I need to cache the output of some computationally expensive functions that have relatively complex and large output (e.g., pandas DataFrames) on S3. The time spent on storing and retrieving this data is approximately the $object size * network speed$. With compression it would be $compression time + object size / compression ratio * network speed$. LZ4 minimizes the time spent among the compressors I've tested.

**Comment by lesteve** [comment]
Do you have some code using joblib already that is slow because of this or is it more of a speculative issue ? If you already have some joblib code, have you used the existing compressing functionalities to see how much it improves the performance ?

**Comment by aabadie** [comment]
@lsorber, if you want to cache some output of computationnally expensive functions, you may be interested by [this project](https://github.com/aabadie/joblib-s3): it adds an extra storage backend to Memory, using the [s3fs](https://github.com/dask/s3fs) package from dask.
If you want to compress data, all compressors from the standard library are supported (zlib, gzip, bz2, xz, lzma) but that's true that having faster compressors might speed up compression + file transfert when working with remote storages.

I played a bit with compressors using [Snappy](https://pypi.python.org/pypi/python-snappy) and [LZ4](https://pypi.python.org/pypi/lz4) and noticed 2 things:
* the python binding from the lz4 package provide a `lz4.frame.LZ4File` that works out-of-box with joblib.dump and joblib.load functions (used internally by Memory to write/read on the cache)
* snappy has a similar interface than zlib

So I refactored a bit the way compressors are managed with dump and load. See my [branch here](https://github.com/aabadie/joblib/tree/snappy_compress). The idea is to add a `register_compressor` function (I'll rename it `register_compressor_file`) and then to have extra compression methods ('snappy', 'lz4', etc)

I also wrote a gist that compares the performances of different compression strategies. See [here](https://gist.github.com/aabadie/281c48841412a0afe6588712ef6c3bbe)

Here are the result for different datasets:
* a numpy array full of ones (10000, 10000):

|             strategy |       dump |       load |       size |
| -------------------- | ---------- | ---------- | ---------- |
|       No compression |      1.99s |      0.45s |   762.94MB |
|               Snappy |      3.30s |      3.01s |    36.00MB |
|                  LZ4 |      0.47s |      0.83s |     3.19MB |
|                 Zlib |      2.73s |      1.35s |     4.07MB |

* a `np.arange` vector of size 100000000:
|             strategy |       dump |       load |       size |
| -------------------- | ---------- | ---------- | ---------- |
|       No compression |      1.98s |      0.46s |   762.94MB |
|               Snappy |      4.86s |      4.04s |   381.80MB |
|                  LZ4 |      3.23s |      1.89s |   381.75MB |
|                 Zlib |     13.22s |      2.37s |   143.82MB |

LZ4 is indeed very fast compared to zlib but it doesn't compress that well. Same for snappy.

Using the joblib-s3 with this branch and some idea from the given gist, I think it should be possible to LZ4 compressed cache results to an S3 backend or on disk.

If people are interested I can PR my branch but there's still some work remaining on it.

**Comment by lsorber** [comment]
@aabadie Adding a `register_compressor` seems like an excellent solution. Thanks for the really detailed answer! Any chance of integrating these improvements in joblib?

**Comment by lsorber** [comment]
@lesteve Yes, joblib is slow for the use case I described above (i.e., caching large objects on S3) and could be significantly faster with a more efficient compressors. I have tested the existing compression options, but as @aabadie's experiments show, there are substantial benefits to using LZ4 (or Snappy, or Blosc) over the existing options.
