### ISSUE TITLE
Some article/technical report to cite when using joblib

### ISSUE THREAD

**Issue by thvasilo** [joblib/joblib#589]
Hello devs,

First thanks for the great library. We're using joblib for some of our work and would like to cite it, so I was wondering if there's any article or technical report we can (or submitted to [NumFOCUS JOSS](https://joss.theoj.org/about)), otherwise we'll use the github repo.

Thanks,
Theodore

**Comment by ogrisel** [comment]
I don't think so. @GaelVaroquaux do you have any suggestion? Otherwise feel free to cite the github repo URL.

**Comment by GaelVaroquaux** [comment]
No. There is no publication so far. I wanted to have a somewhat reliable
cache replacement policy before.

**Comment by joelostblom** [comment]
I would also like to cite joblib as it has helped me greatly during my work! Would you consider putting the repo on Zenodo until there is a publication? https://zenodo.org/

**Comment by joelostblom** [comment]
Or provide a simplified bibtex entry, like what Bokeh has https://bokeh.org/citation/
