### ISSUE TITLE
push to pypi

### ISSUE THREAD

**Issue by jeweinberg** [joblib/joblib#596]
This really isn't an issue, just a question. When do you plan on pushing your master branch to pypi? I had an issue with joblib not being able to pickle my functions until I pulled the most recent version from github. I would like to push this to production, but I want the environment to be replicable for future deployments.

**Comment by ogrisel** [comment]
There is a randomly failing test on travis at the moment. I would rather wait for @tomMoral to come back from vacation to backport the work we did on Python 3 concurrent.futures that should probably solve this.

**Comment by GaelVaroquaux** [comment]
Some of us are currently sprinting on joblib this week (exciting moments!). My gut feeling is that we'll get some things done and merged this week, then we'll want to wait a little bit for the dust to settle (releases right after important merges are dangerous), so we'll wait a few days, and then release an alpha, than a beta...

But the good news is that, if I understand well your message, you are a happy user of the development version. It's always good to hear. It makes us believe that it is solid :).

**Comment by lesteve** [comment]
Glad to see joblib is helpful! Closing this one.
