### ISSUE TITLE
backend="multiprocessing" - produces correct results?

### ISSUE THREAD

**Issue by xhudik** [joblib/joblib#597]
Hi there,

I thought there is almost no difference between `threading` and `multiprocessing`. If there is no GIL issue both should behave the same. However if I run the following example:
```
d={}
#this produce correct results (d={1: 1, 2: 4})
Parallel(n_jobs=-1,backend="threading" )(delayed(d.update)({i:i**2}) for i in range(1,3)) 

#this doesnt change d
Parallel(n_jobs=-1,backend="multiprocessing" )(delayed(d.update)({i:i**2}) for i in range(1,4)) 
```
Dictionary `d` is not touched when `backend="multiprocessing"`. Is it a bug or am I missing something?

thank you!

**Comment by GaelVaroquaux** [comment]
This is expected: in multiprocessing backend, the objects are not shared
between workers.

@glemaitre: I guess that's one example to add to our list of examples.

**Comment by xhudik** [comment]
yep the example and/or a simple sentence about the difference would be great!! Thanks for the fast reply. I'm closing the issue
