### ISSUE TITLE
Error whith lambda function as argument

### ISSUE THREAD

**Issue by cdancette** [joblib/joblib#600]
Hi,

My environment :  conda environment, python 3.5.4

I have the following bug : 
```python
from joblib import Parallel, delayed
a = lambda x: 2*x
def id(x):
    return x
Parallel(n_jobs=2)(delayed(id)(a) for x in range(10))
```
Which raises this error : 
```
Traceback (most recent call last):
  File "/home/cdancette/anaconda3/envs/abnet3-bis/lib/python3.5/site-packages/joblib/externals/loky/backend/queues.py", line 150, in _feed
    obj, reducers=reducers)
  File "/home/cdancette/anaconda3/envs/abnet3-bis/lib/python3.5/site-packages/joblib/externals/loky/backend/reduction.py", line 145, in dumps
    p.dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x2aaab1f990d0>: attribute lookup <lambda> on __main__ failed
```

I tried with joblib version 0.11, and with the master version, and I have an error in both cases.

I read that lambda were supposed to be supported on master, do you know how I could fix this issue ?
Thanks !

**Comment by glemaitre** [comment]
The following snippet will work:

```python
In [1]: from joblib import Parallel, delayed
   ...: a = lambda x: 2*x
   ...: Parallel(n_jobs=2)(delayed(a)(x) for x in range(10))
   ...: 
Out[1]: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

```

Lambda functions are supported as functions but cannot be passed as arguments.
Is it the use case that you have or you really want to use it as an argument?

**Comment by cdancette** [comment]
Thanks, I thought we could use them, I managed to do it otherwise (I declared my lambda functions inside the delayed function, so that i don't have to pass them as an argument).
