### ISSUE TITLE
Auto memory mapping can exceed free disk space when run in a docker container

### ISSUE THREAD

**Issue by ogrisel** [joblib/joblib#604]
Docker containers typically have a very small `/dev/shm` partition. When calling `Parallel` on large numpy objects. We should not try to memory map in `/dev/shm` if the array is larger than 90% of the free space on that partition, for instance using something like:

```python
import os
shm_stats = os.stats('/dev/shm')
use_dev_shm = data_size < (shm_stats.f_bsize * shm_stats.f_bavail) * 0.9
```

**Comment by GaelVaroquaux** [comment]
This is fixed by #609
