### ISSUE TITLE
Memory object does not have a cachedir attribute in master

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#638]
Seems like an oversight from #397. The doc says that cachedir is deprecated but actually it is not set:
https://github.com/joblib/joblib/blob/a0e1f69d2be31e9e6be1f5e346988bc04df7ff75/joblib/memory.py#L778-L783

It'd be a good idea to double-check that other similar things have not been overseen.

Snippet:
```python
from joblib import Memory

mem = Memory('/tmp/test')
print(mem.cachedir)
```

**Comment by lesteve** [comment]
> It'd be a good idea to double-check that other similar things have not been overseen.

One good sanity check (although probably not stringent enough) would be to run the scikit-learn tests using joblib master. I think this would have caught this bug.

**Comment by ogrisel** [comment]
That's a good suggestion. Let me try to do this.
