### ISSUE TITLE
FileNotFoundError on absolute path?

### ISSUE THREAD

**Issue by TMorville** [joblib/joblib#658]
#### Description
Joblib throws ``FileNotFoundError: [Errno 2] No such file or directory`` when trying to load .dat file with an absolute path, but does when using a relative path. 

#### Steps/Code to Reproduce

If I run the code below with a notebook that lives one directory up, everything works fine. 

````
from sklearn.externals import joblib
clf = joblib.load('../models/' + 'xgb.dat')
````
If I run this, 
````
clf = joblib.load('/home/tmo/projects/test/test-00-01/models/' + 'xgb.dat')
````
I get the error above. 

Running ``!ls /home/tmo/projects/test/test-00-01/models`` in the notebook returns ``xgb.dat`` showing that the files does exist, and that the absolute path is correct.

#### Versions
Linux-4.13.0-1011-azure-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
NumPy 1.14.2
SciPy 1.0.0
Scikit-Learn 0.19.1

#### Edit:
1) Added `/` in front of home
2) I have checked all dependencies on folders all the way through. Looks right.

**Comment by TMorville** [comment]
Thanks. It was a typo here, it is correct in the code.

**Comment by GaelVaroquaux** [comment]
I am sorry, I cannot reproduce. Are you sure that there is not an error
in the path that you are entering.

**Comment by TMorville** [comment]
Haven't had my morning coffee. I had a module double named, resulting in a self-reference.

**Comment by medaminefh** [comment]
Hello there, I'm facing the same issue @TMorville , how did you solve it?
