### ISSUE TITLE
Crash when passing named function as an argument

### ISSUE THREAD

**Issue by kpj** [joblib/joblib#674]
Hello,

I am using Python `3.6.5` with joblib `0.11.1.dev0` (master).

Consider the two files:
```python
# test_imp.py
def foo_imp(i):
    return i+2
```
```python
# test.py
from joblib import Parallel, delayed

def foo(i):
    return i+1
def wrap(i, func):
    return func(i)

# runs fine
from test_imp import foo_imp
res = Parallel(n_jobs=2)([delayed(wrap)(i, foo_imp) for i in range(10)])
print(res)

# crashes
res = Parallel(n_jobs=2)([delayed(wrap)(i, foo) for i in range(10)])
print(res)
```

When passing an imported function `foo_imp` as an argument, the code runs fine. For the locally defined function `foo` however, I get the following error:
```bash
Traceback (most recent call last):
  File "/python/site-packages/joblib/externals/loky/process_executor.py", line 376, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'foo' on <module 'joblib.externals.loky.backend.popen_loky_posix' from '/python/site-packages/joblib/externals/loky/backend/popen_loky_posix.py'>
```

Is this intended behavior? It might be related to #600.

**Comment by tomMoral** [comment]
We are aware of this issue and it should be resolved before the next `joblib` release.

The `foo` and `wrap` functions are not picklable by default because they live in the `__main__` module.
To make the `wrap` function picklable, we use `couldpickle`, which is able to serialize function from `__main__`. However, we only use `cloudpickle` to serialize the function argument in delayed. This is because using `cloudpickle` is slower than using the standard `pickle`.

We need to fix this by registering new reducers that for functions that are in the main and rely on `cloudpickle` only in this case.

**Comment by kpj** [comment]
I see, thanks for the response!

Has anyone already started working on this and/or is further help required?

**Comment by tomMoral** [comment]
I don't think anyone has started to work on it yet, so feel free to start a PR.

The easiest idea I had to solve this quickly would be to introspect the argument of [`BatchedCalls`](https://github.com/joblib/joblib/blob/master/joblib/parallel.py#L166) and use `dumps` to pre-serialize the functions from `__main__`. Then, the original objects need to be recovered using `loads` to recover the proper objects.
Another way to do it is to introduce a new reducer that automatically does that in the `_memmapping_reducer.py` and register it in `ArrayMemmapReducer`.

**Comment by kpj** [comment]
Modifying `BatchedCalls` does indeed seem like an easy fix.

My example from above runs with the following code changes:
```python
class BatchedCalls(object):
[..]
    def __getstate__(self):
        items = [(dumps(func), [dumps(a) for a in args],
                  {k: dumps(v)
                   for k, v in kwargs.items()})
                 for func, args, kwargs in self.items]
        return (items, self._size, self._backend)

    def __setstate__(self, state):
        items, self._size, self._backend = state
        self.items = [(loads(func), [loads(a) for a in args],
                       {k: loads(v) for k, v in kwargs.items()})
                      for func, args, kwargs in items]
```

I will move this to a PR once I figure out how to only dumps/loads arguments when needed.
Do you have a suggestion for this?

**Comment by tomMoral** [comment]
You could introspect the object using a function like
```python
def is_in_main(obj):
    mod = getattr(obj, "__module__", "")
    return "__main__" in mod
```

Be careful that you need to go a bit further to ensure that the unpickling is done properly. You could for instance wrap the objects from main in a class such as
```python
class WrapMainModuleObject:
    def __init__(self, obj):
        self.pickled_obj = dumps(obj)
    def __reduce__(self):
        return loads, (self.pickled_obj,)
```

**Comment by kpj** [comment]
Nice, my previous example works with your PR.

Let's see what others think of it.

**Comment by tomMoral** [comment]
I have pushed a fix for this issue in master. It should be faster too when issuing many short tasks.

**Comment by kpj** [comment]
Great, thanks a lot!
