### ISSUE TITLE
Parallel Any

### ISSUE THREAD

**Issue by ryanpeach** [joblib/joblib#679]
Hey, I wrote a parallelized Any function using concurrent.futures. Has such a thing been added here? I was just looking for this and your package came up. The main goal is that Any should stop early if any job completes early. Using concurrent.futures.as_completed this is possible, is it in your code?

**Comment by GaelVaroquaux** [comment]
No, it is not in joblib.

**Comment by GaelVaroquaux** [comment]
I am closing this issue, as I believe that the question has been answered. The discussion can however continue if precisions are needed.
