### ISSUE TITLE
Does joblib use swap

### ISSUE THREAD

**Issue by erikradisch** [joblib/joblib#687]
is it possible, that joblib ignores swap? If I start parallel with more jobs, then would fit into the main memory (without swap), my processes get idle one after another, which - looks to me - is connected to the fact, that my main memory is full.
Is there any possibility to force joblib to use swap-memory as well?

**Comment by ogrisel** [comment]
No but it uses shared memory from `/dev/shm` when working with large numpy arrays. In master it now checks that there are at least 2GB of free space before doing so though.

If you still get the problem, can you please try to report a minimal reproduction example?
