### ISSUE TITLE
Be robust to infinite recursively parallel

### ISSUE THREAD

**Issue by GaelVaroquaux** [joblib/joblib#688]
Currently, it is easy to freeze a machine with infinite nesting parallel:
<pre>
def very_complex_func():
    joblib.Parallel()(joblib.delayed(very_complex_func)() for i in range(30))
</pre>

We need to be robust to this, and probably test it (I have a fix in a prototyping branch).

**Comment by ogrisel** [comment]
Fixed by #700.
