### ISSUE TITLE
Using .pkl extension for joblib pickles is confusing 

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#694]
Coming from https://github.com/scikit-learn/scikit-learn/pull/11230: `.pkl` is confusing: unless there are no numpy arrays in the `joblib.dump`ed object, the file you write to can not be read with `pickle.load`.

Maybe using .jbl would be fine, better suggestions welcome!

Looking at `git grep -l '\.pkl'`, we probably want to update at least `doc/persistence.rst` and `examples/compressors_comparison.py`. Not sure about other places, we probably don't want to change `output.pkl` to `output.jbl` in Memory ...

**Comment by ogrisel** [comment]
I think I prefer `.joblib` to `.jbl` but I am fine with both.

**Comment by lesteve** [comment]
Looks like `.jbl` is already taken according to https://github.com/scikit-learn/scikit-learn/pull/11230#issuecomment-396919147, so let's go for .joblib!
