### ISSUE TITLE
Regression in 0.12: different exception type than PicklingError when arguments of Parallel can not be pickled

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#707]
Moved from https://github.com/joblib/joblib/issues/706#issuecomment-400189831. Probably because of the switch from pickle to cloudpickle.

```py
import numpy as np

import pymc3 as pm

rng = np.random.RandomState(0)
count_data = rng.randint(1, 70, 100).astype(dtype=np.float64)
n_count_data = len(count_data)

with pm.Model() as model:
    alpha = 1.0/count_data.mean()  # Recall count_data is the
                                   # variable that holds our txt counts
    lambda_1 = pm.Exponential("lambda_1", alpha)
    lambda_2 = pm.Exponential("lambda_2", alpha)
    
    tau = pm.DiscreteUniform("tau", lower=0, upper=n_count_data - 1)

with model:
    step = pm.Metropolis()
    trace = pm.sample(5, tune=10,step=step)
```

More context from https://github.com/joblib/joblib/issues/706#issuecomment-400187390:
It seems like the problem comes from the fact that  pymc3 catches `PickleError` to fall-back to single threaded mode:

```pytb
~/miniconda3/lib/python3.6/site-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    440         _print_step_hierarchy(step)
    441         try:
--> 442             trace = _mp_sample(**sample_args)
    443         except pickle.PickleError:
    444             _log.warning("Could not pickle model, sampling singlethreaded.")```
```

But now that joblib uses cloudpickle the error you get is a `TypeError`. Not 100% sure what's the best way to fix that, maybe catch all errors produced by cloudpickle.dump and reraise a PickleError?

**Comment by tomMoral** [comment]
The error in the proposed script is not from the task pickling but from the pickling of the result, in the process worker. This means that we fixed the expected Pickling issue but now the result is not pickling at the and of `pycm3.sampling._sample`. It seems to be related to some `theano` object that are shipped with the result.

I think it is a good idea to still change embed the exception in a `PicklingError` but this will not solve this issue.

**Comment by lesteve** [comment]
> The error in the proposed script is not from the task pickling but from the pickling of the result, in the process worker.

It *feels* like (just from looking at their codein the traceback above) that what pymc3 was expecting was an early failure so that they can revert to n_jobs=1 execution. This might defeat their strategy if we now fail after a computation (possibly taking some long time) has happened.

**Comment by tomMoral** [comment]
Basically, we now have less pickling errors so `joblib` will be able to schedule more tasks. However, some results can't be pickled, resulting in failures in the user code.

I don't think we can fix this in `joblib` as it highly depends on the submitted function.

**Comment by GaelVaroquaux** [comment]
> I don't think we can fix this in joblib as it highly depends on the submitted function.

Maybe we should open a discussion on the PyMC3 tracker?

**Comment by tomMoral** [comment]
Apparently, this has already been reported in pymc-devs/pymc3#3068 and the snippet provides by @lesteve is not failing on `pymc3:master` anymore.
