### ISSUE TITLE
Error in Jupyter on Mac - Attempting to do parallel computing without protecting your import

### ISSUE THREAD

**Issue by simonhughes22** [joblib/joblib#709]
On Mac High Sierra (10.13.4) and using joblib 0.11 and 0.12, in jupyter notebook and jupyter lab, I constantly run into the unprotected import error above. I cannot protect the import when in a notebook sessions AFAIK. Note that this does not happen straight away, it works fine for a while and then randomly fails. But this happens consistently, causing me to restart the kernel and lose a lot of work.

**Comment by simonhughes22** [comment]
That's going to be tough, as I mentioned it doesn't happen straight away, it takes a number of iterations before it just randomly fails.

**Comment by lesteve** [comment]
Without a way for us to reproduce, I am afraid it is going to be very though to help.

At the moment this issue does not have enough context even for us to guess what the problem could be. Could you post a snippet of code and the full stack-trace, could you put your notebook on github so we can have an idea what you are doing?

> That's going to be tough, as I mentioned it doesn't happen straight away, it takes a number of iterations before it just randomly fails.

I am not sure I follow, are you saying that the failure is not deterministic? 

Side-comment: if in your stacktrace you have `sklearn/externals/joblib` as seems to be the case of the linked hdbscan issue, you are very likely using joblib 0.11 (sklearn contains a copy of joblib which is independent of the joblib version you have installed).

**Comment by simonhughes22** [comment]
I totally understand. I will try and post more information, and some example code of when it fails. For the record this has definitely happened in joblib 0.12 also. I am not using it in sklearn, i call the Parallel and delayed functions directly. I will post a stack trace when it happens again.

**Comment by simonhughes22** [comment]
TBH this hasn't happened more than once or twice since i upgraded. It did happen once after I switched to 0.12, but i am wondering if the kernel didn't pick up the new library when it did that. So I think you can close this for now, I will create a new one if it starts happening again.

**Comment by lesteve** [comment]
Thanks for letting us know and closing the issue!
