### ISSUE TITLE
Undefined names: 'func_with_kwonly_args' and 'func_with_signature' in test_memory.py

### ISSUE THREAD

**Issue by cclauss** [joblib/joblib#711]
flake8 testing of https://github.com/joblib/joblib on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./joblib/test/test_memory.py:599:36: F821 undefined name 'func_with_kwonly_args'
        func_cached = memory.cache(func_with_kwonly_args)
                                   ^
./joblib/test/test_memory.py:620:36: F821 undefined name 'func_with_kwonly_args'
        func_cached = memory.cache(func_with_kwonly_args, ignore=['kw2'])
                                   ^
./joblib/test/test_memory.py:626:36: F821 undefined name 'func_with_signature'
        func_cached = memory.cache(func_with_signature)
                                   ^
3     F821 undefined name 'func_with_kwonly_args'
3
```

**Comment by lesteve** [comment]
Thanks for opening an issue, this is a false positive so I am going to close this one.

Here is the code, this is a bit of a hack (`exec` a string) to test a function with keyword-only arguments (Python3 only feature) without a SyntaxError on Python2:

https://github.com/joblib/joblib/blob/902869324061e380e499da7950de0fc411ae6e9f/joblib/test/test_memory.py#L588-L595
