### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by JoeXinfa** [joblib/joblib#712]
Python 3.5, Joblib 0.12, running on Linux.

```pytb
Traceback (most recent call last):
  File "/home/zhuu/code/ezcad/ezcad/gocube/tool/prop_from_gsurf.py", line 110, in apply
    NXL, NDP, DP, depthArrays, propArrays) for i in nproc)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/parallel.py", line 906, in __call__
    n_jobs = self._initialize_backend()
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/parallel.py", line 705, in _initialize_backend
    **self._backend_args)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 470, in configure
    **memmappingexecutor_args)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/executor.py", line 36, in get_memmapping_executor
    initargs=initargs)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/reusable_executor.py", line 108, in get_reusable_executor
    executor_id=executor_id, **kwargs)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/reusable_executor.py", line 144, in __init__
    initializer=initializer, initargs=initargs)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/process_executor.py", line 825, in __init__
    self._processes_management_lock = self._context.Lock()
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/backend/context.py", line 187, in Lock
    return Lock()
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/backend/synchronize.py", line 174, in __init__
    super(Lock, self).__init__(SEMAPHORE, 1, 1)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/backend/synchronize.py", line 90, in __init__
    semaphore_tracker.register(self._semlock.name)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/backend/semaphore_tracker.py", line 117, in register
    self.ensure_running()
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/backend/semaphore_tracker.py", line 96, in ensure_running
    pid = spawnv_passfds(exe, args, fds_to_pass)
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/backend/semaphore_tracker.py", line 230, in spawnv_passfds
    _pass += [_mk_inheritable(fd)]
  File "/data/data323/devl/zhuu/lib/python3.5/site-packages/joblib/externals/loky/backend/_posix_reduction.py", line 30, in _mk_inheritable
    os.set_inheritable(fd, True)
OSError: [Errno 9] Bad file descriptor
```

**Comment by lesteve** [comment]
Can you provide a stand-alone snippet to reproduce the problem ? Please read https://stackoverflow.com/help/mcve.

Readability counts, a lot! Please use triple back-quotes aka [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to format error messages code snippets. Bonus points if you use [syntax highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) with `py` for python snippets and `pytb` for tracebacks. I have edited your post, but try to remember for next time!

**Comment by lesteve** [comment]
For future reference, can you paste the output of:

```py
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import joblib; print("joblib", joblib.__version__)
```

**Comment by ogrisel** [comment]
@JoeXinfa here is a post to explain how to craft minimal bug reports:

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Without it we cannot reproduce your issue and therefore cannot help you.

**Comment by JoeXinfa** [comment]
@lesteve @lesteve I'm new to making PRs. Thank you very much for the quick response and the tutorials. When trying make the MCVE, I also get learn better where the bug comes from (kind like debugging). I think I've found the reason...

Following the trace-back, I see the 76th line (below) adds sys.stderr.fileno, which is usually 2 and no bug. But in my app, I have redirected the output stream to another widget, which modified it to -1. This -1 is what caused the error "Bad file descriptor".

File: joblib/externals/loky/backend/semaphore_tracker.py
```py
            fds_to_pass = []
            try:
                fds_to_pass.append(sys.stderr.fileno())
            except Exception:
                pass
```

Here is my MCVE. The part of XStream class comes from the linked SO post. If you don't have PyQt and cannot run my example, it is totally fine. As you can see in the code, it sets the fileno to -1.
https://stackoverflow.com/questions/24469662/how-to-redirect-logger-output-into-pyqt-text-widget

```py
import sys
from joblib import Parallel, delayed

from qtpy.QtCore import QObject, Signal
class XStream(QObject):
    """ Redirect stdout/stderr stream in PyQt """
    _stdout = None
    _stderr = None
    messageWritten = Signal(str)
    def flush( self ):
        pass
    def fileno( self ):
        return -1
        # return 1 # workaround for joblib, consequence...?
    def write( self, msg ):
        if ( not self.signalsBlocked() ):
            # self.messageWritten.emit(unicode(msg))
            self.messageWritten.emit(str(msg))
    @staticmethod
    def stdout():
        if ( not XStream._stdout ):
            XStream._stdout = XStream()
            sys.stdout = XStream._stdout
        return XStream._stdout
    @staticmethod
    def stderr():
        if ( not XStream._stderr ):
            XStream._stderr = XStream()
            sys.stderr = XStream._stderr
        return XStream._stderr

def print1(text):
    """ Restore the system default sys.stdout """
    sys.stdout = sys.__stdout__
    sys.stdout.write(text)

def print2(text):
    """ Redirect print to a Qt widget """
    pass # skip details for the sake of MCVE

print("Before redirect: sys.stderr.fileno() = ", sys.stderr.fileno())
XStream.stdout().messageWritten.connect(print1)
XStream.stderr().messageWritten.connect(print1)
print("After redirect: sys.stderr.fileno() = ", sys.stderr.fileno())

def test(i):
    print("This is thread", i)

nthread = 5
processes = range(10)
_ = Parallel(n_jobs=nthread)(delayed(test)(i) for i in processes)
```

That said, I can change XStream fileno return 1 (the default sys.stdout.fileno), I see the multi-thread prints go to my Linux terminal instead of my PyQt logger widget. On the other side, you may add a condition to skip negative fd at line 30 in joblib/externals/loky/backend/_posix_reduction.py. The idea is the same, so we circumvent the error.

Now the open question is how to make joblib aware of the stream redirection and send the multi-thread prints to the designated widget. I'd appreciate if you can provide any advice.

Lastly, the version information requested @lesteve 
```
Linux-2.6.32-696.18.7.el6.x86_64-x86_64-with-redhat-6.9-Santiago
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0]
joblib 0.12.0
```

**Comment by tomMoral** [comment]
Why do you need to implement the method `fileno`? If you just remove it, the issue will go away.

The issue is that you are not raising an error but returning an invalid fid. I am not sure this is expected when redirecting the std outputs.

**Comment by JoeXinfa** [comment]
Thanks @tomMoral. I will try modify or remove the method ```fileno```.
The issue can be closed for now. Thank you all.
