### ISSUE TITLE
v0.12: 'MemorizedResult' object has no attribute 'argument_hash'

### ISSUE THREAD

**Issue by fmaussion** [joblib/joblib#714]
I our test suite I was checking that caching occurred properly by checking that a ``MemorizedResult`` instance would have the same hash after two calls to ``call_and_shelve``.

Now the ``argument_hash`` attr is gone, and I replaced ``argument_hash`` with ``timestamp`` in our tests.

I was wondering if this is an oversight or if it was intended? I coudln't find anything in the changelog

**Comment by lesteve** [comment]
Thanks for opening an issue! This looks like an oversight from https://github.com/joblib/joblib/pull/397. IIUC `argument_hash` has been replaced by `args_id`. Maybe @aabadie remembers the context about this change.

```py
from joblib import Memory
mem = Memory('/tmp/test')
def func(x):
    return x

func_cached = mem.cache(func)
result = func_cached.call_and_shelve(1)
result
print(result)
print(result.args_id)
```

```
________________________________________________________________________________
[Memory] Calling __main__--tmp-test.func...
func(1)
_____________________________________________________________func - 0.0s, 0.0min
MemorizedResult(location="/tmp/test/joblib", func="<function func at 0x7ff0edb6e6a8>", argument_hash="d3ffa92536e9b2aeb96c6d0e11ccd857")
d3ffa92536e9b2aeb96c6d0e11ccd857
```

Not sure what we want to do about this one:
* we add back argument_hash possibly as a deprecated property
* we leave it like this (my guess is that not so many people are using `MemorizedResult` directly ...) but we should at the very least change the `MemorizedResult.__repr__` to use `args_id=`

**Comment by aabadie** [comment]
`args_id` was used as a semantic way to retrieve a processing result from an identifier. In the current design the identifier is built using the hash of the argument, but this can change depending on the store backend (database unique key, etc).

I opened #716 following @lesteve suggestions above to fix this issue.

**Comment by fmaussion** [comment]
Thanks all!
