### ISSUE TITLE
readthedocs still documents joblib 0.11

### ISSUE THREAD

**Issue by mhooreman** [joblib/joblib#724]
Hello,

https://pythonhosted.org/joblib/index.html still documents joblib 0.11

This is disturbing, especially because there are some "big" changes on 0.12 (backend, etc.), and the 0.12 switch already happened (at least with anoconda).

Thanks.

**Comment by GaelVaroquaux** [comment]
> https://pythonhosted.org/joblib/index.html still documents joblib 0.11

Yes. We moved to readthedocs, but did not update the links or kill the
pythonhosted site.

**Comment by GaelVaroquaux** [comment]
> > https://pythonhosted.org/joblib/index.html still documents joblib 0.11

> Yes. We moved to readthedocs, but did not update the links or kill the
> pythonhosted site.

Hum, it's more complicated than that: we tried moving to readthedocs, but
it failed because readthedocs cannot build our docs
https://readthedocs.org/projects/joblib/builds://readthedocs.org/projects/joblib/builds/

**Comment by mhooreman** [comment]
Thanks Gael

Le mer. 25 juil. 2018 14:11, Gael Varoquaux <notifications@github.com> a
écrit :
