### ISSUE TITLE
FileSystemStoreBackend.__repr__ should not return a string

### ISSUE THREAD

**Issue by lesteve** [joblib/joblib#764]
Something that tripped me up when working on https://github.com/joblib/joblib/pull/746, is that `FileSystemStoreBackend.__repr__` makes it look like a string. I could not find a good reason for this. Do you remember something about this @aabadie?

Here is a snippet to show what I mean:
```
In [1]: from joblib import Memory

In [2]: mem = Memory('/tmp/test')

In [3]: mem.store_backend
Out[3]: /tmp/test/joblib
```

When I was debugging I lost at least one hour until I thought of doing `type(mem.store_backend)` ...

Also slightly less important but:
```py
from joblib._store_backends import FileSystemStoreBackend
backend = FileSystemStoreBackend()
backend  # Exception in __repr__ AttributeError: 'FileSystemStoreBackend' object has no attribute 'location'
```

**Comment by aabadie** [comment]
> Do you remember something about this @aabadie?

That was some time ago... so not really. This is certainly something that I didn't take care of unfortunately.

I tested a bit locally and adapted slightly to have something more common. I'll push a PR soon.

**Comment by aabadie** [comment]
@lesteve, see #765
