### ISSUE TITLE
Fonts in Joblib logo are not rendered correctly on non Linux systems

### ISSUE THREAD

**Issue by aabadie** [joblib/joblib#770]
If one browse the documentation on readthedocs from a system other than Linux (and maybe other than Ubuntu), the fonts used for "Joblib" in the Logo is not correct. I noticed this problem on Windows and Mac OS.

In fact, the logo looks like this:

![joblib_logo](https://user-images.githubusercontent.com/1375137/45052272-9fecc280-b086-11e8-9680-7cc38a34cc9f.png)

Joblib is written using the default font and not the Ubuntu Mono that is defined in the SVG. There's also a spacing issue between `Job` and `lib`. This is because the Ubuntu Mono font is not available on non Linux/Ubuntu systems and the browser don't know how to correctly display the text.
This can be fixed by at least 2 ways:
- embed the Ubuntu Mono font within the SVG, normally Inkscape is able to do that
- instead of using a text element with a specific font, convert it to a vector path. I think this can also be done with Inkscape

**Comment by GaelVaroquaux** [comment]
Third option: in the corresponding CSS, use a list of font, instead of a
single font name: the first available is used. It's then a question of
finding the right ones that have the correct look.

**Comment by aabadie** [comment]
Ok, #772 was merged a bit fast. I just checked on windows and it doesn't work. Well in fact, displaying the SVG directly in the browser works but within and the html page, the fonts are not fetched.
