### ISSUE TITLE
loky backend errant print statements

### ISSUE THREAD

**Issue by ibackus** [joblib/joblib#776]
I recently upgraded joblib v0.12.4 and started using the loky backend.  Unfortunately, when running a `Parallel` loop, I get a bunch of errant print statements that I cannot for the life of me track down.  The statements vanish when I switch back to using the multiprocessing backend.

I run the code with something like:
```python
results = Parallel(4, mmap_mode='r+', verbose=0)(
    delayed(function)(a, b, c) for a, b, c in stuff)
```

The print statements look like:
```
85827584
81047552
80310272
86327296
111181824
88104960
83111936
86261760
86261760
88330240
111181824
83857408
83857408
111050752
88903680
86261760
```

Any ideas?

**Comment by tomMoral** [comment]
The line responsible for this debug print is indeed in `loky`:
`joblib/externals/loky/process_executor.py:441:     print(mem_usage)`

Thanks for reporting this.
