### ISSUE TITLE
How to avoid multiple non-thread safe code execution on module re-imports inside Parallel

### ISSUE THREAD

**Issue by StrikerRUS** [joblib/joblib#780]
The following error(s) started to appear after updating `scikit-learn` to 0.20 and in consequence `joblib` to 0.12:
```
================================== FAILURES ===================================
_________________________ TestExamples.test_examples __________________________
sklearn.externals.joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\externals\loky\process_executor.py", line 420, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 563, in __call__
    return self.func(*args, **kwargs)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py", line 261, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 242, in fit_ovr_binary
    return binary_clf.fit(X, y, sample_weight)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 306, in fit
    self._execute_command(cmd)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 267, in _execute_command
    universal_newlines=True).communicate()
  File "C:\Miniconda36-x64\envs\test-environment\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Miniconda36-x64\envs\test-environment\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""
The above exception was the direct cause of the following exception:
self = <test_examples.TestExamples testMethod=test_examples>
    def test_examples(self):
        for filename in find_files(os.path.join(os.path.abspath(os.path.dirname(__file__)), os.path.pardir, 'examples')):
>           exec(open(filename).read(), globals())
tests\test_examples.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<string>:16: in <module>
    ???
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py:502: in fit
    self._fit_multiclass_task(X, y, sample_weight, params)
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\rgf_model.py:377: in _fit_multiclass_task
    for i in range(self._n_classes))
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py:996: in __call__
    self.retrieve()
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py:899: in retrieve
    self._output.extend(job.get(timeout=self.timeout))
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py:517: in wrap_future_result
    return future.result(timeout=timeout)
C:\Miniconda36-x64\envs\test-environment\lib\concurrent\futures\_base.py:432: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <Future at 0x5ae8519630 state=finished raised FileNotFoundError>
    def __get_result(self):
        if self._exception:
>           raise self._exception
E           FileNotFoundError: [WinError 2] The system cannot find the file specified
C:\Miniconda36-x64\envs\test-environment\lib\concurrent\futures\_base.py:384: FileNotFoundError
______________________ TestRGFClassfier.test_attributes _______________________
sklearn.externals.joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\externals\loky\process_executor.py", line 420, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 563, in __call__
    return self.func(*args, **kwargs)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py", line 261, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 242, in fit_ovr_binary
    return binary_clf.fit(X, y, sample_weight)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 306, in fit
    self._execute_command(cmd)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 267, in _execute_command
    universal_newlines=True).communicate()
  File "C:\Miniconda36-x64\envs\test-environment\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Miniconda36-x64\envs\test-environment\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""
The above exception was the direct cause of the following exception:
self = <test_rgf_python.TestRGFClassfier testMethod=test_attributes>
    def test_attributes(self):
        clf = self.classifier_class(**self.kwargs)
        attributes = ('estimators_', 'classes_', 'n_classes_', 'n_features_', 'fitted_',
                      'sl2_', 'min_samples_leaf_', 'n_iter_')
    
        for attr in attributes:
            self.assertRaises(NotFittedError, getattr, clf, attr)
>       clf.fit(self.X_train, self.y_train)
tests\test_rgf_python.py:256: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py:502: in fit
    self._fit_multiclass_task(X, y, sample_weight, params)
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\rgf_model.py:377: in _fit_multiclass_task
    for i in range(self._n_classes))
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py:996: in __call__
    self.retrieve()
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py:899: in retrieve
    self._output.extend(job.get(timeout=self.timeout))
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py:517: in wrap_future_result
    return future.result(timeout=timeout)
C:\Miniconda36-x64\envs\test-environment\lib\concurrent\futures\_base.py:432: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <Future at 0x5ae86fe320 state=finished raised FileNotFoundError>
    def __get_result(self):
        if self._exception:
>           raise self._exception
E           FileNotFoundError: [WinError 2] The system cannot find the file specified
C:\Miniconda36-x64\envs\test-environment\lib\concurrent\futures\_base.py:384: FileNotFoundError
---------------------------- Captured stderr call -----------------------------
ERROR: The process with PID 2448 (child process of PID 1612) could not be terminated.
Reason: The operation attempted is not supported.
```

I use Parallel to communicate with executable file which uses OpenMP:

https://github.com/RGF-team/rgf/blob/a7c0a5b5b51d26eac689650194867a33ad640c47/python-package/rgf/rgf_model.py#L373-L377
https://github.com/RGF-team/rgf/blob/a7c0a5b5b51d26eac689650194867a33ad640c47/python-package/rgf/utils.py#L263-L267

Failures are random: roughly 1 failure for 3 runs. It can be illustrated by the following picture (it's 8 re-builds of the same commit):

![image](https://user-images.githubusercontent.com/25141164/46248600-049c0280-c424-11e8-81a4-f2a104b9227d.png)

Error is presented **only** on x64 Windows with Python 3.7. x86 Windows, Linux, macOS are bug-free. The error doesn't appear at Python 2.7, 3.4-3.6 too.

After facing this error I've tried to run scikit-learn with joblib from PyPI via `set SKLEARN_SITE_JOBLIB=true` (version 0.12.0 - 0.12.5) - no luck.

Old stable joblib 0.11 cannot be used with the newest scikit-learn due to the following error in RandomForestRegressor:
```
            # Parallel loop: we prefer the threading backend as the Cython code
            # for fitting the trees is internally releasing the Python GIL
            # making threading more efficient than multiprocessing in
            # that case. However, we respect any parallel_backend contexts set
            # at a higher level, since correctness does not rely on using
            # threads.
            trees = Parallel(n_jobs=self.n_jobs, verbose=self.verbose,
>                            prefer="threads")(
                delayed(_parallel_build_trees)(
                    t, self, X, y, sample_weight, i, len(trees),
                    verbose=self.verbose, class_weight=self.class_weight)
                for i, t in enumerate(trees))
E           TypeError: __init__() got an unexpected keyword argument 'prefer'
C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\ensemble\forest.py:331: TypeError
```

**Comment by ogrisel** [comment]
Thanks for your report. Can you please try to reproduce only with joblib and a minimal python function that does not depend on the rgf package?

BTW, what is this rgf package? Do you have an idea which file it's trying to open?


The suspicious lines from the traceback are executed in the worker process::

```python-traceback
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\sklearn\externals\joblib\parallel.py", line 261, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 242, in fit_ovr_binary
    return binary_clf.fit(X, y, sample_weight)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 306, in fit
    self._execute_command(cmd)
  File "C:\Miniconda36-x64\envs\test-environment\lib\site-packages\rgf\utils.py", line 267, in _execute_command
    universal_newlines=True).communicate()
```

But we need a minimal reproduction case in order for us to be able to help you.

**Comment by ogrisel** [comment]
Maybe you could try to print the command, its filepath, the current working directory, the content of the PATH environment variable and such to try to understand what's causing the problem?

**Comment by StrikerRUS** [comment]
Thank you very much for the prompt response!

rgf is a Python wrapper for Regularized Greedy Forest C++ implementations. Here is the original issue: https://github.com/RGF-team/rgf/pull/251 .

I suppose that the only file which cannot be found is rgf.exe with which Python code tries to communicate:
>I use Parallel to communicate with executable file which uses OpenMP.

The code of the Parallel communication logic encapsulated here:
https://github.com/RGF-team/rgf/blob/a7c0a5b5b51d26eac689650194867a33ad640c47/python-package/rgf/rgf_model.py#L373-L377
https://github.com/RGF-team/rgf/blob/a7c0a5b5b51d26eac689650194867a33ad640c47/python-package/rgf/utils.py#L263-L267

I'll try to create minimal reproducible example. Please give me some time for this.

**Comment by StrikerRUS** [comment]
Hi @ogrisel !
I'm so sorry about the delay!

All this time I've tried to reproduce the issue. At first, issue disappeared at all, but then started to occur not only on Windows x64 with Python 3.7, but on x86 and with Python 2.7, 3.4, 3.5, 3.6.

However, it seems to be that today I found the root of the problem.

Here is the setup.
Let say we have a package called `joblib_issue` with 3 `.py` files in it.
- `foo.py`
- `bar.py`
- `baz.py`
### foo.py:
```
from sklearn.externals.joblib import Parallel, delayed

from joblib_issue.baz import test_command
from joblib_issue.bar import SomeClass

def run_test():
    classes = [SomeClass(i) for i in ['a', 'b', 'c']]
    classes = Parallel(n_jobs=-1)(delayed(test_command)(classes[i]) for i in range(len(classes)))
```

### bar.py:
```
def init():
    print('Not thread-safe function which should be executed once at the module startup!')
    return r'C:\exe_file.exe'

SOME_CONSTANT = init()  # This constant is a path on which joblib argues

class SomeClass(object):
    def __init__(self, some_arg):
        self.some_field = some_arg
```

### baz.py:
```
def test_command(cls):
    print(cls.some_field)
    return cls
```

And a file to test this `test.py`:
```
from joblib_issue.foo import run_test

if __name__ == "__main__":
    run_test()
```

You can find these files in this repo: https://github.com/StrikerRUS/joblib-issue.

And I get the following output with scikit-learn 0.20:
```
$ python test.py
>>> Not thread-safe function which should be executed once at the module startup!
>>> Not thread-safe function which should be executed once at the module startup!
>>> a
>>> Not thread-safe function which should be executed once at the module startup!
>>> b
>>> c
```

I have no idea why there was no such problem with previous scikit-learn versions...
It seems to me that it imports `bar.py` module multiple times which is inadmissible is my case. Is there any approach to avoid this? 

Thanks in advance!

**Comment by tomMoral** [comment]
Thanks a lot for investigating this!

Your issue results from the fact that we are not relying on `fork` to start our processes anymore. Using `fork` means that all previously loaded modules do not need to be reloaded in the workers, so `init` is not called multiple times. In `0.12`, we need to import the modules in each of the worker, causing your `init` function to be called multiple times.

A quick fix would be to add a `with parallel_backend("multiprocessing"):` in your `main` script to rely on the `multiprocessing` backend which still relies on `fork`.

Note that you should avoid having side-effects on module impor in general. It makes it complicated to serialize the object from this module and you can have weird behavior if it is used with `reloading` options.

**Comment by StrikerRUS** [comment]
@tomMoral Many thanks for the detailed explanation and the proposed quick fix!

Unfortunately, I need to detect the path of the exe file and check whether it's corrupted or not every time the package is imported, which is
- not thread safe at present (but can be reworked)
- rather time consuming (cannot be reworked).

Am I right, that the place (module) where the startup logic is placed doesn't matter, because the constant set during executing startup logic is used in parallel task, and it will not help to prevent multiple module imports?

Can you please give any advice how to import the module only once with the latest joblib and any backend?

**Comment by tomMoral** [comment]
When using multiprocessing, each worker has its own interpreter. That means that all modules you use need to be imported in the new interpreter, thus the constant `SOME_CONSTANT` will be set once for each worker, if you don't rely on `fork` to start processes (this does not happen with `fork` because you duplicate the interpreter, thus modules that are already imported don't need to be re-imported). 

This is hard to come up with ways to mitigate this without having the actual code. You could try to avoid relying on a global variable (as it does not appear to be a global constant) but compute this at startup time in `test.py` and pass that as an argument of the calls which need it.

Another solution would be to put the path in `SomeClass` class, as a class variable. That way, it would not need to be re-computed as it would be serialized with your object. For instance, in your example, you could modify `bar.py` such that

```python
def init():
    print('Not thread-safe function which should be executed once at the module startup!')
    return r'C:\exe_file.exe'


class SomeClass(object):
    cst = None
    def __init__(self, some_arg):
        self.some_field = some_arg
        self._init()

    @classmethod
    def _init(cls):
        if cls.cst is None:
            cls.cst = init()
```

This gives the following output:

```
$ python test.py 
Not thread-safe function which should be executed once at the module startup!
a
b
c
```

**Comment by ogrisel** [comment]
@tomMoral this issue is about windows and speaking about "fork" is confusion: on windows fork is not used at all, it's the spawn method with the "init main" flag set to true. Loky is like the windows spawn method but without the init main flag.

The rest of the analysis about the startup logic being or not being executing still holds though.

**Comment by tomMoral** [comment]
> this issue is about windows and speaking about "fork" is causing confusion

Sorry about the confusion, I did not realize it was on windows. Indeed, in this case, using the `multiprocessing` backend won't solve your problem.

**Comment by StrikerRUS** [comment]
Thank you, guys, for all your help! Really appreciate it!

**Comment by StrikerRUS** [comment]
@tomMoral Sorry for disturbing, but your proposed hotfix with class variable doesn't seem to be working...

I've simply added printing my constant in `baz.py`:
```diff
--- a/joblib_issue/baz.py
+++ b/joblib_issue/baz.py
@@ -1,3 +1,4 @@
 def test_command(cls):
     print(cls.some_field)
+    print(cls.cst)
     return cls
```

Everything OK with `Parallel(n_jobs=1)...`:
```
$ python test.py
Not thread-safe function which should be executed once at the module startup!
a
C:\exe_file.exe
b
C:\exe_file.exe
c
C:\exe_file.exe
```
But with `Parallel(n_jobs=-1)...` the constant is unset:
```
$ python test.py
Not thread-safe function which should be executed once at the module startup!
b
None
a
None
c
None
```

**Comment by StrikerRUS** [comment]
@tomMoral Is [this behavior](https://github.com/joblib/joblib/issues/780#issuecomment-430448941) expected?

**Comment by tomMoral** [comment]
Yes it is the expected behavior... Sorry it misses some part.
Actually the correct implementation to mitigate the problem would be:

```python
# File bar.py
    print('Not thread-safe function which should be executed once at the module startup!')
    return r'C:\exe_file.exe'


class SomeClass(object):
    cst = None
    def __init__(self, some_arg):
        self.some_field = some_arg
        self.cst = self._init()

    @classmethod
    def _init(cls):
        if cls.cst is None:
            cls.cst = init()
        return cls.cst
```

The pickling will not serialize the class constant. So the best way to send it is to set an instance field to hold `cst`. That way, the constant is sent to the workers without recomputations.

Let me know if this solves your use case @StrikerRUS

**Comment by StrikerRUS** [comment]
@tomMoral Many thanks for your help and time!

> The pickling will not serialize the class constant.

Oh, now everything is clear for me! But may I ask, why it is so?

> Let me know if this solves your use case @StrikerRUS

Practically.... The last step is to make `SomeClass` compatible with scikit-learn estimator interface.
I mean, I cannot set instance constant in the `__init__()` method due to [this check](https://github.com/scikit-learn/scikit-learn/blob/d88bef17eaa9d81e152c8b914fad7cf45f5e8393/sklearn/utils/estimator_checks.py#L1965-L1995). So, I've tried to move this logic to the `fit()` method, but it doesn't work with `GridSearchCV` - multiple calls of `"Not thread-safe function"` happen again.

**Comment by tomMoral** [comment]
> Oh, now everything is clear for me! But may I ask, why it is so?

When pickling an instance of a class which can be imported, `pickle` does not pickle the exact object but just a reference to the module containing this object. Thus the object is re-created starting from its definition and the class constant is just taken from its definition, _i.e._ set to `None`.

> I mean, I cannot set instance constant in the __init__() method due to this check.

I did not know of this check.. Maybe, a way I see to solve this is to implement a [`__getstate__`and `__setstate__` method](https://docs.python.org/3/library/pickle.html#object.__getstate__) for your estimator and use them to set a global constant in your module:

```python
# file bar.py
cst = None

def init():
    print('Not thread-safe function which should be executed once at the module startup!')
    return r'C:\exe_file.exe'


class SomeClass(object):
    def __init__(self, some_arg):
        self.some_field = some_arg
        self._init()

    @classmethod
    def _init(cls):
        global cst
        if cst is None:
            cst = init()

    def print_cst(self):
        print(cst)

    def __getstate__(self):
        return (self.some_field, cst,)

    def __setstate__(self, state):
        global cst
        self.some_field, cst = state

# File baz.py

def test_command(cls):
    cls.print_cst()
    print(cls.some_field)
    return cls

```

What do you think for your usage?

**Comment by StrikerRUS** [comment]
> I did not know of this check..

Yeah, it's new check presented only in `0.20` version.

> What do you think for your usage?

Locally on my machine your proposal works like a charm! Thanks a lot for this! To be honest, I think that I would never have thought about preserving module constant in object instance.

Let me run several rounds of CI tests and get back here with final results.

In addition, can you please correct me if I'm mistaken in the following? Starting from `scikit-learn 0.20` (`joblib 0.12`), thanks to `loky`, it's safe to run any **OpenMP** program inside **GridSearchCV** with `n_jobs=-1`.

**Comment by ogrisel** [comment]
Also note that if you set `OMP_NUM_THREADS` explicitly to some other value, joblib will not override this and instead propagate that to the worker processes.

**Comment by GaelVaroquaux** [comment]
> Also note that if you set OMP_NUM_THREADS explicitly to some other value, joblib will not override this and instead propagate that to the worker processes.

Naive question: do we have a good documentation section about this? (my
apologies for not checking).

**Comment by StrikerRUS** [comment]
Thanks a lot to all participants, especially to @tomMoral !
I've run tests on CIs multiple times and the proposed fix solves the original problem.

I suppose that this issue can be closed now (and probably renamed with the aim to help other users find very useful information about module variables pickling).
