### ISSUE TITLE
Large memory growth with parallel on numpy arrays.

### ISSUE THREAD

**Issue by jason-neal** [joblib/joblib#781]
I do not know if this is similar to related to the other memory leak issues posted. 

I am trying to run a convolutions of several stellar which are 1d arrays of length ~100000.
In the parallel case I am getting a memory leak in which the used memory grows to full the system memory (24GB in about half a day).

I have tried multiple experiments but I am no further ahead on the issue after several days. 

Example code in which I see the effect  is below. (although I have not tried running this out to 24GB)

```
from joblib import Parallel, delayed, load, dump
import gc
import os
import numpy as np
import shutil

def func(x,y, xi):
        # complicated function
        yy =  np.sum(y) + xi
        return yy
                                                                                                                         
if __name__ == "__main__":
      cores = 6
      npix = 50000  # large 1d numpy array.
      x_ = 2 + (1/npix) * np.arange(npix)
      y_ = np.random.randn(npix-10)
      x2_ = x_[10:-10]  # shorter than x/y    

      folder = "./memmap_dir/"
      for ii in range(2000):    
          # x and y change in each iteration
          # x, y   = x_ + ii, y_+ii
          # trying memmapping
          x_filename_memmap = os.path.join(folder, 'data_memmap_x')
          dump(x_+ii, x_filename_memmap)
          x = load(x_filename_memmap, mmap_mode='r')
          y_filename_memmap = os.path.join(folder, 'data_memmap_y')
          dump(y_+ii, y_filename_memmap)
          y = load(y_filename_memmap, mmap_mode='r')
        
          with Parallel(n_jobs=cores) as parallel:
              result =  parallel(delayed(func)(x, y, xi) for xi in x2_)
          
          gc.collect()


      shutil.rmtree(folder, ignore_errors=True)

```
As you can see I have tried adding memmapping, and gc.collect() but I still get memory growth up to GBs (before I kill it).

Versions:
joblib                    0.12.5
python                  3.6.5
numpy                  1.15.0

Am I missing something here?  It does not occur when num_procs=1

**Comment by jason-neal** [comment]
Here is a simplified version that does the same memory growth.
```
from joblib import Parallel, delayed
import os
import numpy as np

def func(y, xi):
        # complicated numpy using function
        return np.sum(y) + xi
                                                                                                                         
if __name__ == "__main__":
      cores = os.cpu_count()
      # cores = 1
      npix = 100000  # large 1d-numpy array.
      x_ = np.arange(npix-100) # x shorter than y    
      y_ = np.random.randn(npix-10)
      
      for ii in range(2000):    
          print(ii)
          y = y_ + ii
 
          with Parallel(n_jobs=cores) as parallel:
              result = parallel(delayed(func)(y, xi) for xi in x_)
```

Eventually it gives a memory leak error.

```
/home/jneal/anaconda3/envs/eniric/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py:700: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
```

![memleak](https://user-images.githubusercontent.com/10076879/46418534-e257fc80-c723-11e8-9e45-e4de31e4cc77.png)

**Comment by ogrisel** [comment]
Thanks for the report.  I have simplified it further to:

```python
from joblib import Parallel, delayed
import numpy as np
import psutil
import gc


def func(y, xi):
    return np.sum(y) + xi


if __name__ == "__main__":
    n = 100000
    y = np.random.randn(n)
    x = np.arange(n)
    print("y size: %0.3f MB" % (y.nbytes / 1e6))

    for i in range(2000):
        gc.collect()
        print("Iteration %d: %0.3f MB" % (
            i, psutil.Process().memory_info().rss / 1e6))

        Parallel(n_jobs=2)(delayed(func)(y, xi) for xi in x)
```

and I get:

```
y size: 0.800 MB
Iteration 0: 31.986 MB
Iteration 1: 66.511 MB
Iteration 2: 94.368 MB
Iteration 3: 118.743 MB
Iteration 4: 141.640 MB
Iteration 5: 175.591 MB
Iteration 6: 184.300 MB
Iteration 7: 206.828 MB
Iteration 8: 225.526 MB
```

A few remarks:

- for such small input data `y`, there is no memmapping in /dev/shm (I checked), so this is not the culprit;
- here I report the memory in the main process: the leak is not in the worker processes;
- I tried with the multiprocessing backend of joblib master and joblib 0.11 and I reproduce the issue: loky is not the culprit;
- setting n_jobs=1 or using the threading backend makes the problem disappear;
- if we remove the iteration of `for xi in x` and replace it by `for xi in range(n)`, the problem (almost) disappears: this has to do with an interaction between numpy iteration and joblib apparently...

**Comment by ogrisel** [comment]
I think we might need to debug with https://mg.pov.lt/objgraph/ to find the cause of the leak (assuming it's a reference leak). @gpierreglaser feel free to chip in :)

**Comment by pierreglaser** [comment]
@ogrisel taking this over, will give an update ASAP!

**Comment by pierreglaser** [comment]
Hey @jason-neal, while trying to find a minimal example from the bug you filed, it turns out that this bug can be replicated without `joblib`, using only `numpy` and a `concurrent.futures.ProcessPoolExecutor` instance. I opened a bug report on `numpy`, you can find it [here](https://github.com/numpy/numpy/issues/12122).

We are keeping this opened because although the bug does not involves `joblib`, it still affects the users. 

Thanks, 

Pierre

**Comment by jason-neal** [comment]
Thanks @pierreglaser, no wonder I could not find a simple solution.

**Comment by pierreglaser** [comment]
@jason-neal the [fix](https://github.com/numpy/numpy/pull/12249/files) is merged into numpy master.

**Comment by jason-neal** [comment]
Thanks! That seems to fix the problem.

**Comment by Firestar-Reimu** [comment]
I face the same problem, I have 480000 spectrums to baseline-stripping

and my code is like this:

```
from pybaselines import Baseline
from joblib import Parallel, delayed
from functools import partial

data = np.random(6000, 600, 800)  # random cube with 6000*600*800, only about 10GB large
velocities = np.arange(0,6000)

baseline_fitter = Baseline(x_data=velocities)
dataset = data.transpose(1, 2, 0).reshape(n_y * n_x, n_v)
baselines = np.empty_like(dataset)
partial_func = partial(baseline_fitter.arpls, lam=1e8)


results = Parallel(n_jobs=-1, backend="loky")(delayed(partial_func)(dataset[i]) for i in trange(len(dataset)))


for i, (baseline, params) in enumerate(results):
    baselines[i] = baseline
```

If I use backend=loky, the code is done in 90 seconds, while the used memory rockets to ~60GB

I have just 64GB of RAM and I cannot do anything beyond that, vscode will crash if I run more code

If I use backend=threading, the code is done in 20 minutes, but the used memory will eventually rise to ~60GB

I want to collect these memory into the OS

**Comment by tomMoral** [comment]
Hello,

This issue was closed more than 6 years ago, so please open a new issue with a standalone reproducer if possible  (without `pybaseline`).
From your description, it does not seem like an issue with `joblib`, as both code leads to the same memory consumption, but more the fact that the created data is very large.

To reduce this memory, you could  use `return_as='generator'` to try to reduce the data as it is computed (see [here](https://joblib.readthedocs.io/en/stable/auto_examples/parallel_generator.html#sphx-glr-auto-examples-parallel-generator-py) for an example).
