### ISSUE TITLE
Backporting n_jobs=None to joblib 0.11.1

### ISSUE THREAD

**Issue by rth** [joblib/joblib#786]
As mentioned by @ogrisel on Gitter (regarding using joblib <0.12 with latest scikit-learn),

> The problem is that we cannot easily revert back to to 0.11 unfortunately: the use n_jobs=None change prevents that. We could issue a joblib 0.11.1 release for which n_jobs=None would be accepted an treated as n_jobs=1.

If it is possible to make such a release, I think it would be very useful.

Currently, scikit-learn 0.20, can only work with joblib 0.12 that also uses loky as the default back-end. For any issue, that affects loky, it means that that scikit-learn users need to wait for the issue to be fixed upstream. I don't doubt that most issues (if any are discovered) will be resolved, however I think it's also important to give users a quick workaround if needed, in any case. 

For Linux distributions that package scikit-learn and joblib separately I think it also doesn't hurt to have a larger range of compatible versions.

Another use case for this is that I am currently working on packaging joblib for [Pyodide](https://github.com/iodide-project/pyodide/), and I wanted to start with joblib 0.11 as that the WebAssembly environment doesn't support creating threads/processes yet, so all the additions in the vendored loky in that context mean just more possibilities to fail by calling unsupported parts of the stdlib. And as mentioned earlier that version of joblib doesn't work with scikit-learn 0.20...

This would be very much appreciated.

**Comment by rth** [comment]
Nevermind, `n_jobs=None` appears to work with joblib 0.11 already,
```py
In [1]: import numpy as np                                                                                                                                   
In [2]: import joblib                                                                                                                                        

In [3]: joblib.Parallel(n_jobs=None)(joblib.delayed(np.sqrt)(i ** 2) for i in range(10))                                                                     
Out[3]: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]                                                                                                                                              

In [4]: backend = joblib.Parallel(n_jobs=None)                                                                                                               

In [5]: backend._initialize_backend()                                                                                                                        
Out[5]: 1  # returns n_jobs
```

**Comment by GaelVaroquaux** [comment]
@ogrisel used his time machine to forsee your issues and fix them in the
past.

**Comment by rth** [comment]
I don't doubt it :)
