### ISSUE TITLE
Numpy memmap example

### ISSUE THREAD

**Issue by albertcthomas** [joblib/joblib#798]
The ['Numpy memmap' example](https://joblib.readthedocs.io/en/latest/auto_examples/parallel_memmap.html#speed-up-processing-of-a-large-data-array) is supposed to show that you can speed up the processing by "dumping large data array ahead of calling joblib.Parallel". However the times with and without dumping the large array are the same (0.64s).

**Comment by ogrisel** [comment]
This is true that I would not expect a big difference from a speed point of view. The main difference is the ability to dump and load numpy arrays without making a memory copy and to be able to load the data as a memory mapped array.

**Comment by albertcthomas** [comment]
Closing as solved and FWIW the times do not appear to be the same anymore. Thanks @ogrisel
