### ISSUE TITLE
Add a paragraph about serialization/pickle/cloudpickle in doc?

### ISSUE THREAD

**Issue by albertcthomas** [joblib/joblib#799]
For process-based parallelism, the current version of the doc only says that "data need to be serialized in a queue for communication with the worker processes".

I think it would be good to add a small paragraph/section about serialization in the doc, especially for the process-based parallelism part, briefly explaining what it is, how it is done in joblib (when pickle is used and when cloudpickle is used) and what this implies (e.g. why some objects might not be picklable).

WDYT?

**Comment by tomMoral** [comment]
That would be a great idea! :+1:

**Comment by albertcthomas** [comment]
Closing (PR #803).
