### ISSUE TITLE
Nested Parallel

### ISSUE THREAD

**Issue by KarenChen9999** [joblib/joblib#842]
I am trying to run nested parallel to reduce overhead in my functions. I have tested nested parallel in simple functions but it didn't work. It forces n_job to 1. some suggests to do "threading.current_thread().name = 'MainThread", but i am not sure how to do this. My 1st question: is it possible to run nested parallel using joblib? My 2nd question: if it is possible, how can i make it work?

My sample code:
```python
def fun1(n):
    storm_claim_b = pd.read_csv(csv_input_path+'STO_freq_b_up1.csv', nrows=100000)
    fun2(n)
    return

def fun2(n):
    result = Parallel(n_jobs=6)(delayed(fun3)(i) for i in range(10))    
    return

def fun3(n):
    storm_claim_b = pd.read_csv(csv_input_path+'STO_freq_b_up1.csv', nrows=100000)
    return
result = Parallel(n_jobs=6)(delayed(fun1)(i) for i in range(10))
```
warning messages:
/apps/anaconda3/envs/vectorized3/lib/python3.7/site-packages/joblib/parallel.py:547: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  **self._backend_args)

**Comment by ogrisel** [comment]
It's possible in the latest joblib versions but it's only going to be useful only for one or two levels of nesting provided that:
- your outer parallel loops does less iteration than the number of CPU cores on your machine;
- your code releases the GIL in the compute intensive part;
- and / or the performance bottleneck is I/O communication.

I am not sure if it's the case for `pd.read_csv`

Based on the warning message you get I believe you are not using the most recent version of joblib.

**Comment by KarenChen9999** [comment]
Thanks orgisel!. I have downloaded the most recent version of joblib. yes, it gets rid of the warning message. but the performance hasn't improved. it probably didn't work for the problem that i am trying to solve. so i have tried to reduce the overhead from my currently parallel function as much as possible and create separate function to run those overhead parallel instead. That seems to run much faster than before.

**Comment by ogrisel** [comment]
Ok great.
