### ISSUE TITLE
Oversubscription protection done by setting environment variables in worker initializer is not effective

### ISSUE THREAD

**Issue by ogrisel** [joblib/joblib#880]
This was implemented in @tomMoral's #701 but it does not work. For instance with loky:

- both the queue objects and the initializer are passed to worker as pickles
- the worker program starts by unpickling this preparation data
- then the initializer is called and sets the env variable

Unfortunately this is too late: the queue objects have custom reducers some of which customize the handling of numpy arrays. Therefore numpy is imported well before calling the initializer.

An alternative would be to extend loky such that is `fork_exec` function use to spawn the worker process can receive a dict of custom environment variables to be passed to `os.execve` instead of just using `os.execv`.

This would make it possible to set the environment variable prior to starting the Python interpreter of the workers.

**Comment by tomMoral** [comment]
Yes, I also recently saw this bad behavior. Another solution would be to use `threadpoolctl` in the initializer in complement. This way, even if some `openmp` library were to be loaded, the number of threads would be valid.

**Comment by ogrisel** [comment]
There are still some unresolved issues with some openmp combinations in threadpoolctl (https://github.com/joblib/threadpoolctl/pull/16) so I think it's still worth implementing the static / environment variable based protection.

**Comment by tomMoral** [comment]
I might have missunderstood but to me, the issue joblib/threadpoolctl#16
only appeared with nested call to C threadpools.
Implementing a solution that is backend dependent is fine by me but if we
can avoid it, this would avoid increasing the maintenance burden.

We can talk about it IRL tomorrow?

**Comment by ogrisel** [comment]
> I might have missunderstood but to me, the issue joblib/threadpoolctl#16 only appeared with nested call to C threadpools.

Yes. But the env var solution just feels safer and has no performance overhead. Arguably the performance overhead of threadpoolctl called in an initializer is very limited has well.

> We can talk about it IRL tomorrow?

Yes.

**Comment by ogrisel** [comment]
Now that the infrastructure to properly set environment variables in loky child processes tomMoral/loky#217 was merged, we can solve this issue by setting the maximum number of OpenMP/BLAS threads in child process via an environment variable with a value set by default to (cpu_count() / n_worker_processes): see #915.
