### ISSUE TITLE
Task queue usage?

### ISSUE THREAD

**Issue by gsakkis** [joblib/joblib#884]
Is it possible to use joblib, either directly or as a building block, to provide basic task queue functionality? What I mean is, instead of passing upfront a batch of tasks to be executed in parallel, have some sort of queue that tasks are added and executed dynamically. (I'm less interested in more advanced task queue features such as scheduling, retrying failed tasks, task prioritization, etc).

**Comment by tomMoral** [comment]
You should probably rely on `concurrent.futures` or `loky` directly for such features as the scope for `joblib` is (at least for now) embarrassingly parallel tasks only.

As the default backend in `joblib` is `loky`,  you will have very similar performances, but with more control as you can submit tasks and collect results one at a time.

The main difference (except for API) is the memmapping capabilities. But if needed, you can try and use the `joblib.executor.get_memmapping_executor` to have direct access to the custom executor used by `joblib`.

**Comment by gsakkis** [comment]
Ok thanks, makes sense; closing
