### ISSUE TITLE
joblib.memory for file-producing functions

### ISSUE THREAD

**Issue by gsakkis** [joblib/joblib#886]
I have a (presumably not quite unusual) use case of functions that generate files (e.g. csv or json) that I want to cache using `joblib.memory`. Is there a way or pattern to tell joblib to recompute the function when the output file is missing (or perhaps more generally when a condition is meet, e.g. older than `X datetime`) even when called with the same (cached) input arguments?

**Comment by SultanOrazbayev** [comment]
@gsakkis I am encountering a similar situation. Did you find a way?
