### ISSUE TITLE
error using ipyparallel backend with sklearn.cluster.kmeans

### ISSUE THREAD

**Issue by nikhil003** [joblib/joblib#916]
```
from ipyparallel import Client
from ipyparallel.joblib import IPythonParallelBackend
from sklearn.externals.joblib import Parallel, parallel_backend, register_parallel_backend, delayed

c1 = Client(profile="batch_slurm_python-3.6.1")
bview = c1.load_balanced_view()
register_parallel_backend('ipyparallel', lambda: IPythonParallelBackend(view=bview))
```

After doing the aforementioned steps, I tested the following code

```
with parallel_backend('ipyparallel'):
    cluster.KMeans(n_clusters=6, n_jobs=-1).fit(image_2d)
```

however, when i run the code, i get following error.

**AttributeError: 'IPythonParallelBackend' object has no attribute '_effective_batch_size'**

**Comment by pierreglaser** [comment]
Which version of `ipyparallel` are you using? I don't have an `IPython` cluster setup so I can't reproduce, but it seems that this error may have been fixed one year ago with this line.
 
https://github.com/ipython/ipyparallel/blob/f2c10970b782b60b2f2ec04e95ab88d204d6c6b9/ipyparallel/client/_joblib.py#L13

**Comment by nikhil003** [comment]
the issue has been answered. I was using ipyparallel 6.1.1 which didn't have the fix.
