### ISSUE TITLE
Parallel jobs do not see updated module variables

### ISSUE THREAD

**Issue by bersbersbers** [joblib/joblib#923]
Consider this example code:

`MyConsts.py`
```
myConst = 1
```

`Bug.py`
```
from joblib import Parallel, delayed

import MyConsts

print(f"we have got myConst == {MyConsts.myConst}")
MyConsts.myConst = 2
print(f"we have set myConst := {MyConsts.myConst}")

def Job(name):
    print(f"{name} sees myConst == {MyConsts.myConst}")

Parallel(n_jobs=1)(delayed(Job)("correct: serial") for _ in range(1))
Parallel(n_jobs=2)(delayed(Job)("a bug? parallel") for _ in range(1))
```

This outputs:
```
we have got myConst == 1
we have set myConst := 2
correct: serial sees myConst == 2
a bug? parallel sees myConst == 1
```

It seems that the update of `myConst` has not made it into the parallel environment that is used to run `Job`. Is this a bug or working as expected?

**Comment by GaelVaroquaux** [comment]
Yes, this is expected: they different codes are executed in different Python virtual machines (ie different environments). They do not share any state.

I am closing. Cheers!

**Comment by bersbersbers** [comment]
Thanks for your answer, but I don't think I understand. I agree: The workers are in different VMs and don't share environments. I get as much that updating a variable in one worker will not change the variable in a different worker.

But I am not updating a variable *in a worker*, and I am not talking about updating the state of a different worker: I am talking about the initial state of each VM.

Obviously, the initial state of each VM does share *something* with the global scope, as you can see by the first example failing and the second working:
failing:
```
from joblib import Parallel, delayed
def Job(name):
    print(f"{name} sees myLocalConst == {myLocalConst}")
    print(f"{name} sees myConst == {MyConsts.myConst}")
Parallel(n_jobs=2)(delayed(Job)("parallel") for _ in range(1))
```
working:
```
from joblib import Parallel, delayed
import MyConsts
myLocalConst = 1
def Job(name):
    print(f"{name} sees myLocalConst == {myLocalConst}")
    print(f"{name} sees myConst == {MyConsts.myConst}")
Parallel(n_jobs=2)(delayed(Job)("parallel") for _ in range(1))
```

So, in my first example. why does the *initial state*  of each parallel VM see a value of the module variable that does not exist any more? If the initial state of parallel VM did not share anything with the global scope, then it should not see *any* value of `MyConsts.myConst`. But it does see one, so it must come from the global scope, just as a global variable does.

I find this highly counterintuitive, and I feel my confusion is somewhat similar to that of the OP of https://github.com/joblib/joblib/issues/921, who also noticed that the workers behave differently from the global scope.

I would be OK with the workers *not* seeing the imports from the global scope - but seeing an old value, I am not sure this should be intended.

**Comment by shenrun** [comment]
I got a similar problem and found that the 'multiprocessing' backend gave a reasonable result. This is quite tricky and makes this package less reliable.
