### ISSUE TITLE
Ability to spawn parallel jobs from a child thread

### ISSUE THREAD

**Issue by kitchoi** [joblib/joblib#932]
`loky` and `multiprocessing` backend have the following logic which prevent parallelizing from a child thread:
https://github.com/joblib/joblib/blob/fd585ce36faba338fa1c71949cf29ed8e8f5ea19/joblib/_parallel_backends.py#L412-L419

That causes `SequentialBackend` to be used as a fallback. In use cases where the jobs to be parallelized are spawned from distributed framework such as `dask.distributed` (i have this use case), or just an application trying to do things asynchronously, `Parallel` could be called from a child thread. 

From offline discussion with @pierreglaser, this check is to prevent over subscriptions.
One possibility is to allow this restriction to be switched off at the user's discretion?

**Comment by tomMoral** [comment]
I recently opened a PR to add a parameter to deactivate this over-subscription protection (#919) following #865. It still need some discussion about the precise API and naming but it seems to be working.

Does it feels like it would solve your problem too?

**Comment by kitchoi** [comment]
Thank you @tomMoral!  Yes looks like your PR will solve this problem.
Thanks for pointing out there is an existing issue #865.
Closing as duplicate (As author I hope it is okay for me to close my own issue?).

**Comment by tomMoral** [comment]
Yes it is okay! ;)
Thanks
