### ISSUE TITLE
[Parallel(n_jobs=5)]: Using backend SequentialBackend with 1 concurrent workers.

### ISSUE THREAD

**Issue by omarcr** [joblib/joblib#947]
When I put nested parallel jobs I get the following message:
`[Parallel(n_jobs=5)]: Using backend SequentialBackend with 1 concurrent workers.`

Which does not allow me to run some part of the code in parallel, how can I fix it?

**Comment by tomMoral** [comment]
In its current implementation, `joblib` does not allow you to use nested parallelism directly.

If you don't need any nesting protection, a possible way of doing this would be to create your own backend such as:


```python
from joblib._parallel_backends import LokyBackend

class NestedBackend(LokyBackend):
    def get_nested_backend(self):
        backend = NestedBackend()
        backend.nested_level = 0
        return backend, None

from joblib import Parallel, delayed
def print_pid(level=0):
    import os
    import time
    time.sleep(.2)
    print(f"Level {level}: {os.getpid()}")


def nested():
    print_pid(1)
    Parallel(n_jobs=2)(delayed(print_pid)(2) for _ in range(2))


backend = NestedBackend()
    
print_pid() 
Parallel(n_jobs=2, backend=backend)(delayed(nested)() for _ in range(2))
```

Give output:

```
Level 0: 22317
Level 1: 22362
Level 1: 22361
Level 2: 22395
Level 2: 22398
Level 2: 22393
Level 2: 22394
```

**Comment by tomMoral** [comment]
It seems like your program is trying to serialize the `backend` object. One you have set the `backend` object in the outer most call to `Parallel`, it will be passed automatically to the children so you don't need to set it in the inner call. Does this solve your issue?

**Comment by omarcr** [comment]
Thank you, solved now!

**Comment by tomMoral** [comment]
Great! Thanks for the feedback.
