### ISSUE TITLE
Log when memory fails due to unpicklable function output

### ISSUE THREAD

**Issue by rggjan** [joblib/joblib#952]
I just spent hours trying to find out why my function didn't get cached when using `@memory.cache`. It turns out the reason was that the function returned an object where `pickle` threw an exception when trying to pickle it to disk.

This exception was silently swallowed in `_store_backends.py`:
```
    def dump_item(self, path, item, verbose=1):
        """Dump an item in the store at the path given as a list of
           strings."""
        try:
            item_path = os.path.join(self.location, *path)
            if not self._item_exists(item_path):
                self.create_location(item_path)
            filename = os.path.join(item_path, 'output.pkl')
            if verbose > 10:
                print('Persisting in %s' % item_path)

            def write_func(to_write, dest_filename):
                with self._open_item(dest_filename, "wb") as f:
                    numpy_pickle.dump(to_write, f,
                                      compress=self.compress)

            self._concurrency_safe_write(item, filename, write_func)
        except:  # noqa: E722
            " Race condition in the creation of the directory "
```

It would be great if at least a log message would be generated along the lines of "function XY could not be cached due to unpicklable function result", even if this is just logged at a high verbosity level.

**Comment by ogrisel** [comment]
I agree it should not be swallowed. This is causing many people to waste time debugging very silent issues. Better be explicit and find out what is the list of exception types that can arise in case of race condition when creating the cache directory.

**Comment by GaelVaroquaux** [comment]
One of the design principles behind joblib caching was to never break, so
that it could be considered as safe.

That said, I do agree that we could make a better job of reporting
problems and helping users fix them.

**Comment by ogrisel** [comment]
If the users expect the code to be cached it's actually causing a very hard to debug breakage by swallowing the exceptions.

I agree we should at the very least print the exception traceback on stderr but as a user I would rather have it to fail early to make it easier to debug my code.

**Comment by tomMoral** [comment]
This is something related to #896.
The `except` seems to be aimed at avoiding concurrent race in creating folders.
I am not sure it was originally to avoid pickling issues. 

I agree that we should at least warn the user. Raising an error seems fine here as the user is expected his work to be cached so it is an error to fail caching.

**Comment by tnielens** [comment]
Same here, I spent several hours testing different changes and reading the documentation to figure out why my output wasn't cached and what I did wrong. An error message in the log would have been quite helpful :).

**Comment by Nielius** [comment]
I also just spent several hours trying to find out why my output wasn't being cached. I've created a PR: https://github.com/joblib/joblib/pull/1359

**Comment by jeremiedbb** [comment]
#1359 added a warning to report pickling errors that occur in the caching mechanism, which will be turned into an error in version 1.5. It also added a warning (`CacheWarning`) to report all other exceptions.
